### ISSUE TITLE
Provide access to `encrypted` field in TerminalSettings in displayUrls/eventUrls / Make a new release

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-java-api-library#1022]
I'd need to access `encrypted` field in TerminalSettings in displayUrls/eventUrls. Latest library release [19.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/19.0.0) does not contain that feature, but you have already implemented that in `develop` branch:

https://github.com/Adyen/adyen-java-api-library/blame/develop/src/main/java/com/adyen/model/management/Url.java#L53

Could you make a new release that contains this feature?

**Comment by jsyrjala** [comment]
My intention is always to set `encrypted=true` so if current implementation already defaults to that, then this works for me.

**Comment by jsyrjala** [comment]
Library v19.0.0 disables always the encryption. So v19.0.0 won't work for my case. But v20.0.0 seems to have been already relesed.

**Comment by jillingk** [comment]
Hi @jsyrjala,

Thanks a lot for reaching out to us here. Yes we did indeed just add this field to the new release, that should hopefully fix your issue! If it's not the case, or if you run into anything else, please let us know and we will take a look at it.

Best, Jilling
Adyen
