### ISSUE TITLE
SaleToPOIResponses for Twint in Switzerland can't be deserialized

### ISSUE THREAD

**Issue by scriptease** [Adyen/adyen-java-api-library#1037]
**Describe the bug**
SaleToPOIResponses for Twint in Switzerland can't be deserialized

**How to reproduce**
Decode a SaleToPOIResponses from Twint in Switzerland using
`TerminalAPIGsonBuilder.create().fromJson(json, TerminalAPIResponse.class);`

**Expected behavior**
The result contains the SaleToAcquirerData and doesn't complain about an object being expected instead of the string.

**Desktop (please complete the following information):**
 - Java Version: 1.8
 - Library Version: 17.1.0, 20.0.0

**Additional context**
Pull request will follow

**Comment by scriptease** [comment]
PR: https://github.com/Adyen/adyen-java-api-library/pull/1038

**Comment by jillingk** [comment]
Hi @scriptease,

We've just released your fix! Thanks again for contributing, it's much appreciated :)

Best, Jilling
Adyen

**Comment by scriptease** [comment]
Awesome 🙏
