### ISSUE TITLE
API Response and SDK models are mismatching in "Get all payment methods" - merchant level

### ISSUE THREAD

**Issue by cb-hariprasath** [Adyen/adyen-java-api-library#1042]
**Describe the bug**

**Get all payment methods** (merchant level) - https://docs.adyen.com/api-explorer/Management/1/get/merchants/_merchantId_/paymentMethodSettings
v1 of this API response has following output:

<img width="1083" alt="image" src="https://github.com/Adyen/adyen-java-api-library/assets/106537957/5dff4672-e4ed-4e2c-aaa8-0d199bb0ab9e">

_**data** -> **PaymentMethod** -> (payment_method)_
```
{
    "itemsTotal": 1,
    "pagesTotal": 1,
    "data": [
        {
            "PaymentMethod": {
                "businessLineId": "SE322JV223222Q5HW8ZLR2RQR",
                "id": "PM322PW223224W5HW8ZM5594Q",
                "type": "amex",
                "storeId": "ST3224X223223V5HW8ZM4CKSP",
                "enabled": true,
                "countries": [],
                "currencies": [],
                "allowed": true,
                "verificationStatus": "valid",
                "customRoutingFlags": [],
                "reference": "01H16"
            }
        }
    ]
}
```

But the `com.adyen.model.management.PaymentMethodResponse` model has `private List<PaymentMethod> data`, which is wrong

This **PaymentMethod** is equivalent to following response:

```
{
    "itemsTotal": 1,
    "pagesTotal": 1,
    "data": [
        {
            "businessLineId": "SE322JV223222Q5HW8ZLR2RQR",
            "id": "PM322PW223224W5HW8ZM5594Q",
            "type": "amex",
            "storeId": "ST3224X223223V5HW8ZM4CKSP",
            "enabled": true,
            "countries": [],
            "currencies": [],
            "allowed": true,
            "verificationStatus": "valid",
            "customRoutingFlags": [],
            "reference": "01H16"
        }
    ]
}
```

Also there is v3 version of the same API that gives following output:

```
{
    "itemsTotal": 1,
    "pagesTotal": 1,
    "data": [
        {
            "storeIds": [
                "ST3224X223223V5HW8ZM4CKSP"
            ],
            "businessLineId": "SE322JV223222Q5HW8ZLR2RQR",
            "id": "PM322PW223224W5HW8ZM5594Q",
            "type": "amex",
            "enabled": true,
            "countries": [],
            "currencies": [],
            "allowed": true,
            "verificationStatus": "valid",
            "customRoutingFlags": [],
            "reference": "01H16"
        }
    ]
}
```
Problem with this response is **storeIds** field is returned as array of strings

**How to reproduce**
Hit the API https://docs.adyen.com/api-explorer/Management/1/get/merchants/_merchantId_/paymentMethodSettings using latest v20.0.0 SDK and it will throw error

**Expected behavior**
**_Solution 1:_**
With API version v1 -> Update the `com.adyen.model.management.PaymentMethodResponse` model with `data` field similar to API docs
**_Solution 2:_**
Update API version to v3 -> Also update `com.adyen.model.management.PaymentMethod` model with `storeId` field as array of string

**Desktop (please complete the following information):**
 - Library Version: 20.0.0

**Comment by cb-hariprasath** [comment]
Hi @jillingk, please take a look at this issue

**Comment by cb-hariprasath** [comment]
@jillingk Thank you so much for the update :)

**Comment by jillingk** [comment]
Hi @cb-hariprasath,

We've finally gotten around to release all the fixes plus some additional features. Thanks again for bringing this to our attention and apologies for the delay releasing this!

Best, Jilling
Adyen
