### ISSUE TITLE
Support for Local Terminal API?

### ISSUE THREAD

**Issue by alegd** [Adyen/adyen-java-api-library#1047]
**Java version**: 11
**Library version**: 20.0.0
**Description**
I'm developing an Android app that will be installed in an S1F2 device. I have my code written in React-Native, and since React Native doesn't have access to modules on the standard node lib (crypto, https, etc.), I've created a native module with Kotlin and succesfully install the adyen-java-api-lib. The issue comes when I try to make a request to the Local Terminal API. I'm seeing this error `Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive; at path $]`.
Also I've seen in the repo README that there is no version suported for [Local/Cloud-based Terminal API](https://docs.adyen.com/point-of-sale/terminal-api-reference). Does that means not support at all?

**Comment by scriptease** [comment]
I think I had a very similar exception in issue #1037

If the exception is cause by parsing a POI Response which contains a base64 encoded SaleToAcquirerData it should be fixed in 20.1.0.

But maybe it is another case, a json would help.

**Comment by wboereboom** [comment]
Hi @alegd ,

Sorry for taking so long to respond (it seemed @scriptease had a handle on things 💪 ).
Are you still dealing with this issue, or has the advice @scriptease gave resolved your issue?

Happy to give further assistance if required. 
I can also confirm we do support both Local and Cloud-based Terminal API, and will continue to do so.

Kind Regards,
Wouter
Adyen
