### ISSUE TITLE
Fetching terminal settings fails with JSON parsing error

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-java-api-library#1049]
**Describe the bug**
Fetching terminal settings fails with JSON parsing error. 

It seems that Adyen API response has a new field `restartHour` and adyen-java-api-library fails parsing that response.
Current version of [API specs](https://docs.adyen.com/api-explorer/Management/1/get/terminals/_terminalId_/terminalSettings) do not have `restartHour` field.
This operation was working at least 2-3 weeks ago.

The main problem here is that this unexpectedly started failing and library should handle unsupported fields in a compatible manner.

```
java.lang.IllegalArgumentException: The field `restartHour` in the JSON string is not defined in the `Hardware` properties. JSON: {\"restartHour\":4}\n\tat com.adyen.model.management.Hardware.validateJsonObject(Hardware.java:150)
\tat com.adyen.model.management.TerminalSettings.validateJsonObject(TerminalSettings.java:666)
\tat com.adyen.model.management.TerminalSettings$CustomTypeAdapterFactory$1.read(TerminalSettings.java:743)
\tat com.adyen.model.management.TerminalSettings$CustomTypeAdapterFactory$1.read(TerminalSettings.java:733)
\tat com.google.gson.TypeAdapter$1.read(TypeAdapter.java:204)\n\tat com.google.gson.Gson.fromJson(Gson.java:1227)\n\tat com.google.gson.Gson.fromJson(Gson.java:1137)
\tat com.google.gson.Gson.fromJson(Gson.java:1047)\n\tat com.google.gson.Gson.fromJson(Gson.java:982)\
tat com.adyen.model.management.TerminalSettings.fromJson(TerminalSettings.java:759)
\tat com.adyen.service.management.TerminalSettingsTerminalLevelApi.getTerminalSettings(TerminalSettingsTerminalLevelApi.java:99)
\tat com.adyen.service.management.TerminalSettingsTerminalLevelApi.getTerminalSettings(TerminalSettingsTerminalLevelApi.java:77)
\tat 
```

**How to reproduce**

We are using Adyen test environment. 
```kotlin
val config =  Config().apply {
        this.apiKey = "..."
        environment = Environment.TEST
        connectionTimeoutMillis = 12000
        readTimeoutMillis = 12000
    }

val terminalSettingsApi = TerminalSettingsTerminalLevelApi(Client(config))
terminalSettingsApi.getTerminalSettings(terminalId)
```

**Expected behavior**

I expected that fetching terminal settings works. If there are any fields that current adyen java api doesn't support, they are ignored.

**Desktop (please complete the following information):**
 - Java Version: 11 Amazon Lambda runtime
 - Library Version: com.adyen:adyen-java-api-library:20.0.0

**Additional information**
- related issue #1024

**Comment by jsyrjala** [comment]
I guess you have already fixed this https://github.com/Adyen/adyen-java-api-library/blame/develop/src/main/java/com/adyen/model/management/TerminalSettings.java#L647 but not yet released the fix.

**Comment by jillingk** [comment]
Hi @jsyrjala,

We've have just released all of the fixes we've done over the past weeks. Thanks for bringing this to our attention and please do reach out if you encounter any other issues!

Best, Jilling
Adyen
