### ISSUE TITLE
Tokenization : SaleToAcquirerData is missing field recurringProcessingModel

### ISSUE THREAD

**Issue by scriptease** [Adyen/adyen-java-api-library#1052]
**Describe the bug**

The documentation specifies that the SaleToAcquirerData contains a setting recurringProcessingModel with values CardOnFile, Subscription, or UnscheduledCardOnFile
https://docs.adyen.com/point-of-sale/recurring-payments#make-initial-payment
```
In SaleData.SaleToAcquirerData include:

shopperReference: your unique reference for this shopper (minimum length three characters).
shopperEmail: optional. The shopper's email address, if you collected that in the first step.
recurringProcessingModel: CardOnFile, Subscription, or UnscheduledCardOnFile. We will create a token for later payments, and save the shopper reference and shopper email on our platform. See [Tokenization parameters](https://docs.adyen.com/point-of-sale/recurring-payments#tokenization-parameters).
```

However the shopperReference and shopperEmail are available the recurringProcessingModel enum is not

**How to reproduce**
See class https://github.com/Adyen/adyen-java-api-library/blob/aab24c5bf043951e146f61d47a9a40ddf7aede5f/src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java

**Expected behavior**
The recurringProcessingModel can be set on the SaleToAcquirerData to enable tokenization.

**Desktop (please complete the following information):**
 - Java Version: 1.8.0
 - Library Version: 20.1.0

**Additional context**
I will provide a pull request

**Comment by jillingk** [comment]
Hi @scriptease,

Thanks again for contributing!
