### ISSUE TITLE
[ITT-596]PaymentDetails.TypeEnum is missing kakaopay

### ISSUE THREAD

**Issue by Xpressik** [Adyen/adyen-java-api-library#1062]
There is missing "kakaopay" enum value in PaymentDetails.TypeEnum therefore it's impossible to proceed with kakaopay payments with 20.1.0 version.

**Comment by jillingk** [comment]
Hi @Xpressik,
 
Thanks for reaching out to us with your issue! I see indeed this payment method is missing currently, we've been battling some issues in the checkout API which caused us to be a bit behind on the actual API specifications. We're working on a fix though and expect to update and release everything next week!

Best, Jilling
Adyen

**Comment by wboereboom** [comment]
Hi @Xpressik,

You should be able to use kakaopay using the [StoredPaymentMethodDetails.java](https://github.com/Adyen/adyen-java-api-library/blob/4bc5a2c60efc281b4218245d77f2311948b6c85e/src/main/java/com/adyen/model/checkout/StoredPaymentMethodDetails.java#L86) class.

I hope that will resolve your issue.

Apologies for the belated response!
Kind Regards,
Wouter
Adyen
