### ISSUE TITLE
BalanceAccount class missing metadata in v19.0.0

### ISSUE THREAD

**Issue by johnsonxu-ott** [Adyen/adyen-java-api-library#1070]
**Describe the bug**
BalanceAccount class missing metadata in v19.0.0

**How to reproduce**
try{
            Client client = new Client(api_key_balance, Environment.TEST);
            BalanceAccounts balance_api = new BalanceAccounts(client);
            BalanceAccount account = balance_api.retrieve(accountHolderId);
}catch(Exception ex){
          ex.printStackTrace();
}

**Expected behavior**
BalanceAccount class add MetaData class

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: [1.8]
 - Library Version: [v19.0.0]

**Additional context**

**Comment by jillingk** [comment]
Hi @johnsonxu-ott,

Thanks for reaching out to us here! ```BalanceAccounts``` is there in the v19 library as you can see [here](https://github.com/Adyen/adyen-java-api-library/blob/19.0.0/src/main/java/com/adyen/service/balanceplatform/BalanceAccounts.java). If you want to be fully up to date, however, I recommend upgrading to our latest version which you can check on this [page](https://github.com/Adyen/adyen-java-api-library/releases).

As for the ```Metadata``` class I just checked and it's there in our latest library release! Please let us know if you're missing anything else.

Best, Jilling 
Adyen
