### ISSUE TITLE
Missing PIX CheckoutPaymentMethod

### ISSUE THREAD

**Issue by bgoyanna** [Adyen/adyen-java-api-library#1079]
**Java version**: x.y.z
**Library version**: x.y.z

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wboereboom** [comment]
Hi @bgoyanna,

Thanks for raising this issue.
You can configure a paymentMethod using PIX by using the `com.adyen.model.checkout.PaymenDetails` object.
I acknowledge that this is might not be intuitive, and we that should work on our documentation.

I hope this solves your issue.

Kind Regards,
Wouter
Adyen

**Comment by bgoyanna** [comment]
Thanks, I was not finding the TypeEnum, cause each class has one, it was getting mixed....
