### ISSUE TITLE
Trying to run classic API `getAccountHolder` always responding with 422 and error code 10_035

### ISSUE THREAD

**Issue by siddharthmlkLSPD** [Adyen/adyen-java-api-library#1084]
**Describe the bug**
I am consuming 17.4.0 tag which contains the classic API implementations. All of sudden it is giving 422 and error code 10_035 for every request. I am not getting what does it mean. I can see the account exist on Adyen test dashboard.

**How to reproduce**
Just consuming `Account` service and calling `getAccountHolder` method

**Expected behavior**

**Screenshots**
response: 
```status: 422
    errorCode: 10_035
    message: Failed to retrieve account holder 'ABC-ABC-ABC'
    errorType: validation
    pspReference: null
    invalidFields: null
}, statusCode=422, message=HTTP Exception, responseHeaders={Transfer-Encoding=[chunked], traceparent=[00-aab59385b69c23727cea470c1af74f9e-0a9e3725b28e7ef7-01], Set-Cookie=[JSESSIONID=59E9B50AD8F2B641BA6F8FBD7AECC58E.test103e; Path=/cal; Secure; HttpOnly], pspReference=[8816891855700555], Date=[Wed, 12 Jul 2023 18:12:50 GMT], Content-Type=[application/json;charset=UTF-8]}}
```

**Desktop (please complete the following information):**
 - Java Version: [17]
 - Library Version: [17.4.0]

**Additional context**

**Comment by wboereboom** [comment]
Hi @siddharthmlkLSPD,

Thanks for raising this issue.
At first glance it seems like this might not be an SDK issue.
After a short investigation the problem might be the following:

After creating an AccountHolder, one should consume the `ACCOUNT_HOLDER_CREATED` Webhook notification before trying to retrieve said AccountHolder.

If this does not help you, I'm afraid I have to forward you to our support team, which will provide further guidance and troubleshooting.

Lastly; The classic Platforms endpoints are not suitable for new merchants, and we do not recommend you build an integration using them. Please consider using the [Configuration API](https://docs.adyen.com/api-explorer/balanceplatform/2/overview) to build your integration.

I hope this helps to some extent.

Kind Regards,
Wouter
Adyen

**Comment by wboereboom** [comment]
**Update:** A quick deep dive by a colleague tells me the accountHolder was created on a different Marketplace ID  from the one on which the retrievals have been attempted.
Please make sure the same Marketplace ID is used for both creation and retrieval of the accountHolder.

I hope that's another piece to the puzzle you are trying to solve.

Kind Regards,
Wouter
Adyen

**Comment by siddharthmlkLSPD** [comment]
Hey @wboereboom thanks. Yes, different Marketplace ID was the issue. Actually, the error was not clear enough to understand. Thanks a lot for doing thorough investigation on my behalf.
Yes, we are soon going to migrate from classic API to Balance platform API but till then need to make it work :)
