### ISSUE TITLE
doku_ovo and doku_wallet payment methods are not defined

### ISSUE THREAD

**Issue by senturkozer** [Adyen/adyen-java-api-library#1086]
**Describe the bug**
doku_ovo and doku_wallet payment methods are not defined.

**How to reproduce**
Try to deserialize the below json. It will fail.
```json
{
  "riskData": {
    "clientData": "eyJ2ZXJzaW9uIjoiMS4wLjAiLCJkZXZpY2VGaW5nZXJwcmludCI6ImRmLXRpbWVkT3V0In0="
  },
  "paymentMethod": {
    "type": "doku_ovo",
    "checkoutAttemptId": "997e4dc0-8ebf-49a0-8ad8-0b78d4754be116896195562913474AC598528E647516BB947F665E4A437C5228743860DA49A090D48F4C3FD3E"
  },
  "clientStateDataIndicator": true
}
```

The same applies to doku_wallet as well.

**Expected behavior**
It should serialize to correct payment method.

**Screenshots**
I do not have a screenshot.

**Desktop (please complete the following information):**
 - Java Version: 11
 - Library Version: 20.1.1

**Additional context**
Thank you.

**Comment by wboereboom** [comment]
Hi @senturkozer,

Thanks for raising this issue.
We are aware these types are currently not included in our documentation and API Libraries.
We are working to include these types into the library shortly. I apologise for any inconvenience this might cause you.

Kind Regards,
Wouter
Adyen

**Comment by senturkozer** [comment]
Thank you @wboereboom. Can you let us know when the fix is released?

**Comment by wboereboom** [comment]
Yes, will do. We are working to address this issue through our automation pipelines so it will fix this for all our API libraries. Hence the delay for this relatively small issue.
Please bear with us.

Kind Regards,
Wouter
Adyen

**Comment by senturkozer** [comment]
Do we have any updates on this?

**Comment by jillingk** [comment]
Hi @senturkozer,

Merged and ready to be added to the library! Will be included in the Monday release as well.

Best, Jilling
Adyen

**Comment by senturkozer** [comment]
Hi @jillingk. Is this released? Can we check?

**Comment by jillingk** [comment]
Hi @senturkozer,

Apologies for the slow response. This fix is released as of the latest beta release (soon to be major), which you can see [here](https://github.com/Adyen/adyen-java-api-library/blob/891748f221506e296b3fbcd426a4afb517d887b2/src/main/java/com/adyen/model/checkout/DokuDetails.java#L78).

Best, Jilling
Adyen
