### ISSUE TITLE
Unable to parse problems from Configuration webhook

### ISSUE THREAD

**Issue by ka30hegde** [Adyen/adyen-java-api-library#1095]
**Describe the bug**
On receiving the Account holder configuration webhooks (balancePlatform.accountHolder.created, balancePlatform.accountHolder.updated), we need to parse the problems to find out the verification remedies and update on our side.
In the library, problems is a plain Object in class AccountHolderCapability.
private List<Object> problems = null;

We can not cast also as the structure is not a standard one and has LinkedTreeMap -> ArrayList -> LinkedTreeMap -> .... 

Is there an easy way to get the problems details?

**How to reproduce**
Consume the webhook and parse the problems.

**Expected behavior**
Problems should have an explicit structure to parse it.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - Java Version: 11
 - Library Version: 20.1.1

**Additional context**
NA

**Comment by jillingk** [comment]
Hi @ka30hegde,

Thanks for reaching out to us with this issue! We're aware of this issue regarding this broken model and are working on it to fix this.

Apologies for the inconvenience, I'll keep you posted on the progress regarding the fix!

Best, Jilling
Adyen

**Comment by ka30hegde** [comment]
Thanks for the response @jillingk 

We are already in the coding phase, integrating to BP.
As a workaround, we are planning to make another call to LEM api and parse the VerificationErrors object.
com.adyen.service.legalentitymanagement.LegalEntitiesApi#checkLegalEntitysVerificationErrors(java.lang.String)

What do you suggest?

Is there a timeline, by when the fix might be available?

**Comment by jillingk** [comment]
Hi @ka30hegde,

Apologies for the delayed response. We needed to do a little bit of a refactoring internally however it seems to be (almost) ready now. I'll keep you posted on the progress!

Best, Jilling
Adyen
