### ISSUE TITLE
PaymentFee type in split not working without sending amount for refund request.

### ISSUE THREAD

**Issue by ankushgoyal96** [Adyen/adyen-java-api-library#1124]
**Describe the bug**
PaymentFee type in split not working without sending amount for refund request.
Getting error - The required field `amount` is not found in the JSON string: {\"description\":\"Payment Fee\",\"reference\":\"sample-refund-20230911-A1\",\"type\":\"PaymentFee\"}

**How to reproduce**
Initiate refund request without sending amount 
or set this in your code -
```
final Split split = new Split()
                    .type(Split.TypeEnum.PAYMENTFEE)
                    .reference(reference)
                    .description("Payment Fee");
```

**Expected behavior**
Direct Adyen API is working, It should also work as expected.

- Java Version: 11
- Library Version: 19.0.0

**Additional Context**
we are using hosted onboarding and your doc suggests to use v2 api.
I can't use latest version of this library because above 19.0.0, it is using v3 lem api.

**Comment by jillingk** [comment]
Hi @ankushgoyal96,

Thanks for reaching out to us with your issue! Indeed I see this seems to be an issue in this older version of the library. Could you please upgrade to the latest library version and use the fix explained in this issue #1107 to downgrade to v2 LEM for hosted onboarding. I know it is not an ideal solution, and the v3 version of LEM will be fixed soon, however for the time being this is the only way we could handle this from the libraries. Let me know if you run into anything during this fix, or if you encounter any other problems!

Best, Jilling
Adyen

**Comment by ankushgoyal96** [comment]
@jillingk Currently we are working on migrating from classic to balance platform api. We have to support both classic integration and balance platform but classic api support has removed from latest version of sdk. Could you please suggest how to proceed here?

**Comment by ankushgoyal96** [comment]
@jillingk Please reply!

**Comment by jillingk** [comment]
Hi @ankushgoyal96,

Apologies for the delayed answer, we're thinking of the best solution to make this migration possible. I'll let you know asap!

Best, Jilling
Adyen

**Comment by ankushgoyal96** [comment]
@jillingk Any update?

**Comment by DjoykeAbyah** [comment]
Hi @ankushgoyal96! 

Did you happen to spot the workaround provided? If so, did it resolve your issue?
If there are no further concerns, I'll go ahead and close this issue for now. Remember, you can always open a new one if you run into any other issues!

Best regards,

Djoyke
Adyen
