### ISSUE TITLE
Support retries and exponential backoff

### ISSUE THREAD

**Issue by eric-gfm** [Adyen/adyen-java-api-library#1140]
**Java version**: 17.x.x
**Library version**: any

**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
I would like the Java client to support retries and exponential backoff as recommended in https://docs.adyen.com/development-resources/api-idempotency/?programming_language=java#retries-and-exponential-backoff. I would also like to be able to configure the maximum number of times a request will be retried in the event of a failure.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by AlexandrosMor** [comment]
Hello @eric-gfm, 

The libraries should be a thin layer between merchant's application and Adyen's Apis. This functionality could be implemented on the application side in a way that fits merchants needs and they could have more control.
For now we could close this ticket

kind regards,
Alexandros
Adyen
