### ISSUE TITLE
In com.adyen.model.transferwebhooks.TransferData$PlatformPaymentTypeEnum, value 'Remainder' is missing

### ISSUE THREAD

**Issue by jmatter** [Adyen/adyen-java-api-library#1157]
**Describe the bug**
When receiving a transfer webhook event of the type _Remainder_, the payload can't be deserialized because the `PlatformPaymentTypeEnum` is incomplete:

> com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.adyen.model.transferwebhooks.TransferData$PlatformPaymentTypeEnum`, problem: Unexpected value 'Remainder'

**How to reproduce**
Create a transaction with splits that don't add up to the transaction total amount (or a transaction without any splits so the whole amount goes to the liable account).

**Versions**
 - Java Version: [17.0.6]
 - Library Version: [21.6.0]

**Comment by jillingk** [comment]
Hey @jmatter,

Thanks for reaching out to us with this issue. I see the value is there in our specifications but we simply have not yet generated this yet as it's quite a new feature that was recently added. I'll make sure this value is included in the next release we do for this library (we do bi-weekly releases).

Best, Jilling
Adyen

**Comment by jmatter** [comment]
@jillingk 
Thank you!

**Comment by jmatter** [comment]
Issue is resolved in v22
