### ISSUE TITLE
Getting a 401 when making a call to Checkout sessions

### ISSUE THREAD

**Issue by Zander1983** [Adyen/adyen-java-api-library#1163]
**Describe the bug**
I successfully integrated with the Adyen Payments API last year. When I did that integration, I used a username and password. Now I want to integrate with the Checkout API. However I cannot successfully make a request to the Checkout /sessions endpoint

**How to reproduce**
I generated an API Key at Developers -> API Credentials under my Adyen Test account here https://ca-test.adyen.com/ca/ca/config/api_credentials_new.shtml

Here is the curl Im running (I have the correct values for "my-api-key" and "my-merchant-account" in the real call):

```
curl --location 'https://checkout-test.adyen.com/checkout/v69/sessions' \
--header 'x-api-key: my-api-key' \
--header 'Content-Type: application/json' \
--header 'Accept-Charset: UTF-8' \
--header 'Cookie: JSESSIONID=A390F827E55E6344493CF98CBA21C00B.test108e' \
--data '{
  "amount": {
    "value": 1000,
    "currency": "EUR"
  },
  "channel": "Web",
  "countryCode": "NL",
  "lineItems": [
    {
      "amountIncludingTax": 5000,
      "description": "Sunglasses",
      "quantity": 1
    },
    {
      "amountIncludingTax": 5000,
      "description": "Headphones",
      "quantity": 1
    }
  ],
  "merchantAccount": "my-merchant-account",
  "reference": "fb514d80-7e2d-478b-a077-807576175183",
  "returnUrl": "https://orders.domain.com",
  "splitCardFundingSources": false,
  "threeDSAuthenticationOnly": false
}'
```

**Expected behavior**
However Im getting the response:
```
{
    "status": 401,
    "errorCode": "000",
    "message": "HTTP Status Response - Unauthorized",
    "errorType": "security"
}
```

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: 8
 - Library Version: 18.3.0

**Additional context**

**Comment by Zander1983** [comment]
@jillingk thans for the replce. I instead tried Basic Auth and this worked, I got back sessionData. However, looking at the Adyen Java library, `apiKeyRequired` is hardcoded to true:

https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/ApiKeyAuthenticatedService.java#L30


When I look at the code in com.adyen.httpclient.AdyenHttpClient i see that because isApiKeyRequired is true, it sets the API key not the Basic Auth, which is what I need: https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/httpclient/AdyenHttpClient.java#L218

My code is:

```
        Config config = new Config();
        config.setUsername(apiConfiguration.getPaymentConfiguration().getAdyenUsername());
        config.setPassword(CbSystem.getAdyenPassword());

        Client adyenClient = new Client(config);

        if (CbSystem.getEnvironment().equals("production")) {
            adyenClient.setEnvironment(Environment.LIVE, apiConfiguration.getPaymentConfiguration().getEnvironment());
        } else {
            adyenClient.setEnvironment(Environment.TEST, null);
        }

        Checkout checkout = new Checkout(adyenClient);

        CreateCheckoutSessionRequest checkoutSession = new CreateCheckoutSessionRequest();
        checkoutSession.countryCode("NL");
        checkoutSession.merchantAccount("my-account");
        // (optional) set WEB to filter out payment methods available only for this platform
        checkoutSession.setChannel(CreateCheckoutSessionRequest.ChannelEnum.WEB);
        checkoutSession.setReference(UUID.randomUUID().toString()); // required
        checkoutSession.setReturnUrl("https://orders.clevercards.com");

        com.adyen.model.Amount amountDetails = new com.adyen.model.Amount();
        amountDetails.setCurrency("EUR");
        amountDetails.setValue(1000L);
        checkoutSession.setAmount(amountDetails);
        // set lineItems required for some payment methods (ie Klarna)
        checkoutSession.setLineItems(Arrays.asList(
                new LineItem().quantity(1L).amountIncludingTax(5000L).description("Sunglasses"),
                new LineItem().quantity(1L).amountIncludingTax(5000L).description("Headphones"))
        );


        try {
            checkout.sessions(checkoutSession);
//            CreateCheckoutSessionResponse checkoutSessionResponse = checkout.sessions(checkoutSessionRequest);
        } catch (com.adyen.service.exception.ApiException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```

How can I force it to use Basic Auth?

**Comment by jillingk** [comment]
Hi @Zander1983,

The checkout services you are using here are extending the `Service` class and not the class you linked. If you provide basic auth it should work fine, as the class you linked was merely something we used in the past. 

Let me know if you're able to make the requests using basic auth! I'll see if we can remove some of these legacy classes from the library to prevent confusion.

Best, Jilling
Adyen
