### ISSUE TITLE
cannot make a "Hosted Checkout integration" with the latest adyen-java-api-library

### ISSUE THREAD

**Issue by WPisces** [Adyen/adyen-java-api-library#1166]
**Describe the bug**
To make a "Hosted Checkout integration" need a request param named "mode" in the sessions api, but I not found the param in CreateCheckoutSessionRequest

**Screenshots**
<img width="1040" alt="image" src="https://github.com/Adyen/adyen-java-api-library/assets/40688687/91b12ef3-1385-4b50-87ad-cce95699ade6">

<img width="961" alt="image" src="https://github.com/Adyen/adyen-java-api-library/assets/40688687/6f9243fc-448e-4a48-9bc4-63d359a39b47">

**Desktop (please complete the following information):**
 - Java Version: [17.0.7]
 - Library Version: [21.6.0] and [22.0.0-beta]

**Comment by Aleffio** [comment]
Hi @WPisces ,
the `mode` field is now available, starting from the library version [22.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/v22.0.0).
Thanks for your patience and please let us know if you encounter any issues.

Best regards,
Alessio
Adyen
