### ISSUE TITLE
Adding support for Idempotency Header

### ISSUE THREAD

**Issue by yavanap** [Adyen/adyen-java-api-library#119]
**Java version**: 1.8
**Library version**: 1.5.2
**Description**

Support for adding Idempotency-Key via Java API for all POST Requests made to adyen. 
Needed for our (Adobe) integration with Adyen.

**Comment by rkewlani** [comment]
Hi,
Thanks! We have created a task to address this and we will soon release a new API version with idempotency-key support. We will keep you posted.

Regards,
Rajni
Adyen

**Comment by yavanap** [comment]
@rkewlani if there is any update on the progress of the above request.. please keep us posted.. based on the ETA.. we have to plan our launch..

**Comment by rkewlani** [comment]
Hi @yavanap ,
We have already completed changes. We will release it in upcoming release 1.6.0 today or tomorrow. 
Thanks,
Rajni
Adyen

**Comment by rkewlani** [comment]
Hi @yavanap ,
1.6.0 is released.

Thanks,
Rajni
Adyen

**Comment by rkewlani** [comment]
Hi @yavanap ,
1.6.0 is released.

Thanks,
Rajni
Adyen
