### ISSUE TITLE
ERROR WHEN PARSING THE JSON

### ISSUE THREAD

**Issue by jvrs2812** [Adyen/adyen-java-api-library#1194]
Using the TerminalCloudAPI.async method, with an invalid api-key, the api returns an XML with status code 401 but when parsing the body returned to the ApiException error we will have a problem, the solution I found for now was to do a if ternary to avoid this error handling in the parser.

![error convert](https://github.com/Adyen/adyen-java-api-library/assets/64158791/68def52f-e2b2-4267-ba14-576bea42a853)

If you want, I can make this commit and create the PR for you.

**Comment by jillingk** [comment]
Hi @jvrs2812,

Thanks for reaching out here and apologies for the slow response. This issue will be fixed with the upcoming pr refreshing our terminal integration in this library. #1219 if you want to follow it.

Best, Jilling
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @jvrs2812!

Are you still encountering this problem? If so, would you mind sharing the steps you're taking to reproduce it? It would be helpful for us to better tackle this issue.

Thanks!

Djoyke
Adyen

**Comment by DjoykeAbyah** [comment]
Hi @jvrs2812,

I'm closing this issue for now. However, if you encounter any further issues, feel free to contact us!

Djoyke
Adyen
