### ISSUE TITLE
Failed deserialization for TransferRouteRequirements

### ISSUE THREAD

**Issue by costinpapuc** [Adyen/adyen-java-api-library#1198]
**Describe the bug**
_Failed deserialization for TransferRouteRequirements: 0 classes match result, expected 1 (through reference chain: com.adyen.model.balanceplatform.TransferRouteResponse["transferRoutes"]->java.util.ArrayList[0])
com.fasterxml.jackson.databind.JsonMappingException: Failed deserialization for TransferRouteRequirements: 0 classes match result, expected 1 (through reference chain: com.adyen.model.balanceplatform.TransferRouteResponse["transferRoutes"]->java.util.ArrayList[0])_

**Possible Fix**
The field `requirements` in `TransferRoute` should be of type `List<TransferRouteRequirements>`
https://github.com/Adyen/adyen-java-api-library/blob/main/src/main/java/com/adyen/model/balanceplatform/TransferRoute.java#L148

**How to reproduce**
`transferRoutesApi.calculateTransferRoutes(validTransferRouteRequest);`

**Expected behavior**
No deserialization error

**Desktop**
 - Java Version: 17
 - Library Version: 22.1.0

**Comment by DjoykeAbyah** [comment]
Hi @costinpapuc!

Thanks for spotting this issue and reaching out. The fix has been implemented and is set to be included in the next release.

What was:
```java
public TransferRouteRequirements getRequirements()
```
Will be:
```java
public List<TransferRouteRequirementsInner> getRequirements() {
    return requirements;
}
```

If you have any further questions or encounter any more issues, feel free to let us know!

Regards,

Djoyke
Adyen
