### ISSUE TITLE
CreateAcquisitonRequest

### ISSUE THREAD

**Issue by pintobikez** [Adyen/adyen-java-api-library#1212]
**Describe the bug**
When creating a CreateAcquisitonRequest our app is able to call the Adyen APP, user is is requested for a Card, but it stays forever loading, never returning a response.

**How to reproduce**

```
CardAcquisitionRequest cardAcquisitionRequest = new CardAcquisitionRequest();
CardAcquisitionTransaction cardAcquisitionTransaction = new CardAcquisitionTransaction();
		cardAcquisitionTransaction.setTotalAmount(paymentRequest.getPaymentTransaction().getAmountsReq().getRequestedAmount());
cardAcquisitionRequest.setCardAcquisitionTransaction(cardAcquisitionTransaction);

// Instantiation and assignment of the sales object, within the request object
SaleData saleData = new SaleData();
saleData.setSaleTransactionID(paymentRequest.getSaleData().getSaleTransactionID());
saleData.setTokenRequestedType(TokenRequestedType.CUSTOMER);
cardAcquisitionRequest.setSaleData(saleData);

terminalAPIRequestBuilder.withCardAcquisitionRequest(cardAcquisitionRequest);
terminalAPIRequest = terminalAPIRequestBuilder.build();
response = terminalLocalApi.request(terminalAPIRequest);
```

**Expected behavior**
Response should have a value, but we never get a response.

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: 11.0.20
 - Library Version: 22.1.0

**Additional context**

**Comment by jillingk** [comment]
Hi @pintobikez,

Thanks a lot for reaching out to us here! Usually when the local terminal api keeps loading there is an issue with the network setup (that is it can't find the device on the local network). Did you try all the trouble shooting steps documented on our [Adyen Docs](https://docs.adyen.com/point-of-sale/design-your-integration/network-and-connectivity/networking-issues/) page?

**Comment by pintobikez** [comment]
Hi @jillingk we have made it work. The problem was related to the ServiceId.
The issue we now face is when performing a CardAcquisitionRequest there is no CurrencyCode, so instead of showing the customer that we are "trying" to charge lets say 50MXN, it will always show the currency of EUR (our default currency).

**Comment by DjoykeAbyah** [comment]
Hi @pintobikez! Given the nature of the problem, it might be more efficient to contact our support team directly for assistance. You can create a ticket through the customer area. I'll go ahead and close this issue for now. You can always open a new one if you run into any other issues.

Best regards,

Djoyke
Adyen
