### ISSUE TITLE
Warning logs `Warning, indecisive deserialization for CheckoutPaymentMethod: 2 classes match result, expected 1`

### ISSUE THREAD

**Issue by senturkozer** [Adyen/adyen-java-api-library#1217]
**Describe the bug**
After we upgraded to 22.1.0, we started to see warning logs `Warning, indecisive deserialization for CheckoutPaymentMethod: 2 classes match result, expected 1`. When we debugged, we saw that, some payment methods, e.g. `onlinebanking_IN` and `wallet_IN` were defined in two classes, e.g. `BillDeskDetails` and `PaymentDetails`.  We believe they should only be defined in `BillDeskDetails` class.

**How to reproduce**
Deserialize a payments details of `onlinebanking_IN` or `wallet_IN`.

**Expected behavior**
Payments details of `onlinebanking_IN` or `wallet_IN` should be deserialized to `BillDeskDetails` only.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Java Version: [11]
 - Library Version: [22.1.0]

**Additional context**
N/A

**Comment by jillingk** [comment]
Hi @senturkozer,

Thanks a lot for reaching out to us here and flagging this issue. We're aware of it and pushing a fix any minute now. Next release will contain the fix. Apologies for the inconvenience :)

Best, Jilling
Adyen

**Comment by senturkozer** [comment]
@jillingk I still see them under the `PaymentDetails`class. 🤔

**Comment by senturkozer** [comment]
@jillingk I think current release does not contain this fix.

**Comment by jillingk** [comment]
@senturkozer as you can see [in this commit](https://github.com/Adyen/adyen-java-api-library/commit/c3063f3932aac00758b6fd3d61c9267b4c905bb0#diff-a07501d6f61f9c9f626010fff5016f692bfa5b2b31f4d323298606d53423096f) these payment tx-variant has been removed from the BillDeskDetails class which resolves your issue.

If I'm missing something here please let me know!
