### ISSUE TITLE
OutputContent is missing setOutputText method

### ISSUE THREAD

**Issue by jamesmudd** [Adyen/adyen-java-api-library#1220]
**Describe the bug**
The class `com.adyen.model.nexo.OutputContent` has `getOutputText()` but no `setOutputText()` This is needed if implementing a custom message at then end of a card acquistion flow e.g. as discribed here https://docs.adyen.com/point-of-sale/card-acquisition/#cancel-completed

As this field is a List<OutputText> which can only contain 2 elements header and footer maybe a nicer or additional api could be `get/setHeader` and `get/setFooter` taking String ignoring the additional formatting options, or just taking `OutputText`

**Desktop (please complete the following information):**
 - Java Version: 17.0.9
 - Library Version: 22.1.0

**Comment by jillingk** [comment]
Hey @jamesmudd,

Thanks for reaching out to us here! Interesting to hear that the setter is not there, as it very much should of course. We're currently trying to add generated terminal models, so when we merge that your issue should be solved. #1219 if you want to follow the pr. 

Best, Jilling
Adyen

**Comment by jamesmudd** [comment]
I still don't think this is fixed in the latest version 25.0.0

The class `com.adyen.model.nexo.OutputContent` [OutputContent](https://github.com/Adyen/adyen-java-api-library/blob/main/src/main/java/com/adyen/model/nexo/OutputContent.java) still doesn't not have a `setOutputText` method?
