### ISSUE TITLE
HTTP Exception for Refused transaction with error code 905_1

### ISSUE THREAD

**Issue by fctg-pip** [Adyen/adyen-java-api-library#1223]
**Describe the bug**
When making a transaction using an unrecognised/unconfigured payment method (in this case a UATP card), the transaction is processed and refused, but the response is not returned and instead an HTTP exception is thrown.

**How to reproduce**
1. Make a payment to Adyen using the PaymentsApi.java payments() method with a payment method/card that has not been configured on the account.
2. HTTP exception is thrown from the Adyen library in the Resource.java request() method
3. Verify in Adyen that the transaction request was received and refused.
4. There is no log of the API call under Developers > Logs either.

**Expected behavior**
Since the request is received and subsequently refused, a 200 response should be returned with the PSP reference, result code, and refusal reason.

**Screenshots**
Error message in Adyen
![image](https://github.com/Adyen/adyen-java-api-library/assets/108645120/49b60654-433a-4960-9bce-88d955b346e9)

Stack trace within Adyen library:
com.adyen.service.exception.ApiException: HTTP Exception 

      at com.adyen.service.resource.Resource.request(Resource.java:114) 

      at com.adyen.service.resource.Resource.request(Resource.java:92) 

      at com.adyen.service.checkout.PaymentsApi.payments(PaymentsApi.java:209) 

      at com.adyen.service.checkout.PaymentsApi.payments(PaymentsApi.java:194)

Resource.java request() function:
![image](https://github.com/Adyen/adyen-java-api-library/assets/108645120/1d0dabd1-7d51-4164-802e-4540e7844c2b)

**Desktop (please complete the following information):**
 - Java Version: [17.0.9]
 - Library Version: [21.5.0]

**Additional context**
This is a direct payment implementation for an enterprise and not an online checkout.

**Comment by jillingk** [comment]
Hi @fctg-pip,

Thanks for reaching out here! Could you please reach out to our support channels with this question? It seems your payment method has not been setup properly, which is something our support teams can help you with. If you have any other library related questions please let us know!

Best, Jilling 
Adyen

**Comment by jillingk** [comment]
Hey @fctg-pip,

Thanks for reaching out here and making us aware of this issue. We will investigate what response is returned in case of a refused action and how we should handle it. 

As for the refused itself, you can reach out to our support teams to properly setup your payment method :)

Best, Jilling
Adyen

**Comment by fctg-pip** [comment]
@wboereboom thank you for the clarification, I have adjusted the ApiException handling to extract the inner error message. Would it be possible to have ApiException detailMessage match or include the ApiError message? If not feel free to close this issue.
![image](https://github.com/Adyen/adyen-java-api-library/assets/108645120/60b6966b-2ba7-428e-b83e-a32eb49a229a)

**Comment by wboereboom** [comment]
Hi @fctg-pip ,

I see your point, and I think you're right. It would probably have been a bit cleaner if we'd done it like that in the first place. But at this time I don't think it's worth introducing a breaking change for it.
So I'm afraid all I can provide you with for now is bragging rights for knowing better than us.

I'm closing the issue as you seem to be unblocked.

Kind Regards,
Wouter
Adyen
