### ISSUE TITLE
Internal calls on .toJson() throws NoClassFoundError 'java.lang.NoClassDefFoundError' exception.

### ISSUE THREAD

**Issue by OchiengHosea** [Adyen/adyen-java-api-library#1224]
**Describe the bug**
While invoking `payment.authorise()` method in PaymentApi, NoClassFoundError 'java.lang.NoClassDefFoundError' exception is thrown. This error also happens when any object calls `.toJson()` method.
Upon inspecting internal libraries, theres a JSON.java class that appears to have errors related to jakarta, unresolved reference.

**How to reproduce**
Using version 21 or 22 with springboot 2.3.5, call the `payment.authorise()` or `paymentRequest.toJson()` method

**Expected behavior**
I expected the payment to get initiated when calling `payment.authorise()` or a JSON representation of the payment request object

**Screenshots**
<img width="1066" alt="image" src="https://github.com/Adyen/adyen-java-api-library/assets/33859011/946bf0e1-36b5-4964-86ff-5871b4e24b40">

**Desktop (please complete the following information):**
 - Java Version: [17.1.0]
 - Library Version: [21.0.0]
 - Kotlin 1.8
 - Springboot 2.3.5

**Additional context**
In your examples, I have realized that the newer versions use springboot 3, could there be incompatibility issue with springboot 2?

**Comment by AlexandrosMor** [comment]
Hello @OchiengHosea,

Thank you for letting us know about this issue. We are going to open an internal ticket to investigate it further. 

kind regards,
Alexandros
Adyen

**Comment by jillingk** [comment]
Hi @OchiengHosea,

Did you try installing the jakarta dependency manually? It might be that spring is not pulling the correct version.

Could you also perhaps supply me the depedency project of your project? That might be the easiest way to trouble shoot this.

Best, Jilling
Adyen
