### ISSUE TITLE
Is it possible to do tokenization (for unscheduled recurring/onetime payment) offline?

### ISSUE THREAD

**Issue by NerdFaisal404** [Adyen/adyen-java-api-library#1238]
Is it possible to do tokenization (for unscheduled recurring/onetime payment) offline? Such as my terminal is offline I do the tokenization and at a later time I do an auth with that token, is that possible offline? If yes, can you direct us on how to do it? Or is it possible to do something similar to tokenization for offline orders? 

_Can anybody share example code for offline tokenization?_

**Note : We have implemented tokenization in online mode.**

**Comment by wboereboom** [comment]
Hi @NerdFaisal404 ,

For questions on general Adyen features and support please reach out to support from the [customer area](https://ca-test.adyen.com/).

We can only help out with missing library features and functionality, as well as any bugs within the API library.
Sorry for the inconvenience, but I'm sure our tech support department can help you with this question!

Kind Regards,
Wouter
Adyen
