### ISSUE TITLE
Error parsing account holder created webhook JSON

### ISSUE THREAD

**Issue by AxelWard** [Adyen/adyen-java-api-library#1244]
**Describe the bug**
While processing Platform webhooks and attempting to parse an `AccountHolderNotificationRequest` from the webhook body I started getting

> Cannot construct instance of `com.adyen.model.configurationwebhooks.AccountHolder$StatusEnum`, problem: Unexpected value 'active'
> at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 17, column: 16] (through reference chain: com.adyen.model.configurationwebhooks.AccountHolderNotificationRequest["data"]->com.adyen.model.configurationwebhooks.AccountHolderNotificationData["accountHolder"]->com.adyen.model.configurationwebhooks.AccountHolder["status"])
> class com.fasterxml.jackson.databind.exc.ValueInstantiationException

**How to reproduce**
```
String testData = """
{
   "data":{
     "balancePlatform":"REDACTED",
     "accountHolder":{
       "contactDetails":{},
       "description":"Test Description",
       "legalEntityId":"LE555KH555555Z5KCRHRG5MC5",
       "capabilities":{
         "receiveFromPlatformPayments":{"enabled":true,"requested":true,"allowed":false,"verificationStatus":"pending"},
         "receiveFromBalanceAccount":{"enabled":true,"requested":true,"allowed":false,"verificationStatus":"pending"},
         "sendToBalanceAccount":{"enabled":true,"requested":true,"allowed":false,"verificationStatus":"pending"},
         "sendToTransferInstrument":{"enabled":true,"requested":true,"allowed":false,"requestedSettings":{"interval":"daily","maxAmount":{"currency":"EUR","value":0}},"verificationStatus":"pending"},
         "receivePayments":{"enabled":true,"requested":true,"allowed":false,"verificationStatus":"pending"}
       },
       "id":"AH5555Z555555P5KCRHRHC5NR",
       "status":"active"
     }
   },
   "environment": "test",
   "type": "balancePlatform.accountHolder.created"
}
"""
AccountHolderNotificationRequest.fromJson(testData)
```

**Expected behavior**

**Desktop:**
 - Java Version: [11.0.2]
 - Library Version: [24.0.0]

**Additional context**
I'm not sure when this started happening. We are in early app development and haven't been consuming Platform webhooks for some time now.

**Comment by AxelWard** [comment]
A quick follow up: It looks like this is being caused because the data received in the webhook has `"status": "active"` when the JSON parser is expecting `"status": "Active"`.

I'm happy to submit a PR to fix for this if the data coming from the webhook is correct and the parser just needs to be fixed.

**Comment by vojkny** [comment]
@AxelWard Can you post your code? I am implementing Webhooks as well and it seems to me that `WebhookHandler` class can only consume events from `ca-test.adyen.com` but not from `https://balanceplatform-test.adyen.com/` – the structure for both are completely different.

**Comment by AxelWard** [comment]
@vojkny The implementation for Platform and Standard webhooks is different, I'm assuming different teams worked on them. I'd love it if they were processed the same, but for now we basically have to have 2 different types of webhook processors.

In case anyone else has a similar issue, our technical rep at Adyen informed me that this particular error is caused by our webhook version being set to V2, which is unreleased right now. After backdating to V1 everything seems to be working fine again.

**Comment by vojkny** [comment]
So, how can I process the webhooks from Platform accounts? It is not super-clear from the docs.

**Comment by vojkny** [comment]
🙏
