### ISSUE TITLE
accountHolder.contactDetails should be deprecated?

### ISSUE THREAD

**Issue by vojkny** [Adyen/adyen-java-api-library#1248]
**Describe the bug**
According to documentation: https://docs.adyen.com/api-explorer/balanceplatform/2/post/accountHolders#request-contactDetails

this field should be deprecated. Ideally please validate what is correct and describe why it is deprecated in the code comment 🙏

**Comment by DjoykeAbyah** [comment]
Hi @vojkny!

Thanks for reaching out! We expect this to be updated in our libraries as well in one of the upcoming releases.

**Comment by jillingk** [comment]
Closing as we have pushed a fix to deprecate said fields
