### ISSUE TITLE
Missing metadata for BalanceAccounts and AccountHolders?

### ISSUE THREAD

**Issue by vojkny** [Adyen/adyen-java-api-library#1249]
Balance accounts and AccountHolders have documented `metadata` in API Docs:

- https://docs.adyen.com/api-explorer/balanceplatform/2/post/balanceAccounts#request-metadata
- https://docs.adyen.com/api-explorer/balanceplatform/2/post/accountHolders#request-metadata

However it seems to me that these are missing in the Java Api?

Eg.

```kotlin
legalEntitiesApi
            .createLegalEntity(
                LegalEntityInfoRequiredType()
                    .reference(user.name)
                    .type(LegalEntityInfoRequiredType.TypeEnum.INDIVIDUAL)
                    .metadata( << method missing >> )
```

**Comment by jillingk** [comment]
Hey @vojkny,

Thanks for reaching out here. Seems you might have confused the endpoints? The endpoints you linked use different methods than the one you pasted in the snippet. 

The explorer links you pasted correspond to these methods in the java library:
- [post balance](https://github.com/Adyen/adyen-java-api-library/blob/13ff139bfb22f9a4abde57e2923bd2afb31a4f81/src/main/java/com/adyen/service/balanceplatform/BalanceAccountsApi.java#L79)
- [post accountholder](https://github.com/Adyen/adyen-java-api-library/blob/13ff139bfb22f9a4abde57e2923bd2afb31a4f81/src/main/java/com/adyen/service/balanceplatform/AccountHoldersApi.java#L76)

Let me know if u can find the resources now you're looking for.

Best, Jilling 
Adyen

**Comment by vojkny** [comment]
you are right, I messed the realtionship between these, I am excusing myself.

**Comment by jillingk** [comment]
Don't worries there's a lot there :)

Let us know if you need any help!
