### ISSUE TITLE
Attachment setContent handling base64 encoding on behalf of the SDK client

### ISSUE THREAD

**Issue by afabris-kodypay** [Adyen/adyen-java-api-library#1259]
**Java version**: 21
**Library version**: 2.4.0

**Is your feature request related to a problem? Please describe.**
Using Document API is confusing because the Attachment.content takes as input a byte array but it's not immediately clear this needs to be Base64 encoded.
What happened is that I tried to upload an attachment passing the raw content byte array and this caused an error server side that was not immediately evident given it was "content type not supported".
I appreciate those class are automatically generated out of OpenAPI so no "translation magic" is applied, but having a method that accepts bytes you would expects it applies any adaptation logic needed by the server.

**Describe the solution you'd like**
Rename the content setter so that is explicit it needs a base64 byte array
Add a content setter that can base64 encode any raw byte array being passed.

**Describe alternatives you've considered**
Clearly specify assumptions in library docs (README?)

**Additional context**
N.A.

**Comment by DjoykeAbyah** [comment]
Hi @afabris-kodypay!

Apologies for the delayed reply. This is indeed confusing. We’ve updated our Readme to give more clarification about the usage of content in Attachments to prevent more confusion in the future. Thank you for bringing this to our attention!

Regards

Djoyke,
Adyen

**Comment by janaz** [comment]
Hi @DjoykeAbyah

The note added to the README mentions only the `com.adyen.model.legalentitymanagement.Attachment` class. 

There's a similar issue with the [`content`](https://github.com/Adyen/adyen-java-api-library/blob/67f33117153d6ef1f3e92bd871f76fa701ca28b7/src/main/java/com/adyen/model/disputes/DefenseDocument.java#L41) field in the `com.adyen.model.disputes.DefenseDocument` class. 

Does the advice from the README apply to `DefenseDocument` as well?

**Comment by jillingk** [comment]
Hi @janaz,

Yes similar types (like byte array) are handled the same throughout our libraries. 

Best, Jilling
Adyen
