### ISSUE TITLE
How can I simulate to test my interface?

### ISSUE THREAD

**Issue by kexiaoyang** [Adyen/adyen-java-api-library#126]
**Java version**: 1.8
**Library version**: 1.5.4
**Description**
Dear friends,
I want to integrate the Adyen Java library in my project.We use it in IOS and Android system,but I need to do some work for purpose of encapsulation.Such as get the payment methods of my account and response it to the front end.When I want to simulate to test the payment endpoint, I always make some mistakes suck as 
Exception in thread "main" ApiException{error=class ApiError {
    status: 422
    errorCode: 174
    message: Unable to decrypt data
    errorType: validation
    pspReference: null
}, statusCode=422, message=HTTP Exception}
	at com.adyen.service.Resource.request(Resource.java:61)
	at com.adyen.service.Checkout.payments(Checkout.java:61)
	at com.xxx.pay.service.AdyenService.payment(AdyenService.java:117)
	at com.xxx.pay.service.AdyenService.main(AdyenService.java:144)
How can I do to settle this problem?
My code is as follows:
request.setPaymentMethod(new HashMap<String, String>());
request.putPaymentMethodItem("type", "scheme");
request.putPaymentMethodItem("encryptedCardNumber", "6771 7980 2500 0004");
request.putPaymentMethodItem("encryptedExpiryMonth", "10");
request.putPaymentMethodItem("encryptedExpiryYear", "2020");
request.putPaymentMethodItem("encryptedSecurityCode", "737");
Best regards.

**Comment by kexiaoyang** [comment]
I want to settle this error, can you give me some advice?    message: Unable to decrypt data

**Comment by rkewlani** [comment]
Hi @kexiaoyang,
Can you please try following code:

request.setPaymentMethod(new HashMap<String, String>());
        request.putPaymentMethodItem("type", "scheme");
        request.putPaymentMethodItem("number", "6771 7980 2500 0004");
        request.putPaymentMethodItem("expiryMonth", "10");
        request.putPaymentMethodItem("expiryYear", "2020");
        request.putPaymentMethodItem("cvc", "737");
Please check following link for more information on parameter values:
https://adyen.github.io/adyen-java-api-library/checkout-api.html
Please let us know if you still face issues.

Thanks,
Rajni
