### ISSUE TITLE
Typo in TaxReportingClassification.BusinessTypeEnum

### ISSUE THREAD

**Issue by zzeng2** [Adyen/adyen-java-api-library#1265]
**Describe the bug**
In TaxReportingClassification.BusinessTypeEnum:
FINANCIALINSTITUTION_("financialInstitution.");
this value has extra underscore in name and extra dot in value, which caused exception when using fromValue.

**How to reproduce**
Call BusinessTypeEnum.fromValue("financialInstitution");

**Expected behavior**
The value should be correct string.

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: [19.0.2-zulu]
 - Library Version: [24.0.0]

**Additional context**
none

**Comment by DjoykeAbyah** [comment]
Hi @zzeng2! 

Thank you for reaching out to us. The latest release addressed this issue. We recommend updating to the latest version to resolve it!

Djoyke
Adyen
