### ISSUE TITLE
balancePlatform.accountHolder.updated webhook sends incorrect value in AccountHolder status

### ISSUE THREAD

**Issue by limealot** [Adyen/adyen-java-api-library#1287]
**Describe the bug**
The balancePlatform.accountHolder.updated sends "status" : "active" when it should be "status" : "Active" according to the Enum class, see https://github.com/Adyen/adyen-java-api-library/blob/main/src/main/java/com/adyen/model/configurationwebhooks/AccountHolder.java : 91

**How to reproduce**

1. Add a configuration webhook in balance platform CA and set the _Version_ to `2` in _Server configuration_.
2. Make a change to an account holder, e.g. on the hosted onboarding page, change the legal name of the company and click _Save and go to overview_. This should trigger a  `balancePlatform.accountHolder.updated` webhook event.
3. In your webhook endpoint you will see the  payload for the AccountHolderNotificationRequest and parsing the object  using the `BankingWebhookHandler` class will fail because the payload contains `"status" : "active"`.

**Expected behavior**
Parsing the payload should be successful, either by reading the Enum value without case sensitivity or by sending the correct value in the webhook payload.

**Screenshots**
![image](https://github.com/Adyen/adyen-java-api-library/assets/33153788/85a809a8-b868-428e-8e66-eb6dbb59813d)

**Desktop (please complete the following information):**
 - Java Version: [17.0.6]
 - Library Version: [25.1.0]

**Comment by wboereboom** [comment]
Hi @limealot,

Library v25.1.0 does not support Configuration Webhooks v2 yet (documented in our [README](https://github.com/Adyen/adyen-java-api-library/tree/v25.1.0?tab=readme-ov-file#supported-webhook-versions).
Our upcoming major release however will, and the models will match the actual webhook data.

Kind Regards,
Wouter
Adyen
