### ISSUE TITLE
BankingWebhookHandler its not being able to parse the payload correctly

### ISSUE THREAD

**Issue by helsoncruztw** [Adyen/adyen-java-api-library#1292]
I'm trying to parse the payload from balance platform webhook, more specific the [account holder updated](https://docs.adyen.com/api-explorer/balanceplatform-webhooks/latest/post/balancePlatform.accountHolder.updated)
Currently i'm trying to parse the payload using the `BankingWebhookHandler`. 
Even with a payload that should be valid, the `AccountHolderNotificationRequest` it's not Present.
Testing this i have noticed that the `status`, of account holder object in the payload, it's the problem.

the status in the payload it's lower case and in the `configurationwebhooks.AccountHolder` object the enum has the values with the first letter uppercase.

**How to reproduce**
Try to use `BankingWebhookHandler` to parse this payload:
{
  "data": {
    "balancePlatform": "platform",
    "accountHolder": {
      "id": "account-holder-id",
      "legalEntityId": "legal-entity-id",
      "status":"active"
    }
  },
  "environment": "test",
  "type": "balancePlatform.accountHolder.updated"
}

**Expected behavior**
Should be able to parse the json if the status is valid, not be case sensitive or return the correct value in payload.

**Screenshots**
Here the payload that i'm receiving
<img width="630" alt="image" src="https://github.com/Adyen/adyen-java-api-library/assets/150693422/ca62de6a-c81a-4bff-8639-a4b5b25ddbb0">

**Desktop (please complete the following information):**
 - Library Version: 25.1.0

**Comment by DjoykeAbyah** [comment]
Hi @mvaltas-gfm, @helsoncruztw!

I'm not sure If you already spotted version 26.0.0 on maven central. In case you weren't able to check yet you can find it [here](https://central.sonatype.com/artifact/com.adyen/adyen-java-api-library)
