### ISSUE TITLE
Error: Field acsTransId not defined in ThreeDS2Result properties

### ISSUE THREAD

**Issue by RajuMmgs** [Adyen/adyen-java-api-library#1295]
**Describe the bug**
I'm encountering an error while integrating with the Adyen Java API library (version 20.0.0). When I attempt to process a 3D Secure 2.0 authentication, I receive the following response:

{
    "code": "500",
    "message": "Failure",
    "errorList": [
        "The field `acsTransId` in the JSON string is not defined in the `ThreeDS2Result` properties. JSON: {\"acsTransId\":\"6d5ee284-3971-4ea0-a770-c9abbadc74e8\",\"authenticationType\":\"01\",\"authenticationValue\":\"QURZRU4gM0RTMiBURVNUIENBVlY=\",\"dsTransID\":\"3d627f3f-0f85-470f-a587-aa89a6281778\",\"eci\":\"07\",\"interactionCounter\":\"1\",\"messageVersion\":\"2.1.0\",\"threeDSServerTransID\":\"c52d5f20-762e-4b6c-a196-78536651f135\",\"transStatus\":\"N\",\"transStatusReason\":\"01\"}"
    ],
    "errorMessage": "The field `acsTransId` in the JSON string is not defined in the `ThreeDS2Result` properties. JSON: {\"acsTransId\":\"6d5ee284-3971-4ea0-a770-c9abbadc74e8\",\"authenticationType\":\"01\",\"authenticationValue\":\"QURZRU4gM0RTMiBURVNUIENBVlY=\",\"dsTransID\":\"3d627f3f-0f85-470f-a587-aa89a6281778\",\"eci\":\"07\",\"interactionCounter\":\"1\",\"messageVersion\":\"2.1.0\",\"threeDSServerTransID\":\"c52d5f20-762e-4b6c-a196-78536651f135\",\"transStatus\":\"N\",\"transStatusReason\":\"01\"}"
}

**How to reproduce**
POM dependency

<dependency>
	<groupId>com.adyen</groupId>
	<artifactId>adyen-java-api-library</artifactId>
	<version>20.0.0</version>
</dependency>

tried to call  payments/details API

Java Code

Client client = new Client(X_API_KEY, Environment.TEST);

PaymentsApi service = new PaymentsApi(client);	

PaymentCompletionDetails paymentCompletionDetails = new PaymentCompletionDetails().threeDSResult(adyenPaymentDetailsRequest.getDetails().getThreeDSResult());

 // Define payment details request
DetailsRequest detailsRequest = new DetailsRequest();
detailsRequest.setDetails(paymentCompletionDetails);

// Make the API call
PaymentDetailsResponse response = service.paymentsDetails(detailsRequest);

// Process the response
System.out.println("Payment Details Response:");
	

response : 

"{
    "code": "500",
    "message": "Failure",
    "errorList": [
        "The field `acsTransId` in the JSON string is not defined in the `ThreeDS2Result` properties. JSON: {\"acsTransId\":\"6d5ee284-3971-4ea0-a770-c9abbadc74e8\",\"authenticationType\":\"01\",\"authenticationValue\":\"QURZRU4gM0RTMiBURVNUIENBVlY=\",\"dsTransID\":\"3d627f3f-0f85-470f-a587-aa89a6281778\",\"eci\":\"07\",\"interactionCounter\":\"1\",\"messageVersion\":\"2.1.0\",\"threeDSServerTransID\":\"c52d5f20-762e-4b6c-a196-78536651f135\",\"transStatus\":\"N\",\"transStatusReason\":\"01\"}"
    ],
    "errorMessage": "The field `acsTransId` in the JSON string is not defined in the `ThreeDS2Result` properties. JSON: {\"acsTransId\":\"6d5ee284-3971-4ea0-a770-c9abbadc74e8\",\"authenticationType\":\"01\",\"authenticationValue\":\"QURZRU4gM0RTMiBURVNUIENBVlY=\",\"dsTransID\":\"3d627f3f-0f85-470f-a587-aa89a6281778\",\"eci\":\"07\",\"interactionCounter\":\"1\",\"messageVersion\":\"2.1.0\",\"threeDSServerTransID\":\"c52d5f20-762e-4b6c-a196-78536651f135\",\"transStatus\":\"N\",\"transStatusReason\":\"01\"}"
}"

**Expected behavior**
Required proper message with failure reason

**Desktop (please complete the following information):**
 - Java Version: [1.8]
 - Library Version: [20.0.0]

**Comment by jillingk** [comment]
Hi @RajuMmgs,

Apologies for the delayed response. The issue should be solved when upgrading to a more recent version of the library as I can see the field is there.

Best, Jilling
Adyen
