### ISSUE TITLE
TransferNotificationRequest cannot be parsed for tips

### ISSUE THREAD

**Issue by limealot** [Adyen/adyen-java-api-library#1302]
**Describe the bug**
When using BankingWebhoookHandler to parse a payload from a "balancePlatform.transfer.updated" webhook event that contains 
`"platformPaymentType" : "Tip"`
it fails, most likely because there is no  `TIP("Tip")` value in the enum _com.adyen.model.transferwebhooks.PlatformPayment.PlatformPaymentTypeEnum_

**How to reproduce**
Parse the webhook payload containing a Tip, using the BankingWebhoookHandler class.

**Expected behavior**
TransferNotificationRequest object should be parsed successfully with a correct value (e.g. `TIP("Tip")`) in 
`object.getData().getCategoryData().getPlatformPayment().getPlatformPaymentType()`

**Desktop (please complete the following information):**
 - Java Version: [17.0.6]
 - Library Version: [26.0.0]

**Additional context**
For the same webhook, when receiving the Seller split, the platformPaymentType is completely missing in the payload.

**Comment by wboereboom** [comment]
Hey @limealot,

Sorry for the inconvenience!
Unfortunately development is sometimes faster than our ability to update the library.
We released release v26.1.0 of the library this week, which should resolve your issue.
Happy coding, I hope the rest of your integration journey will be smooth.

Kind Regards,
Wouter
Adyen
