### ISSUE TITLE
 SEPA Bank Transfer payment method  PaymentResponseAction cannot be deserialized

### ISSUE THREAD

**Issue by cristianvanderwey** [Adyen/adyen-java-api-library#1303]
**Describe the bug**
When using the SEPA Bank Transfer payment method the PaymentResponseAcction cannot be deserialized.

**How to reproduce**

Do a payment request for bankTransfer_IBAN:

```
{
  "amount": {
    "currency": "EUR",
    "value": 10
  },
  "countryCode" : "NL",
  "reference": "****",
  "paymentMethod": {
    "type": "bankTransfer_IBAN"
  },
  "merchantAccount": "****"
}
```

When deserializing the paymentsResponse:

`PaymentResponse paymentsResponse = paymentsApi.payments(paymentRequest);
`
It cannot deserialize the PaymentResponseAction:

```
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.fasterxml.jackson.databind.JsonMappingException: Unexpected IOException (of type java.io.IOException): Failed deserialization for PaymentResponseAction: 0 classes match result, expected 1
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected IOException (of type java.io.IOException): Failed deserialization for PaymentResponseAction: 0 classes match result, expected 1
```

**Expected behavior**
The PaymentResponseAction should be mapped to the right class.

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: [17]
 - Library Version: [25.0.0]

**Additional context**

**Comment by wboereboom** [comment]
Hi @cristianvanderwey ,

Thanks for raising this issue, and I'm sorry to hear you're dealing with these issues.
Do you have a JSON response or a PsPreference so we might look into the API response and see how it mismatches with the library models?

Kind Regards,
Wouter
Adyen

**Comment by cristianvanderwey** [comment]
Hi Wouter thanks for your respsone! Here is the response we are receiving:

```
{
  "pspReference": "JMLQSQSBSH2ZTL65",
  "resultCode": "Received",
  "action": {
    "paymentMethodType": "bankTransfer_IBAN",
    "totalAmount": {
      "currency": "EUR",
      "value": 20000
    },
    "beneficiary": "Adyen",
    "iban": "NL13TEST0123456789",
    "bic": "TESTNL02",
    "reference": "JML-QSQS-BSH2-ZTL65",
    "type": "bankTransfer"
  },
  "merchantReference": "****"
}
```

**Comment by jillingk** [comment]
Hi @cristianvanderwey,

The action part cannot be deserialised as the type is not recognised by the library. We will look into adding this asap!

Best, Jilling
Adyen

**Comment by davince72** [comment]
Any update on this issue? Some rumours say it would be fixed / released half of august.

**Comment by DjoykeAbyah** [comment]
Hi @cristianvanderwey and @davince72!

Good news! This fix has just been released in [[src/main/java/com/adyen/model/checkout/CheckoutBankTransferAction.java](https://github.com/Adyen/adyen-java-api-library/pull/1343/files#diff-88c55ec7f811accc81311abdd386ac191ab0f39e9255b461a74bbdcc4d28bfa8)](https://github.com/Adyen/adyen-java-api-library/pull/1343/files#diff-88c55ec7f811accc81311abdd386ac191ab0f39e9255b461a74bbdcc4d28bfa8).   

Kind regards,  

Djoyke
Adyen
