### ISSUE TITLE
AccountHolderNotificationRequest cant parse AccountHolderNotificationRequest webhook

### ISSUE THREAD

**Issue by mattbachmann-toast** [Adyen/adyen-java-api-library#1308]
**Describe the bug**
I received the following request in my test environment

```
{
    "data": {
        "balancePlatform": "Toast-US-Issuing",
        "accountHolder": {
            "contactDetails": {},
            "description": "Bachmann test holder",
            "legalEntityId": "LE32CKZ223225Q5KT9J773SQC",
            "reference": "I think we can put restaurantGuid here",
            "capabilities": {
                "receiveFromBalanceAccount": {
                    "enabled": "true",
                    "requested": "true",
                    "allowed": "false",
                    "verificationStatus": "pending"
                },
                "sendToBalanceAccount": {
                    "enabled": "true",
                    "requested": "true",
                    "allowed": "false",
                    "verificationStatus": "pending"
                },
                "sendToTransferInstrument": {
                    "enabled": "true",
                    "requested": "true",
                    "allowed": "false",
                    "verificationStatus": "pending"
                },
                "issueCard": {
                    "enabled": "true",
                    "requested": "true",
                    "allowed": "false",
                    "verificationStatus": "pending"
                },
                "useCard": {
                    "enabled": "true",
                    "requested": "true",
                    "allowed": "false",
                    "verificationStatus": "pending"
                }
            },
            "id": "AH32957223227M5KT9JQWFHWB",
            "status": "Active"
        }
    },
    "environment": "test",
    "type": "balancePlatform.accountHolder.created"
}
```

For the life of me I was not able to get this parsed.  I tried

```
BankingWebhookHandler(body).accountHolderNotificationRequest.ifPresent { 
            ....redacted...
        }
```

But `BankingWebhookHandler(body).accountHolderNotificationRequest` was always null. So I tried to process it a bit more manually.

```
AccountHolderNotificationRequest.fromJson(body)
```

This crashes with 

```
Cannot construct instance of `com.adyen.model.configurationwebhooks.AccountHolder$StatusEnum`, problem: Unexpected value 'Active'
```

This is because the enum does not have `Active` defined. It has `active`. This is when I figured it was a bug and here I am.

**How to reproduce**
Pass the provided webhook body to `AccountHolderNotificationRequest.fromJson(body)`

**Expected behavior**
Seems like it should parse

**Screenshots**

<img width="1295" alt="Screenshot 2024-06-11 at 6 03 05 PM" src="https://github.com/Adyen/adyen-java-api-library/assets/101126316/da3d8dc0-753f-4593-8cca-c809c5ec0d78">

**Desktop (please complete the following information):**
 - Java Version: [11.0.15] 
 - Library Version: [26.0.0]

**Additional context**

**Comment by tddouglas** [comment]
I think this is a version mismatch issue. Can you adjust the version of your configuration webhook to v2
[V1](https://docs.adyen.com/api-explorer/balanceplatform-webhooks/1/post/balancePlatform.accountHolder.updated#request-data-accountHolder-status) was capitalized while [v2](https://docs.adyen.com/api-explorer/balanceplatform-webhooks/2/post/balancePlatform.accountHolder.updated#request-data-accountHolder-status) is not

**Comment by mattbachmann-toast** [comment]
@tddouglas I dont see how I can set a version in either the creation screen or the edit screen

<img width="1215" alt="Screenshot 2024-06-13 at 10 38 57 AM" src="https://github.com/Adyen/adyen-java-api-library/assets/101126316/6128dbcf-9dd9-46e7-b158-353e70b8bd3c">


<img width="1120" alt="Screenshot 2024-06-13 at 10 41 16 AM" src="https://github.com/Adyen/adyen-java-api-library/assets/101126316/0182a561-fcc0-4bfa-927a-978d7a10a7ce">

**Comment by mattbachmann-toast** [comment]
the manage webhook button only lets me delete the webhook

**Comment by jillingk** [comment]
Hi @mattbachmann-toast,

Good catch @tddouglas! The webhook models are indeed for the v2 version, hence only these can be deserialised I'm afraid.

I'm not sure why you can't change the version though, I just checked and you should be able to do so by (re-)configuring the webhook setup. Are you sure you're using the `Platforms` config and not the `Payments` one?

Best, Jilling
Adyen

**Comment by mattbachmann-toast** [comment]
@jillingk Whatever happens when I click "Create new webhook" in https://balanceplatform-test.adyen.com/balanceplatform/developers/webhooks/
<img width="877" alt="Screenshot 2024-06-13 at 11 44 34 AM" src="https://github.com/Adyen/adyen-java-api-library/assets/101126316/58bda5ae-dece-420a-9fa3-b9cc7c9df714">

I then click add on the 'recommended' webhook for configuration updates

**Comment by mattbachmann-toast** [comment]
Looks like I cant change the version once the hook exists (dropdown greyed out)  Ill try and remake them and hope that works

**Comment by jillingk** [comment]
@mattbachmann-toast,

Hmm weird that you can't change an existing webhook on balanceplatform, I was able to do so on https://ca-test.adyen.com/ca. Not sure if you have access to that, but that might be worth a try. Either way I'll go ask around why it can't be changed after the fact.

In the meantime I hope it's not too much work to redo the current configs.

Best, Jilling 
Adyen

**Comment by mattbachmann-toast** [comment]
@jillingk I gotta apoloigzie. I had some confusion on my end. 

Some of the webhooks only have 1 version and in those cases the webhook version is greyed out. On the ones that *do* have multiple versions I was able to change them.


But if you are in a position to file feedback or open a ticket... I feel like I was setup for failure because I *did* confirm that the configuration webhook (and I think one other) default to a lower version then the library actually supports.

IF the current version of the library only supports the most current version it seems like creating a new hook should default to the most current version. I feel like I got setup for failure here trying to figure this out. 

as someone just beginning to onboard I had assumed the defaults were good and the most recent version of the library was what I should start with.

**Comment by jillingk** [comment]
Hey @mattbachmann-toast,

Ahh right for the generic webhooks we only have one version and the other (balanceplatform) webhooks have multiple! 

Don't worry about the mix up though that happens :)

I will take the standard version as a valid feedback point though. We actively push for using the latest versions so I'm not sure why we would have a standard lower version by default..

Hope the rest of your onboarding will run smoothly. If you run into anything don't hesitate to reach out here!

Best, Jilling
Adyen
