### ISSUE TITLE
Creation of AccountHolder from webhook contents fails

### ISSUE THREAD

**Issue by vincenthartsteen** [Adyen/adyen-java-api-library#1320]
**Describe the bug**
Mapping of the `accountHolder` that is part of e.g. the `balancePlatform.accountHolder.updated` webhook fails. The `status` field for that account-holder is `Active` but that value can't be mapped to the `AccountHolder$StatusEnum`.

**How to reproduce**
Create or update an account-holder on the Balance platform. A webhook similar to the following will be sent:
```
{
  "data": {
    "balancePlatform": "MontroPlatform",
    "accountHolder": {
      "description": "Woe1200",
      "legalEntityId": "LE3293X223225R5KZBDZ99KZ5",
      "reference": "3402",
      "capabilities": {
        "receiveFromPlatformPayments": {
          "enabled": "true",
          "requested": "true",
          "allowed": "false",
          "problems": [
            {
              "entity": {
                "id": "LE3293X223225R5KZBDZ99KZ5",
                "type": "LegalEntity"
              },
              "verificationErrors": [
                {
                  "code": "2_902",
                  "message": "Terms Of Service forms are not accepted.",
                  "remediatingActions": [
                    {
                      "code": "2_902",
                      "message": "Accept TOS"
                    }
                  ],
                  "type": "invalidInput"
                }
              ]
            }
          ],
          "verificationStatus": "pending"
        }
      },
      "id": "AH3294C223227N5KZBDZBBCVG",
      "status": "Active"
    }
  },
  "environment": "test",
  "type": "balancePlatform.accountHolder.updated"
}
```

From that webhook, get the value for the `accountHolder` and pass that into `AccountHolder.fromJson(...)`

Notice that an exception is thrown:
```
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.adyen.model.balanceplatform.AccountHolder$StatusEnum`, problem: Unexpected value 'Active'
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 35, column: 13] (through reference chain: com.adyen.model.balanceplatform.AccountHolder["status"])
```

The enum (`AccountHolder$StatusEnum`) only has values in lowercase. I created a simple test for this and indeed when I change `Active` to `active` the method returns an AccountHolder object.

So either the enum should accept the `Active` or the contents of the webhook should exactly match the values of the enum.

**Expected behavior**
The `AccountHolder.fromJson` should return a valid AccountHolder object based on the contents of the webhook. 

**Screenshots**
Error message is shown in previous section.

**Desktop (please complete the following information):**
 - Kotlin Version: [1.8.22]
 - Library Version: [26.2.0]

**Additional context**
We are migrating our application from the Bank environment to the Balance platform and are now receiving these webhooks on the TEST environment.

**Comment by wboereboom** [comment]
Hi @vincenthartsteen ,

Thanks for raising this issue.
The Accountholder you are trying to parse should be part of the configuration notification models. It's a bit more complicated than we would like unfortunately, but please try to deserialize the accountholder to [this model instead](https://github.com/Adyen/adyen-java-api-library/blob/e4afcbe545506af7849f994e980e8c13577058c3/src/main/java/com/adyen/model/configurationwebhooks/AccountHolder.java#L100). That should solve the enum issues.

We will try to provide more webhooks support in the future.

Kind Regards,
Wouter
Adyen

**Comment by Arnfinng** [comment]
We are experiencing the same problem. AccountHolderNotificationRequest.fromJson tries to deserialize to an AccountHolder (in the AccountHolderNotificationData), which fails as the status enum is no longer correct as the values we are actually getting are capitalized (e.g. "Active")

Cannot construct instance of `com.adyen.model.configurationwebhooks.AccountHolder$StatusEnum`, problem: Unexpected value 'Active'
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.adyen.model.configurationwebhooks.AccountHolder$StatusEnum`, problem: Unexpected value 'Active'
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 5, column: 17] (through reference chain: com.adyen.model.configurationwebhooks.AccountHolderNotificationRequest["data"]->com.adyen.model.configurationwebhooks.AccountHolderNotificationData["accountHolder"]->com.adyen.model.configurationwebhooks.AccountHolder["status"])

**Comment by vincenthartsteen** [comment]
> Hi @vincenthartsteen ,
> 
> Thanks for raising this issue. The Accountholder you are trying to parse should be part of the configuration notification models. It's a bit more complicated than we would like unfortunately, but please try to deserialize the accountholder to [this model instead](https://github.com/Adyen/adyen-java-api-library/blob/e4afcbe545506af7849f994e980e8c13577058c3/src/main/java/com/adyen/model/configurationwebhooks/AccountHolder.java#L100). That should solve the enum issues.
> 
> We will try to provide more webhooks support in the future.
> 
> Kind Regards, Wouter Adyen

Hi Wouter,

I'm afraid that doesn't work. The `AccountHolder` object from the configurationwebhooks package also has the `StatusEnum` where the values are lowercase. However the actual webhook that we receive has a value `Active`. This is an example from the test environment:

```
{"data":{"balancePlatform":"MontroPlatform","id":"AH3292Z223227P5L2ZVKZF3J8","accountHolder":{"description":"Ma1345","legalEntityId":"LE3294Q223225S5L2ZVKZ7FJJ","reference":"4002","capabilities":{"receiveFromBalanceAccount":{"enabled":"true","requested":"true","allowed":"true","verificationStatus":"valid"}},"id":"AH3292Z223227P5L2ZVKZF3J8","status":"Active"}},"environment":"test","type":"balancePlatform.accountHolder.updated"}
```

Here you see a `"status":"Active"` that can't be parsed by the `AccountHolder.fromJson()` because it expects `active`.

**Comment by jillingk** [comment]
Hi @vincenthartsteen and @Arnfinng,

Which webhook versions are you using? You can check this on the Balance Platform Customer Area. 

Best, Jilling
Adyen

**Comment by vincenthartsteen** [comment]
Hi Jilling,

For the Transfer webhook I see version 3. For the Report, Configuration and Balance webhooks I see version 1

Mvg,
Vincent Hartsteen

**Comment by jillingk** [comment]
Hi @vincenthartsteen,

Yes for the webhooks with multiple versions you should be able to change it. I found the similar issue we had a short while ago that might offer you some [more insight](https://github.com/Adyen/adyen-java-api-library/issues/1308). Let me know if you're able to sort it out.

Best, Jilling
Adyen

**Comment by vincenthartsteen** [comment]
Oh ok. That is a bit confusing. So the webhooks for the balance platform can also be edited from the “old” CA environment… And the version can only be changed on the “old” CA and not on the “balance” CA. I need a coffee :-)

Changed the version now and will test it.

Mvg,
Vincent Hartsteen

**Comment by vincenthartsteen** [comment]
Hi Jilling,

Yes I see that the response changed :-)

 Thanks for your assistance!

Mvg,
Vincent Hartsteen
