### ISSUE TITLE
I need a java 8 version supported sdk

### ISSUE THREAD

**Issue by TengLi233** [Adyen/adyen-java-api-library#1399]
**Java version**: 1.8

**Describe the solution you'd like**
I see this sdk only support java 11 or higher, but we need a java 8 version sdk. For my company, update java 8 to java 11 is a very difficult thing. Considering there are still a lot of java 8 system running, do you will support a java 8 verion sdk?

**Comment by vladislav-naydenov** [comment]
Reopening this issue  we're facing a similar problem. Which version of the SDK supports java 8?
