### ISSUE TITLE
Methods equals and hashCode are absent

### ISSUE THREAD

**Issue by githubmicrob** [Adyen/adyen-java-api-library#144]
**Java version**: 1.8.x
**Library version**: 1.7.0
**Description**
Please add methods equals and hashCode to class com.adyen.model.checkout.DefaultPaymentMethodDetails. It was convenient to verify correctness of request created by application logic in tests.

Thanks,
Alex

**Comment by AlexandrosMor** [comment]
Hello @githubmicrob,

We will pick up the issue soon and we will let you know when the library is released. 

kind regards,
Alexandros
Adyen

**Comment by rkewlani** [comment]
Hi Alex @githubmicrob,
We have added equals and hashcode methods in DefaultPaymentMethodDetails class:
https://github.com/Adyen/adyen-java-api-library/blob/master/src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java

Thanks,
Rajni
Adyen
