### ISSUE TITLE
Add Terminal API calls

### ISSUE THREAD

**Issue by xslim** [Adyen/adyen-java-api-library#145]
Please consider Terminal API communications to this library

**Comment by xslim** [comment]
This possibility was added to our .NET api library - https://github.com/Adyen/adyen-dotnet-api-library

I see a todo list as follow:
- [ ] Add `NexoCrypto` class here, so it can be versioned
- [ ] Ability to specify connection URL,  timeout, certificate trust on HTTP request
- [ ] methods / objects to start transaction and parse result
- [ ] parsing / encoding additional data
- [ ] parsing receipts

**Comment by AlexandrosMor** [comment]
Hello @xslim 

We added as an internal todo issue and we will pick it up soon. 

Kind regards,
Alexandros 
Adyen

**Comment by AlexandrosMor** [comment]
https://github.com/Adyen/adyen-java-api-library/pull/188
