### ISSUE TITLE
GetAccountHolderRequest is missing Boolean showDetails parameter

### ISSUE THREAD

**Issue by Haiperlink** [Adyen/adyen-java-api-library#146]
**Java version**: 1.8.0
**Library version**: 1.7.0
**Description**
The GetAccountHolderRequest.java in the MarketPay API should have a Boolean **showDetails** according to the API documentation.
https://docs.adyen.com/api-explorer/#/Account/v4/getAccountHolder

**Comment by Haiperlink** [comment]
If you are interested I've added a PR for this #147

**Comment by lancergr** [comment]
Hi @Haiperlink 

Thanks again for opening a PR for that. It is now merged.

Best Regards,
Giorgos
Adyen
