### ISSUE TITLE
Missing equals in ApplicationInfo

### ISSUE THREAD

**Issue by miklos-toth-olx** [Adyen/adyen-java-api-library#152]
**Library version**: 1.8.0
**Description**
- @AlexandrosMor ApplicationInfo doesn't override equals. Since it is called in AbstractPaymentRequest equals method, identical PaymentRequest3d objects return false for `equals` method.

**Comment by rkewlani** [comment]
Hi @miklos-toth-olx ,
Thanks for writing to us. 
We are working on this and will update the class as soon as possible.

Regards,
Rajni 
Adyen

**Comment by AlexandrosMor** [comment]
PR: [164](https://github.com/Adyen/adyen-java-api-library/pull/164)
