### ISSUE TITLE
SEPA direct debit

### ISSUE THREAD

**Issue by cleemansen** [Adyen/adyen-java-api-library#153]
**Java version**: 1.8.0_202
**Library version**: 1.7.0
**Description**

I need to make a **SEPA direct debit** [payment request](https://docs.adyen.com/developers/payment-methods/sepa-direct-debit#integratewithapi). 

- Is this possible w/ this library? I can not set this payment method in `com.adyen.model.PaymentRequest`.
- Is it possible to set the payment method and the required fields (like `sepa.ibanNumber`) in a generic way w/ this library?

Thanks for your advice.

**Comment by cleemansen** [comment]
Also consider to update your documentation at https://adyen.github.io/adyen-java-api-library/checkout-api.html

```
PaymentsRequest paymentsRequest = new PaymentsRequest();
// [..]
paymentsRequest.setPaymentMethod(new DefaultPaymentMethodDetails().number("4111111111111111").
                expiryMonth("10").expiryYear("2020").
                cvc("737").holderName("John Smith").type("scheme"));
```

This setter (`setPaymentMethod`) is IMHO not available anymore in this library?

**Comment by cleemansen** [comment]
Okay - after investing some time I think I got a first solution:

- Extend `PaymentMethodDetails` by a _SepaDirectDebitPaymentMethodDetails_ class w/ fields
    - `type` (= `"sepadirectdebit"`)
    - `sepa.ibanNumber`
    - `sepa.ownerName`
- use the checkout api (`com.adyen.model.checkout.PaymentsRequest#PaymentsRequest`) and set this extension as `paymentMethod`

Is this the correct way? A first test works for me.

**Comment by rkewlani** [comment]
Hi @cleemansen ,
Apologies for late reply. We are working on this and will keep you posted on this.
Thanks,
Rajni

**Comment by AlexandrosMor** [comment]
PR [170](https://github.com/Adyen/adyen-java-api-library/pull/170)
