### ISSUE TITLE
Enum value is missing for "Pending" result code 

### ISSUE THREAD

**Issue by amashtakov** [Adyen/adyen-java-api-library#154]
**Java version**: 1.8
**Library version**: 1.8.0
**Description**
As per Checkout API for v40 documentation  (https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/payments), possible values for /payments response  resultCode are:
* Authorised 
* Refused
* RedirectShopper 
* Received
* Cancelled
* Pending 
* Error 

In fact _com.adyen.model.checkout.PaymentsResponse.ResultCodeEnum_ is missing "Pending" and
has an extra value "PartiallyAuthorised" which is not documented

**Comment by AlexandrosMor** [comment]
Hell @amashtakov,

We will check the differences in resultCode and we will let you know as soon as possible

Kind regards,
Alexandros

**Comment by AlexandrosMor** [comment]
PR [164](https://github.com/Adyen/adyen-java-api-library/pull/164)
