### ISSUE TITLE
Possible NullPointerException on PaymentResultResponse & PaymentRequest

### ISSUE THREAD

**Issue by sanmibuh** [Adyen/adyen-java-api-library#157]
**Java version**: 1.8
**Library version**: 2.0.0
**Description**
**PaymentResultResponse** and **PaymentRequest** has a possible NullPointerException if we call to 
_putAdditionalDataItem_ or _putMetadataItem_ without calling first to _additionalData_ or _metadata_

**Comment by rkewlani** [comment]
Hi @sanmibuh,
Thanks for PR to fix this. We will merge and release this once review is done.

Thanks,
Rajni
