### ISSUE TITLE
Logger implementation not needed

### ISSUE THREAD

**Issue by sanmibuh** [Adyen/adyen-java-api-library#159]
**Java version**: 1.8.0
**Library version**: 2.0.0
**Description**
log4j:log4j:1.2.17 dependency is not used. Please remove it, because we are getting this dependency transitively if we don't exclude it.

**Comment by rkewlani** [comment]
Hi @sanmibuh,
Thanks for PR to fix this. We will merge and release this once review is done.

Thanks,
Rajni
