### ISSUE TITLE
[Feature request] : Possibly missing ENUM values in PaymentResult

### ISSUE THREAD

**Issue by c9pr3** [Adyen/adyen-java-api-library#163]
**Java version**: 1.8.0
**Library version**: 2.0.0
**Description**

For 3D Secure 2.0 with classic API as described in https://docs.adyen.com/developers/3d-secure-2-classic-integration/browser-based-integration, in com.adyen.model.PaymentResult are missing ENUMS for IdentifyShopper and ChallengeShopper. Currently, we are getting resultCode "NULL".

Request (shortened)
`final Payment payment = new Payment(getClient());`
`final PaymentResult result = payment.authorise(getPaymentRequest());`

Response JSON:
`{"additionalData":{"expiryDate":"8\/2018","threeds2.threeDSServerTransID":"XXXXXX","cardSummary":"1234","paymentMethod":"mc","threeds2.threeDS2Token":"XXXXXX","threeds2.threeDSMethodURL":"https:\/\/pal-test.adyen.com\/threeds2simulator\/acs\/startMethod.shtml"},"fraudResult":{"accountScore":61,"results":[…]},"pspReference":"XXXXXX","resultCode":"IdentifyShopper"}`

Response Java after GSON mapping:
`class PaymentResult {
    authCode: null
    paRequest: null
    issuerUrl: null
    md: null
    dccAmount: null
    dccSignature: null
    pspReference: XXXXXX
    resultCode: null
    additionalData: {expiryDate=8/2018, threeds2.threeDSServerTransID=XXXXXX cardSummary=1234, paymentMethod=mc, threeds2.threeDS2Token=XXXXXX, threeds2.threeDSMethodURL=https://pal-test.adyen.com/threeds2simulator/acs/startMethod.shtml}
    refusalReason: null
    fraudResult: class FraudResult {
   […]
        }]
    }
}`

**Comment by AlexandrosMor** [comment]
Hello @c9pr3,

We created an internal ticket to add 3ds2.0 support for classic API. Currently 3ds2.0 is implemented for checkout. We will keep you posted.

regards    
Alexandros Moraitis
Adyen
