### ISSUE TITLE
How to store the credit card on your end and how to configure the payouts service?

### ISSUE THREAD

**Issue by kexiaoyang** [Adyen/adyen-java-api-library#166]
How to store the credit card on your end and how to configure the payouts service?

**Comment by AlexandrosMor** [comment]
Hey @kexiaoyang 

About payouts you can find information to adyen's [api documentation](https://docs.adyen.com/api-explorer/#/Payout/v30/overview). Furthermore there are some payouts examples in [PayoutTest.java](https://github.com/Adyen/adyen-java-api-library/blob/develop/src/test/java/com/adyen/PayoutTest.java)   

In addition about store card details you can refer [store payment details](https://docs.adyen.com/developers/classic-integration/recurring-payments/store-payment-details)

I hope it helps 

Kind regards,
Alexandros Moraitis
Adyen
