### ISSUE TITLE
Response Error Codes missing

### ISSUE THREAD

**Issue by tenaz3** [Adyen/adyen-java-api-library#167]
**Java version**: 1.8
**Library version**: 1.6.0
**Description**
Where I can have the error codes from the responses, like on the documentation:
https://docs.adyen.com/developers/marketpay/marketpay-error-codes
or
https://docs.adyen.com/developers/point-of-sale/testing-pos-payments/test-acquirer-responses

**Comment by AlexandrosMor** [comment]
Hello @tenaz3,

The errror codes for market pay are provided in `ErrorFieldType` which is part of `ErrorFieldTypeContainer`. The container is part of the responses. For example in case that there is an error in the account holder update then you get the error in `UpdateAccountHolderResponse` and `getInvalidFields`

The error codes for the terminal api are included in the pos terminal response. Terminal api is not supported in adyen-java-api-library.
