### ISSUE TITLE
Status Pending missing in PaymentResultResponse.ResultCodeEnum

### ISSUE THREAD

**Issue by mksplg** [Adyen/adyen-java-api-library#178]
**Java version**: 1.8
**Library version**: 2.0.1
**Description**
Similar to https://github.com/Adyen/adyen-java-api-library/issues/154, the [checkout payment result API documentation](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v41/payments/result) indicates a possible status `Pending`.

The enum `PaymentResultResponse.ResultCodeEnum` is missing this value though it is already present in the apidoc.

It does have an additional status `PartiallyAuthorised`.

**Comment by AlexandrosMor** [comment]
Hello @mksplg 

Thank you for submitting this. We will investigate the ResultCodeEnum soon.

Regards,
Alexandros Moraitis,

**Comment by rkewlani** [comment]
Hi @mksplg,
Result code is added and merged in develop branch.
Thanks,
Rajni 
Adyen
