### ISSUE TITLE
Wrong data line in toString method

### ISSUE THREAD

**Issue by mpochwala** [Adyen/adyen-java-api-library#179]
toString method is misleading. It writes additionalData against applicationInfo details. See defect line below.

https://github.com/Adyen/adyen-java-api-library/blob/12581f963c0ed00b02005c9068141cb0289b0e67/src/main/java/com/adyen/model/modification/AbstractModificationRequest.java#L271

**Comment by AlexandrosMor** [comment]
Hello @mpochwala 

We are looking on this. We will update you as soon as we investigate it. 
Regards,
Alexandros Moraitis,

**Comment by AlexandrosMor** [comment]
Hello @mpochwala 
We merged that fix. Soon it will be in the next release
Regards,
Alexandros Moraitis,
