### ISSUE TITLE
Checkout channel literal not found

### ISSUE THREAD

**Issue by dfratte** [Adyen/adyen-java-api-library#184]
**Java version**: 10.0.2
**Library version**: 2.0.2
**Description**

In the API integration documentation (https://docs.adyen.com/developers/checkout/api-integration#step1getavailablepaymentmethods) the following Java code statement (second to last line in code block) gives a "Cannot resolve symbol" warning:

`paymentMethodsRequest.setChannel(CheckoutChannel.Web);`

I have replaced it with:

`paymentMethodsRequest.setChannel(PaymentMethodsRequest.ChannelEnum.WEB);`

Could this be an issue of deprecated documentation? Thanks!

**Comment by rkewlani** [comment]
Hi @dfratte ,
Thanks for writing to us. Yes, it is documentation issue and we will fix it ASAP. 

Thanks,
Rajni
Adyen

**Comment by rkewlani** [comment]
Hi @dfratte,
We have updated our documentation to fix this.
Regards,
Rajni
Adyen
