### ISSUE TITLE
Decimal places for BYR, GHC and MRO special currencies are not mentioned in the online documentation

### ISSUE THREAD

**Issue by int33h** [Adyen/adyen-java-api-library#192]
https://github.com/Adyen/adyen-java-api-library/blob/e3e0f486a74cb013c5c71baa6330db866ccc7976/src/main/java/com/adyen/Util/Util.java#L104

https://docs.adyen.com/development-resources/currency-codes/

Please update the library and/or documentation so that they are in sync

**Comment by rkewlani** [comment]
Hi @int33h ,
Thanks for your inputs. We have created internal ticket for this and will fix it ASAP.
Thanks,
Rajni
Adyen

**Comment by martinsrenato** [comment]
Hi @int33h !

We fix this issue and released it on version 2.5.0 of the library. Thanks for the input!

Regards,
Renato
Adyen
