### ISSUE TITLE
Missing recurringProcessingModel in classic PaymentRequest

### ISSUE THREAD

**Issue by jacobk** [Adyen/adyen-java-api-library#195]
https://github.com/Adyen/adyen-java-api-library/pull/189 updated RecurringProcessingModel enum but the `UnscheduledCardOnFile` is still missing in https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/model/PaymentRequest.java#L70-L85

According to support both APIs should support this value.

**Comment by rkewlani** [comment]
Thanks @jacobk ,
we have added missing value and will release it soon.
https://github.com/Adyen/adyen-java-api-library/issues/195
Thanks,
Rajni
Adyen
