### ISSUE TITLE
Missing ApplicationInfo setter in AbstractModificationRequest

### ISSUE THREAD

**Issue by amashtakov** [Adyen/adyen-java-api-library#202]
**Java version**: 1.8.0_144
**Library version**: 2.2.0
**Description**

After making the upgrade from version 2.0.1 to 2.2.0, I noticed that _AbstractModificationRequest_ is missing the method:

`
public T applicationInfo(ApplicationInfo applicationInfo)
`

Having such method (or simply a setter) would bring the following benefits:

1. No compatibility issues will occur during the API upgrade
2. Custom application info supplier could be used by integration

Thanks

**Comment by rkewlani** [comment]
@amashtakov ,
This is an intentional change and we have removed setters to restrict modifications to ApplicationInfo from outside code. 
Thanks,
Rajni
Adyen
