### ISSUE TITLE
Sample project

### ISSUE THREAD

**Issue by stokito** [Adyen/adyen-java-api-library#205]
Hi, thank you for the library but I also would be very thankful if you can add a sample project where we can try to use it.
I created the sample project myself https://github.com/stokito/adyen-java-sample
There is some examples how to Create Market Account Holder and some related staff.
Could you please add it to Adyen repository?

**Comment by rikterbeek** [comment]
HI @stokito,

We will look into this. I don't think it should be in this repo as this will be included by all merchants projects. What we do have is tests that already can be used as a guideline how to implement certain calls. What you can do is add those tests to this repo.

Regards,
Rik
Adyen
