### ISSUE TITLE
PaymentMethodDetails object includes deliveryAddress, billingAddress, and personalDetails attriutes

### ISSUE THREAD

**Issue by tddouglas** [Adyen/adyen-java-api-library#214]
**Library version**: 2.0.0
**Description**
In the DefaultPaymentMethodDetails.java file, deliveryAddress, billingAddress, and personalDetails are listed as attributes of the paymentMethod object. However, you can't make a /payments call with deliveryAddress or billingAddress nested inside of the paymentMethod object (they aren't parsed by Adyen). Additionally, I don't know what the personalDetails field is, but it is not mentioned anywhere in the documentation or in our API explorer.

**Comment by tddouglas** [comment]
https://github.com/Adyen/adyen-java-api-library/blob/74a3e82ad726b66246d950b67fed7ffbc72d0afd/src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java#L28

**Comment by martinsrenato** [comment]
Hi @jvalecillos !

You fix was included in the release version 2.5.0 of the library. Thanks for the input!

Regards,
Renato
Adyen
