### ISSUE TITLE
BrowserInfo is not being displayed whitin PaymentsRequest's toString method

### ISSUE THREAD

**Issue by afilardo** [Adyen/adyen-java-api-library#218]
**Java version**: 1.8.0
**Library version**: 2.4.1
**Description**

BrowserInfo is not being displayed whitin PaymentsRequest's toString method

**Comment by martinsrenato** [comment]
Hi @afilardo!

Thanks for the pull request. We will review it and include it on the next release.

Regards,
Renato
Adyen

**Comment by martinsrenato** [comment]
Hi @afilardo!

You fix was released on version 2.5.0 of the library. Thanks for the input!

Regards,
Renato
Adyen
