### ISSUE TITLE
Missing merchantName value

### ISSUE THREAD

**Issue by scopefragger** [Adyen/adyen-java-api-library#221]
**Java version**: 8
**Library version**: 2.4.1
**Description**

Hi Team;

It appears that the "merchantName" value is missing from the com.adyen.model / ThreeDS2RequestData object, as per the documentation 

https://docs.adyen.com/classic-integration/3d-secure/3d-secure-2-classic-integration/authentication-only-integration/#provide-acquirer-data

Is this intentional?

**Comment by martinsrenato** [comment]
Hi @scopefragger ,

You are right, we should have this field and it was not added on this library due to a mistake on our side.
We have created internal ticket for this and will fix it ASAP.

Thanks for the input,
Renato
Adyen
