### ISSUE TITLE
TypeError when oneClickPaymentMethods is empty

### ISSUE THREAD

**Issue by fbngrt** [Adyen/adyen-java-api-library#228]
**Java version**: 1.8
**Library version**: 2.4.1
**Description**
I am referring to support request #850193.

The class `PaymentMethodsResponse` has list attributes which are initialized using the value `null`.

https://github.com/Adyen/adyen-java-api-library/blob/c00bac56d72d43b1046c5bd038cb81febfa6334e/src/main/java/com/adyen/model/checkout/PaymentMethodsResponse.java#L36

This is a problem when the response does not contain i.e. `oneClickPaymentMethods`. When passing `PaymentMethodsResponse` to the frontend, more specifically to adyen.js, a TypeError is thrown.

```
adyen.js:4 Uncaught TypeError: Cannot read property 'filter' of null
    at Vc (adyen.js:4)
    at new e (adyen.js:4)
    at new e (adyen.js:4)
```

Please consider initializing list attributes with an empty list.

**Comment by martinsrenato** [comment]
Hi @fbngrt !

We try to avoid unnecessary creation of new objects on the library, so most of our methods will return null for fields when there's no data for it.
Furthermore, the library is also used in other cases where the frontend component is not involved, so we will analyse with the internal team who developers the component if there's a solution that doesn't need the change of the library for this specific integration problem.

I will update this issue as soon as we have a solution for it. 
Thanks for the input.

Regards,
Renato Martins
Adyen

**Comment by schube** [comment]
Same problem here, support request https://support.adyen.com/hc/requests/892292

**Comment by schube** [comment]
So, I am now on my PC and can type better. I faced the same problem and wrote to Adyen in https://support.adyen.com/hc/requests/892292
But I think this is more a JavaScript problem rather than a Java problem. The JavaScript client must handle NULL values correctly.

**Comment by yahyaharif** [comment]
A quick workaround would be to add this code snippet before your front-end business logic:

```
if (paymentMethodsResponse.oneClickPaymentMethods === null) {
    paymentMethodsResponse.oneClickPaymentMethods = [];
}
```

**Comment by martinsrenato** [comment]
Hi @schube and @yahyaharif ,

As mentioned before, this issue was forwarded to our frontend development team and they already fixed it on our components/drop-in solutions. 
I'm closing this issue, but feel free to open another ticket here for any other library questions.

Regards,
Renato
Adyen

**Comment by frangri** [comment]
Hi @martinsrenato,

I hit the same problem and I had to use @yahyaharif  workaround both on `oneClickPaymentMethods` and `storedPaymentMethods`.

It might not be fixed.
