### ISSUE TITLE
Drop-In paymentMethod constructor

### ISSUE THREAD

**Issue by tddouglas** [Adyen/adyen-java-api-library#230]
**Library version**: 2.5.0
**Description**
To better integrate with the drop-in solution, there should be a [DefaultPaymentMethodDetails constructor](https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java#L28) that take in the properly formatted paymentMethod object outputted as the state of the drop-in component. 
Currently, it seems like the merchant has to implement the logic of parsing the paymentMethod object and constructing a well-formatted  DefaultPaymentMethodDetails object. However, this logic seems generic across all drop-in integrations and should be included in the SDK by default.

**Comment by martinsrenato** [comment]
Hi @tddouglas!

Thanks for the input. This is an improvement that we already have tracked in an internal issue. 
We should start working on this soon and we will let you know when the library is released.

Regards,
Renato Martins
Adyen

**Comment by tddouglas** [comment]
Thanks Renato!
