### ISSUE TITLE
Composite types are not supported by PaymentsRequest.additionalData

### ISSUE THREAD

**Issue by amashtakov** [Adyen/adyen-java-api-library#231]
**Java version**: 1.8.0_44
**Library version**: 2.4.1
**Description**
Hi,

As per documentation for [Basket content fields](https://docs.adyen.com/api-reference/payments-api/paymentrequest/paymentrequest-additionaldata#basket-content-fields) each "riskdata.basket.item" is a container object which should be serialized to JSON.

The "additionalData" member of com.adyen.model.checkout.PaymentsRequest is defined as Map<String, String>. There is no way to pass the Object  to "additionalData" map value. The workaround is to serialize custom POJO to JSON string and then pass it as a map value to "additionalData".

It would be good to have the option to provide POJO as a value to "additionalData" (assuming POJO is properly annotated).

Thanks

**Comment by martinsrenato** [comment]
Hi @amashtakov!

Right now we have this field as Map<String, String> for better compatibility with the code on our internal platform. 

Your approach to send this data is right and should work just fine when sending a request. It can be sent as both nested data or flattened fields, like the following example:

`        
// For basket items, we support both flattened and nested format to be used by merchants
requestRiskData.put("riskdata.basket.item1.sku", "sku1");
requestRiskData.put("riskdata.basket.item1.productTitle", "product1");

// The object will be flattened before persisting to the database
requestRiskData.put("riskdata.basket.item2", "{ \"sku\": \"sku2\", \"productTitle\": \"product2\" }");
`

We will open an internal issue for our documentation team to add a better explanation on how to pass this data.

Thanks for your input!

Regards,
Renato Martins
Developer - Adyen
