### ISSUE TITLE
Add paymentMethod to PaymentResultResponse

### ISSUE THREAD

**Issue by poulhenriksen** [Adyen/adyen-java-api-library#235]
**Java version**: 11.0.1
**Library version**: 2.5.0
**Description**
Add 'paymentMethod' to 'src/main/java/com/adyen/model/checkout/PaymentResultResponse.java'

**Comment by martinsrenato** [comment]
Hi @poulhenriksen.
Indeed, this field is missing on our model. We will work to add it and release soon.
Thanks for the input.

Renato
Adyen

**Comment by martinsrenato** [comment]
Hi @poulhenriksen,
This field was added on [release 2.6.0 of the library](https://github.com/Adyen/adyen-java-api-library/pull/241).
Thanks again!

Renato
Adyen

**Comment by poulhenriksen** [comment]
Great. Thanks!
