### ISSUE TITLE
Device fingerprint

### ISSUE THREAD

**Issue by Zander1983** [Adyen/adyen-java-api-library#242]
**Java version**: 1.8
**Library version**: 2.0.0
**Description**

I want to send the device fingerprint with the PaymentRequest as shown here https://docs.adyen.com/risk-management/device-fingerprinting. 

But the library doesn't appear to support this. Is there any reason? will it support in the future?

**Comment by AlexandrosMor** [comment]
Hello @Zander1983,

I believe that you are talking about [this property](https://github.com/Adyen/adyen-java-api-library/blob/d460c89ef0f07068cd838a8a81e4ad7aaa367cbb/src/main/java/com/adyen/model/checkout/PaymentsRequest.java#L142). Would you like to check and let us know ?

Thank you in advance,
Alexandros Moraitis

**Comment by Zander1983** [comment]
@AlexandrosMor Im using this model for the request https://github.com/Adyen/adyen-java-api-library/blob/d460c89ef0f07068cd838a8a81e4ad7aaa367cbb/src/main/java/com/adyen/model/PaymentRequest.java. Is there a reason why it's not supported here?

**Comment by Zander1983** [comment]
@AlexandrosMor Actually i see the PaymentRequest models i use extends from a class that does have the fingerprint property. I'll close this issue.
