### ISSUE TITLE
Missing PaymentRequest attrs in toString method

### ISSUE THREAD

**Issue by afilardo** [Adyen/adyen-java-api-library#247]
**Java version**: 1.8.0_162
**Library version**: 2.6.1
**Description**

I just realized that in our logs there are not appearing our requests params
I think the bug could be introduced in this commit, when the super.toString() sentence was removed

https://github.com/Adyen/adyen-java-api-library/commit/16ed51dd35ebb4908420266270e1e15f54190813#diff-6a97b0609fd25935f8dc3b1d305771b4L347

Now, the only logs we have are these:

> {
    accountInfo: null
    bankAccount: null
    card: null
    merchantRiskIndicator: null
    mpiData: null
    recurringProcessingModel: null
    splits: null
    store: null
    trustedShopper: null
    threeDS2RequestData: null
}

**Comment by martinsrenato** [comment]
Hi @afilardo !

Thanks for your input.
As you mentioned, the calls to the super methods were removed on a previous commit by mistake.
I reverted that (check #249) and the fix will be included on the next release.

Regards,
Renato
Adyen
