### ISSUE TITLE
3DS1 Payments do not trigger a redirect on the front-end even though the action type is "REDIRECT"

### ISSUE THREAD

**Issue by yahyaharif** [Adyen/adyen-java-api-library#248]
**Java version**: 1.8.0_221
**Library version**: 2.6.0
**SDK**: 3.0.0
**Integration**: Drop-in

**Description**: Adyen Java API sets the value of the action when trying to process 3DS1 payments to "REDIRECT" whereas the Adyen SDK expects "redirect" (case sensitive) and therefore causes a front-end error thus no redirection happens.

**Comment by martinsrenato** [comment]
Hi @yahyaharif !

Are you using any specific serialiser to pass the message from the library to the Drop-In?
The library uses GSON by default and already is annotated to use an Adapter class that serialises to the expected lowercased value.
(check https://github.com/Adyen/adyen-java-api-library/blob/9b7ab7e17cfb2960bf06d97524e4df72ee42e301/src/main/java/com/adyen/model/checkout/CheckoutPaymentsAction.java#L35)

Cheers,
Renato
Adyen
