### ISSUE TITLE
No ACH Direct debit support for the payments api

### ISSUE THREAD

**Issue by nicomancer** [Adyen/adyen-java-api-library#251]
**Java version**: 1.8
**Library version**: 2.6.1
**Description**
Payment method object in payment request does not contains fields for bank account, from official reference it should have fields like this:

"paymentMethod":{
--
  | "type":"ach",
  | "bankAccount":{
  | "bankAccountNumber":"1234567890",
  | "bankLocationId":"121000358",
  | "countryCode":"US",
  | "ownerName":"John Smith"
  | }

  | },

**Comment by martinsrenato** [comment]
Hi @nicomancer ,

Thanks for reaching out.
We are currently revising the PaymentMethod object and should come with a better implementation of it in one of the future releases.
Meanwhile, as paymentMethod details can be very different for each specific payment method, we currently provide a interface you need to adopt. This can be done in the following way:

```
PaymentMethodDetailsACH paymentMethodDetailsACH = new PaymentMethodDetailsACH();
paymentMethodDetailsACH.setType("ach");
BankAccount bankAccount = new BankAccount();
bankAccount.setBankAccountNumber("1234567890");
bankAccount.setBankLocationId("121000358");
bankAccount.setCountryCode("US");
bankAccount.setOwnerName("John Smith");
paymentMethodDetailsACH.setBankAccount(bankAccount);

class PaymentMethodDetailsACH implements PaymentMethodDetails {

    @SerializedName("type")
    private String type;

    @Override
    public String getType() {
        return type;
    }

    @Override
    public void setType(String type) {
        this.type = type;
    }

    @SerializedName("bankAccount")
    private BankAccount bankAccount;

    public BankAccount getBankAccount() {
        return bankAccount;
    }

    public void setBankAccount(BankAccount bankAccount) {
        this.bankAccount = bankAccount;
    }
}
```
The BankAccount class is already part of our library.

Regards,
Renato
Adyen
