### ISSUE TITLE
"idealIssuer" instead of "issuer"

### ISSUE THREAD

**Issue by bryancresswell** [Adyen/adyen-java-api-library#255]
https://github.com/Adyen/adyen-java-api-library/blob/1feb46dfbf35745a4981328f59e46a4b7059cb55/src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java#L57

This line here shows that the DefaultPaymentMethodDetails class is still on "idealIssuer" instead of "issuer". Could this be changed such that it can support more payment methods such as EPS?

**Comment by martinsrenato** [comment]
Hi @bryancresswell ,

Thanks for the input. We added the "issuer" field and deprecated the other one.
This change was released with [version 2.7.1](https://github.com/Adyen/adyen-java-api-library/releases/tag/2.7.1).

Cheers,
Renato
Adyen
