### ISSUE TITLE
No value “A” for DirectoryResponseEnum

### ISSUE THREAD

**Issue by luiseugeniopacheco** [Adyen/adyen-java-api-library#262]
**Java version**: 1.8
**Library version**: 2.7.0
**Description**

**Comment by martinsrenato** [comment]
Hi @luiseugeniopacheco !

Thanks for raising this issue.
We checked and indeed this enum is missing some of its possible values.
I created a PR #267 to fix that, adding the missing values according to the possible one listed on [our docs page](https://docs.adyen.com/classic-integration/3d-secure/raw-3d-secure-responses).
Our team will review it and we will include it on the next release after it's merged.

Cheers,
Renato
Adyen
