### ISSUE TITLE
DefaultPaymentMethodDetails.setApplepayToken method missing

### ISSUE THREAD

**Issue by alansegar-hb** [Adyen/adyen-java-api-library#265]
**Java version**: 11.0.4.11
**Library version**: 2.7.1
**Description**
https://docs.adyen.com/payment-methods/apple-pay/web-component#apple-pay-api uses a method `setApplepayToken` but I can't find that method on `com.adyen.model.checkout.DefaultPaymentMethodDetails` 

This is the line in the example:
`paymentMethodDetails.setApplepayToken("QWIwMmI0YzAhQlFBQkFnQjMv..");`

**Comment by martinsrenato** [comment]
Hi @alansegar-hb !

Thanks for raising this issue.
We just released a fix for that on [version 2.7.2](https://github.com/Adyen/adyen-java-api-library/releases/tag/2.7.2), could you check that?
If you find any other problem, feel free to open a new issue so we can check.

Cheers,
Renato
Adyen
