### ISSUE TITLE
Adyen Authorise Endpoint throwing 401 Unauthorized Error

### ISSUE THREAD

**Issue by qburst-reneesh** [Adyen/adyen-java-api-library#271]
Hello Team,

I have started integration my E-commerce back end service with Adyen as Payment service provider. But however when I tried to invoke _/authorise_ endpoint, I am getting 401 Unauthorized error

AdyenAPI-URL : https://pal-test.adyen.com/pal/servlet/Payment/v30/authorise
AdyenAPI Response Status: 401 Unauthorized

Adyen userId, password are passing as Basic Authentication headers for Authorization.
I have supplied the appropriate MerchantAccount as well in request payload.

Can you please advise whether I am missing any necessary items to be included in the Adyen configurations.

**Comment by martinsrenato** [comment]
Hi @qburst-reneesh !

Thanks for reaching out.
This usually means there is some issue with your account configuration or authentication keys. I would advise you to reach out to our support team via support@adyen.com, so they can investigate why your account is not able to process payments and change any configuration on it if needed.

Cheers,
Renato
Java Developer - Adyen

**Comment by qburst-reneesh** [comment]
Thanks @martinsrenato

**Comment by qburst-reneesh** [comment]
**Update for reference**

Problem was with my Adyen account password, I have generated new password using the Adyen back office application. However I haven't saved the generate password option, which is why I was getting unauthorised error when I tried to invoke its API.

![Screenshot from 2020-01-24 14-13-16](https://user-images.githubusercontent.com/56542690/73055854-b54cd180-3eb3-11ea-844f-4288a13d1d00.png)

**Comment by horisur** [comment]
HTTP URL is working in Adyen payment getaway?
