### ISSUE TITLE
Remove cards with SDK

### ISSUE THREAD

**Issue by hareen-yadlapalli** [Adyen/adyen-java-api-library#274]
Is it possible to remove credit/debit cards using Java SDK?

Could find an API to disable the cards, but not a Java SDK
https://docs.adyen.com/checkout/tokenization/managing-tokens

Regards,
Hareen

**Comment by martinsrenato** [comment]
Hi @hareen-yadlapalli !

Thanks for reaching out.
The library already contains an implementation of the /disable API. You can use it through the [`Recurring` service class, calling the `disable` method](https://github.com/Adyen/adyen-java-api-library/blob/179b85b092a1976a35da4e4f3e122e5a24fdd0a8/src/main/java/com/adyen/service/Recurring.java#L77  ).

Regards,
Renato
Adyen
