### ISSUE TITLE
API Idempotency transient errors HTTP header

### ISSUE THREAD

**Issue by alansegar-hb** [Adyen/adyen-java-api-library#284]
**Java version**: jdk-11.0.4.11
**Library version**: 2.7.2
**Description**
When implementing retries for payment requests using the Java library as follows:

        RequestOptions requestOptions = new RequestOptions();
        requestOptions.setIdempotencyKey(uuid.toString());
        log.info("Calling Adyen with Idempotency-Key uuid {}", uuid.toString());
        PaymentsResponse paymentsResponse = checkout.payments(paymentsRequest, requestOptions);

https://docs.adyen.com/development-resources/api-idempotency#transient-errors
describes the following:

> HTTP header Transient-Error with the value true, which indicates that the request can be retried at a later time using the same idempotency key. If the API does not return a transient error header, or returns a header with a value of false, do not retry the request.

Is there a way to access this Transient-Error header / boolean value in the Java library? 
I've had a look in `PaymentsResponse`, `ServiceError` and `ApiException` but can't find it.

`HTTPClientException` has a `getResponseHeaders` method which may give access to this information, but I don't have access to that type of exception in the checkout.payments call.

Internally that calls Resource.request which has the following catch:
```
} catch (HTTPClientException e) {
    responseBody = e.getResponseBody();
    apiException = new ApiException(e.getMessage(), e.getCode());
}
```
so the `ApiException` that I get back doesn't allow me to get to the  headers.

**Comment by AlexandrosMor** [comment]
Hello @alansegar-hb,

Thank you for raising this issue. We are going to investigate it and come back to you as soon as possible.

kind regards,
Alexandros
Adyen
