### ISSUE TITLE
[PW-2080] Missing notification codes

### ISSUE THREAD

**Issue by YouriT** [Adyen/adyen-java-api-library#307]
**Java version**: 8
**Library version**: 3.0.0

**Is your feature request related to a problem? Please describe.**
Missing notification event codes

**Describe the solution you'd like**
Add missing event codes to Java lib: https://docs.adyen.com/development-resources/notifications/understand-notifications

**Describe alternatives you've considered**
As it's a string, we do a string compare rather than `NotificationRequestItem.EVENT_NAME`

**Additional context**
N/A

**Comment by SprdNils** [comment]
We also miss the chargeback event code.

**Comment by AlexandrosMor** [comment]
Hello @YouriT,

We created an internal ticket to update the notification event codes for the adyen-java-api-library. Furthermore, feel free also to create a pull request with the codes and unit test which we can review it and include in one of the coming releases.  

kind regards,
Alexandros

**Comment by Aleffio** [comment]
Hi @YouriT closing this issue since the fix was merged in the 6.0.0 release.

Regards,
Alessio
Adyen
