### ISSUE TITLE
Unable to set storedPaymentMethodId

### ISSUE THREAD

**Issue by pakit84** [Adyen/adyen-java-api-library#310]
**Describe the bug**
Unable to set storedPaymentMethodId

Hello,
I am developing th possibility to pay with a stored credit card.
I am almost at the end.

card is correctly stored

I am able to retrieve the stored card as payment method

The issue is on the last step, I do not know how to pass to the /payments request the storedPaymentMethodId I get from state.data.paymentMethod from the onSubmit event.

As java client I am using adyen-java-api-library 2.7.3 (I also updated to the latest version : 4.1.0).
I don't see any exposed method to set int the PaymentsRequest object the storedPaymentMethodId.

Could you please help?

Thank you in advance

**Comment by andrei-dediu** [comment]
Hey Pakit,

There's already a storedPaymentMethodId property in the DefaultPaymentMethodDetails class that you can use. 
If this does not help, could we get a code snippet of the flow you are writing to better understand the problem ?

Regards,
Andrei.

**Comment by andrei-dediu** [comment]
Hey @pakit84 

We will close this issue down since we haven't heard from you in the past 30 days. Please re-open this issue if it there's still a problem.

Regards,
Andrei.
