### ISSUE TITLE
Auto-Usage of "global" merchant account

### ISSUE THREAD

**Issue by Deroin** [Adyen/adyen-java-api-library#315]
**Java version**: 8
**Library version**: 4.1.0

**Is your feature request related to a problem? Please describe.**
We just started using this library and immediately I noticed that one can set the merchant account on `Client` object (or rather it's `Config`), but that merchant account setting is hardly used anywhere so that it has to be passed to all places where requests are generated.

**Describe the solution you'd like**
I'd change the code so that if no merchant account is set on a request that requires one, but the client config has one set, the one from client config is automatically added to the request.

I can also do this change myself, just wanted to consult with code owners first if this is something you would accept as a change or if you designed it to be like it is on purpose.

**Comment by rkewlani** [comment]
Hi @Deroin,
It is very good point but we have kept it intentionally like it to force user to provide merchant account explicitly while submitting the payments request. Reason behind it is a user can be configured for multiple merchants and may end up in submitting payments to wrong merchant in case of ignorance of config object properties.
I hope it answers your question.

Thanks,
Adyen
