### ISSUE TITLE
Improve NotificationRequest

### ISSUE THREAD

**Issue by smic1909** [Adyen/adyen-java-api-library#325]
**Java version**: 1.7
**Library version**: 5.0.0

**Is your feature request related to a problem? Please describe.**
It is not related to a problem but more an improvement.

**Describe the solution you'd like**
The `NotificationRequest` returns a List of `NotificationRequestItemContainer`. To what I know, a webhook is sent always singular, not in a batch. This is why the class `NotificationRequest` could be simplified and return just the `NotificationRequestItem` to avoid iterating through a list with a max size of 1 from client perspective.

**Describe alternatives you've considered**
No alternatives available.

**Additional context**

**Comment by martinsrenato** [comment]
Hi @smic1909 ,

Thanks for the input.
The NotificationRequest class is structured like that to exactly reflect the json object that the notification webhooks provide. You can check one example of that on [Adyen documentation page](https://docs.adyen.com/development-resources/notifications/understand-notifications#749220549). Notice how the response is always a list with the NotificationRequestItem item always wrapped in another object.
There is room for improvement there and we really appreciate your opinion, we will take that in consideration when developing further changes on our internal platform and be sure that if the webhook responses change, this will also be reflected on this library.
