### ISSUE TITLE
Missing value in enum PaymentResult.ResultCodeEnum

### ISSUE THREAD

**Issue by zixuan-eb** [Adyen/adyen-java-api-library#327]
- Java Version: 1.8
 - Library Version:5.0.0

Similar to #154 and #178 .
Referring to the doc(https://docs.adyen.com/api-explorer/#/Payment/v52/authorise__resParam_resultCode)
'Pending' is missing in the enum com.adyen.model.PaymentResult.ResultCodeEnum but there is a 'PartiallyAuthorised'.

**Comment by martinsrenato** [comment]
Hi @zixuan-eb ,

Thank you for submitting this issue. 
Indeed this ResultCode was missing, so I created a small PR to fix that. It will be reviewed and included on the next release of the library.

Regards,
Renato
Adyen
