### ISSUE TITLE
Java 8+ Support

### ISSUE THREAD

**Issue by smic1909** [Adyen/adyen-java-api-library#329]
**Java version**: 1.7
**Library version**: 5.0.0

**Is your feature request related to a problem? Please describe.**
No, my request is not related to a problem.

**Describe the solution you'd like**
Upgrade to Java version 1.8+

**Describe alternatives you've considered**
No alternatives available

**Additional context**
Hi there, is there a reason why your library still stick to Java version 7? Switching to Java version 8 or later will give you a lot of advantages as you probably know. If you need support, I am happy to create a first PR.

**Comment by rikterbeek** [comment]
Hi @smic1909,

Thanks for raising this issue. I think indeed a very relevant question if we still need to support Java7. Looking through it it indeed does not make a lot of sense anymore to support this as it it out of support for the public. Looking to other software libraries the java 8 version seems to be the minimum version now a days. We will look into this a bit more but don't see any issues move the minimum version to Java8.

Regards,
Rik
Adyen
