### ISSUE TITLE
[PW-2346] missing "brand" field in DefaultPaymentMethodDetails

### ISSUE THREAD

**Issue by xiaojun-zhang** [Adyen/adyen-java-api-library#338]
**Describe the bug**
I'm trying to follow this [doc](https://docs.adyen.com/checkout/network-tokenization#existing-network-tokens), but there is no way to set paymentMethod.brand. 

**How to reproduce**
N/A

**Expected behavior**
should have a field to set paymentMethod.brand

**Desktop (please complete the following information):**
 - Java Version: [11.0.2]
 - Library Version: [5.0.0]

**Additional context**

**Comment by andrei-dediu** [comment]
Hello Xiaojun,

I checked and indeed it seems we are not supporting all the fields from the network tokenization feature. I have opened an issue on our internal systems to pick up and be fixed by us.

Regards,
Andrei.
