### ISSUE TITLE
[PW-2415] Enums in models POJOs does not work with Jackson

### ISSUE THREAD

**Issue by deepu105** [Adyen/adyen-java-api-library#340]
**Describe the bug**
When using Jackson to serialize the POJOs the enums get the toString rather than value, this makes the POJOs unusable directly and requires a bridging DTO that just remaps with Jackson annotations

**How to reproduce**
Try to use the POJO with a webapp that uses Jackson as the serializer, for example, any spring applications

**Expected behavior**
POJOs should be technology agnostic

**Desktop (please complete the following information):**
 - Java Version: 11
 - Library Version: 5.0.0

**Comment by deepu105** [comment]
I would recommend also adding the Jackson annotations to the POJO as Jackson is more popular the Gson anyway. The annotations can coexist without any issues

see https://stackoverflow.com/questions/32958521/can-gson-and-jackson-annotations-coexist-in-the-same-pojo

**Comment by andrei-dediu** [comment]
Hey @deepu105 

Thanks for opening the issue and the additional suggestion. I have looked at our Java API Library code and indeed and there are some enums with different values from their name. I created a ticket to adjust the serializing and deserializing process by either seeing if we can further customise the process with Gson or by implementing the Jackson annotations.

Regards,
Andrei.

**Comment by saquibsayyad** [comment]
Jackson annotations has been added in the POJO's, will be available in the next release.
