### ISSUE TITLE
Error in checkout to make payments

### ISSUE THREAD

**Issue by Acronus2008** [Adyen/adyen-java-api-library#344]
**Error in checkout to make payments**
when i make a call to **payments** method of **Checkout** class a got an error indicating that no exist a default constructor for the PaymentMethodDetails. This is a problem exist in the version 5, and now when i review the version 6 a got the same error, 

org.springframework.core.codec.CodecException: Type definition error: [simple type, class com.adyen.model.checkout.PaymentMethodDetails]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.adyen.model.checkout.PaymentMethodDetails` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 7, column: 20] (through reference chain: com.adyen.model.checkout.PaymentsRequest["paymentMethod"])

**How to reproduce**
Try to make a payment using the payment method from Checkout class.

**Expected behavior**
Execute a payment when make a request to payment method from Checkout class and receive the response status of the payment transaction

**Screenshots**
[Screen in my Google Drive](https://drive.google.com/file/d/1d6a5dDlqK4ETB2pBmgiebFoZQKKesTuo/view?usp=sharing)

**Desktop (please complete the following information):**
 - Java Version: java 11
 - Library Version: 5.0.0 and 6.1.0

**Additional context**
I use this example of json to execute the payment.
{
  "amount": {
    "currency": "USD",
    "value": 1000
  },
  "reference": "001",
  "paymentMethod": {
    "type": "scheme",
    "encryptedCardNumber": "encryptedCardNumber...",
    "encryptedExpiryMonth": "encryptedExpiryMonth...",
    "encryptedExpiryYear": "encryptedExpiryYear...",
    "encryptedSecurityCode": "encryptedSecurityCode....",
    "holderName": "a holder name"
  },
  "billingAddress": {
       "street": "Infinite Loop",
       "houseNumberOrName": "1",
       "postalCode": "95014",
       "city": "Cupertino",
       "stateOrProvince": "CA",
       "country": "US"
  },
  "returnUrl": "https://your-company.com/checkout?shopperOrder=12xy..",
  "merchantAccount": "DofleiniECOM"
}

**Comment by andrei-dediu** [comment]
Hey @Acronus2008 

Not entirely clear on how you are using the PaymentMethodDetails. That's an interface that requires an implementation. It is there to offer the possibility of creating your own Payment Method in the case we do not support it yet. You can use the DefaultPaymentMethodDetails if you want, as it supports most of the available payment methods.

So if you made your own implementation of PaymentMethodDetails and getting that exception, then we can not help with that as it is not directly related to our library. If that's not the case and you're still facing this issue, please provide us some code samples that we can go through.

Regards,
Andrei.

**Comment by andrei-dediu** [comment]
Hey @Acronus2008,

Since we have not heard back from you, I'm assuming this is not an issue no longer and will close the issue.

Regards,
Andrei.

**Comment by missbond2017** [comment]
@Acronus2008 
Hey buddy, U should create your own class, if U use the java api.

@andrei-dediu 
Hey, you should change the com.adyen.model.checkout.PaymentsRequest class  data structure, tks.

**Comment by andrei-dediu** [comment]
Hey @missbond2017 

This issue has been closed and marked as resolved, if you have any feedback or improvements feel free to open a new ticket or submit your own changes for review.

Regards,
Andrei.
