### ISSUE TITLE
refusalReasonCode is 0 for failed 3d-secure transactions

### ISSUE THREAD

**Issue by smic1909** [Adyen/adyen-java-api-library#345]
**Describe the bug**
In case the 3d-secure authentication failed, a `refusalReasonCode` `0` is set.

**How to reproduce**
Create a 3DS transaction, for example bcmc, and fail during the authentication phase. Log the response as `toString`(see *Screenshot* section)

**Expected behavior**
The field `refusalReasonCode` should have either a documented errorCode or should have the value `"null"`. The former is preferred.

**Screenshots**
A `toString` output of the `PaymentsResponse` class for a failed 3d-secure authentication
![image](https://user-images.githubusercontent.com/7910919/81412545-4df61d00-9144-11ea-86ec-9a1121bc63e5.png)

**Desktop (please complete the following information):**
 - Java Version: 8
 - Library Version: 4.1.0

**Additional context**
It is not expected to have a `0` value in a `String` field. Either it should be `"null"` as String [1] or a proper value is set. Looks like the `refusalReasonCode` is a `int` value in another internal system.

[1] https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/model/checkout/PaymentsResponse.java#L444

**Comment by andrei-dediu** [comment]
Hey @smic1909 

The refusalReasonCode is generated from the refusalReason internally. Meaning that the refusal reason is taken and mapped to a code. In the case there's no match for the refusal reason, then the string "0" will be outputted. 
Internally this parameter is also a string, so we just aligned with it.
So there's an issue with this but it is internal and not related to the library itself, I will follow up on our side.

**Comment by andrei-dediu** [comment]
Hey @smic1909 

I can confirm that this is the intended behavior for the refualReasonCode.

Regards,
Andrei.
