### ISSUE TITLE
ApiException thrown on bad request does not contain invalid field info

### ISSUE THREAD

**Issue by fx90** [Adyen/adyen-java-api-library#346]
**Describe the bug**

When you send a request with an invalid field to the API, the response contains a list of invalid fields (see e.g. https://docs.adyen.com/api-explorer/#/Account/v5/post/updateAccountHolder). However, when sending the request via the java api library, the ApiException that is thrown does not include this information. Since there is also no useful error message, it is not possible to find out from the exception why the request failed.

**How to reproduce**

Update an account holder using https://docs.adyen.com/api-explorer/#/Account/v5/post/updateAccountHolder, and e.g. include a number in the last name to make it a bad request. It will throw an ApiException like this:

ApiException{error=class ApiError {
    status: 0
    errorCode: null
    message: null
    errorType: null
    pspReference: 8815893616598667
}, statusCode=400, message=HTTP Exception, responseHeaders={Transfer-Encoding=[chunked], null=[HTTP/1.1 400 Bad Request], Server=[Apache], Connection=[close], Set-Cookie=[...], pspReference=[8815893616598667], Date=[Wed, 13 May 2020 09:20:59 GMT], Content-Type=[application/json;charset=UTF-8]}}

**Expected behavior**
An exception including the information what went wrong, e.g. by including the "invalid fields" list from the api response.

**Desktop (please complete the following information):**
 - Java Version: openjdk 11.0.2 
 - Library Version: 6.0.0

**Comment by martinsrenato** [comment]
Hi @fx90 ,

Thanks for raising this issue.
Indeed, the raised exception currently does not include the `invalid fields` list returned by the API.
I will create an internal ticket for our team to check what is the best approach on including this information on the error response. We'll try to analyse that as soon as possible and I'll return you here when we have a solution for that.

Regards,
Renato
Adyen

**Comment by fx90** [comment]
It's fixed now with the release of the linked ticket in 7.0.1. Thanks!
