### ISSUE TITLE
Release to the Maven central repository

### ISSUE THREAD

**Issue by jaspervanveghel** [Adyen/adyen-java-api-library#36]
Hey there :) We would like to use this dependency in a project; but I see that there is no release in the central repository. Would you mind releasing it?

See: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by rikterbeek** [comment]
Hi @jaspervanveghelm,

Correct, I did the request just now thanks for letting us know.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @jaspervanveghel,

It should now be on the maven central repository. 

`<dependency>
  <groupId>com.adyen</groupId>
  <artifactId>adyen-java-api-library</artifactId>
  <version>1.1.0</version>
</dependency>`

Can you check if this works for you ?

Regards,
Rik
Adyen

**Comment by lancergr** [comment]
Closing this as 1.1.0 was published
https://repo.maven.apache.org/maven2/com/adyen/adyen-java-api-library/1.1.0/
