### ISSUE TITLE
Missing documentation for Terminal API

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-java-api-library#364]
I am following the documentation for a local Terminal integration and I'd like to use this lib to do the job of serialization, security, etc. as suggested. Unfortunately I can't find any documentation or examples on how to use this part of the lib.

**Comment by nickcaballero-mm** [comment]
Would be interested in this as well. We had to write our own Nexo model representations from the Nexo specifications to figure out how to talk to the terminals.

**Comment by rikterbeek** [comment]
Hi @jnorkus,

I agree this we can better provide it into our documentation. We are working with our documentation team to improve this.
In the mean while we have some documentation on the libraries already available.

Install the library see documentation here:
https://docs.adyen.com/point-of-sale/choose-your-architecture/local#install-library

Creating a payment request see an java example here:
https://docs.adyen.com/point-of-sale/make-a-payment?tab=%23codeBlockWaC83_Java#make-a-payment-request

Check as well some of our test cases here:
https://github.com/Adyen/adyen-java-api-library/blob/develop/src/test/java/com/adyen/TerminalLocalAPITest.java

Regards,
Rik
Adyen
