### ISSUE TITLE
[PW-2681] Add http response headers to PaymentResponse and ModificationResult

### ISSUE THREAD

**Issue by MikhailShumenko** [Adyen/adyen-java-api-library#365]
**Describe the bug**
We are going to integrate with Adyen idempotent payment solution: https://docs.adyen.com/development-resources/api-idempotency?tab=%23codeBlockIp5yV_bash#enable-idempotency

> To verify that a request was processed idempotently, check the Idempotency-Key HTTP header returned in the response.

As described in docs we can verify that a request was processed idempotently by checking response headers, but there is no ability to get response headers from com.adyen.model.checkout.PaymentsResponse.

**Expected behavior**
Cloud you please add response headers to the PaymentsResponse, as you do for https://github.com/Adyen/adyen-java-api-library/pull/288/files#diff-95b172d74ebd7d1c534673475eb29d37R37

**Comment by Aleffio** [comment]
Hi @MikhailShumenko ,

Thank you for reporting the issue, 
I added an internal ticket to work on the headers.

Regards,
Alessio
Adyen

**Comment by viatra2** [comment]
@Aleffio Any updates on this? Could you advise some workaround on how to identify duplicated headers?

**Comment by jillingk** [comment]
Closing this ticket as the issue has been solved.
