### ISSUE TITLE
ApplePay/GooglePay payment method deserialization problem

### ISSUE THREAD

**Issue by bkij** [Adyen/adyen-java-api-library#377]
**Java version**: 11.0.7
**Library version**: 8.0.0

Hello,

I'm using Adyen mobile components on the frontend and java library on the backend for payment processing and there seems to be a problem with JSON deserialization to PaymentMethodDetails subclasses in some cases. One part of the payment request from the mobile component is the paymentMethod object, which in case of apple pay has a field `applepay.token`, and for google pay `paywithgoogle.token`. However, the POJOs representing those payment methods have differently named fields:
ApplePayDetails:
```
@SerializedName("applePayToken")
private String applePayToken = null;
```
GooglePayDetails:
```
@SerializedName("googlePayToken")
private String googlePayToken = null;
```
and so deserialization fails.

Now, to be honest, I'm not 100% sure that it's a bug, as the upstream adyen API seems to accept both `applepay.token` and `applePayToken`, however I was unable to find more information about the different payment method objects shapes in the API documentation; the iOS components documentation page shows an example request with a `applepay.token` field. I've tested this with iOS (but I assume that google pay deserialization will fail similiarly), using Adyen 3.5.0 version pods.

**Comment by Aleffio** [comment]
Hi @bkij ,

thank you for reporting the issue, we are aware of the deserialization issue, also with drop-in please see #369 .
We will work on a fix.

Kind Regards,
Alessio
Adyen

**Comment by Aleffio** [comment]
Hi @bkij,

You can now use the new ApplePayDetails and GooglePayDetails classes for your case, the deserialization should now work correctly with gson/jackson.

regards,
Alessio
Adyen
