### ISSUE TITLE
Does not work with older apache common library

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-java-api-library#382]
I am trying to use the API lib on Android. Some other libs (in my case Google Maps SDK) depend on legacy apache http client as described [here](https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library).

This causes a runtime error for methods `encodeBase64String` and `decodeBase64`:
```
No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
```

This is because the older libs only support `encodeBase64` and `decodeBase64` with `byte[]` as input (as opposed to a `String`, which is currently used).

Passing `byte[]` instead of a `String` covers my case. I can submit a PR if this solution would be accepted.

**Comment by Aleffio** [comment]
Hi @jnorkus ,

There shouldn't be any problems by passing byte[], can you please submit a PR?

Thanks,
Alessio
Adyen

**Comment by Aleffio** [comment]
Closing this issue since it is now included in the latest release,
thank you for the contribution.

Regards,
Alessio
Adyen
