### ISSUE TITLE
Android - java.security.KeyStoreException: JKS not found

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-java-api-library#383]
When used on Android with SSL, lib throws the exception in title.

On my fork instead of `KeyStore.getInstance("JKS")` I use `KeyStore.getDefaultType()`.

I would be happy to submit a PR if this solution is accepted.

**Comment by Aleffio** [comment]
Hi @jnorkus ,

sorry for the late reply and thank you for opening the issue,
can you please open a PR to solve this issue?

thanks,
Alessio
Adyen

**Comment by Aleffio** [comment]
Closing this issue since it is now included in the latest release,
thank you for the contribution.

Regards,
Alessio
Adyen
