### ISSUE TITLE
Make use of Lombok?

### ISSUE THREAD

**Issue by smic1909** [Adyen/adyen-java-api-library#386]
**Java version**: All
**Library version**: All

**Is your feature request related to a problem? Please describe.**
Many projects make use of [Project Lombok](https://projectlombok.org/). I am wondering if there are reasons against using Lombok in this lib. If there are no reasons, I am happy to support here in order to make the code more readable.

**Describe the solution you'd like**
Start introducing Lombok with getter and setter in the first PR. Following PRs could contain more functionality of Lombok.

**Describe alternatives you've considered**
Keep code as is.

**Additional context**
No additional context.

**Comment by andrei-dediu** [comment]
Hey @smic1909,

For the way we are currently generating our models and because of other internal blockers,  we do not see any benefit of using lombok at the moment.

Regards,
Andrei.

**Comment by smic1909** [comment]
Hey Andrei,

thanks for information. Sad to hear internal reasons speak against it. In case you solved the internal blockers and need support on this, please let me know.

Best
Simon
