### ISSUE TITLE
Support different ways of providing terminal certificates

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-java-api-library#388]
**Is your feature request related to a problem? Please describe.**
Currently the only way to provide a terminal certificate to the library is via `Config.terminalCertificatePath`. On Android it makes more sense to store the certificates as resources as opposed to files in the file system.

**Describe the solution you'd like**
I'd like to have a different way of providing the certificates. On my fork I've added a `Config.terminalCertificateStream` property which allows me to provide a resource stream.

**Describe alternatives you've considered**
Another option would be a `Config.terminalCertificate` of type `String`, which would be the most flexible and allow user to read the certificate in any way. I have not tried this approach though.

I'd be happy to provide a PR.

**Comment by Aleffio** [comment]
Hi @jnorkus ,

Thanks for opening the issue,
Indeed it would be awesome if you could open a pr with an additional way of providing the certificates.
I think adding `Config.terminalCertificateStream` will work as it doesn't change the other flow if users still want to use that one.
Can you please open the PR?

Thanks,
Alessio
Adyen

**Comment by Aleffio** [comment]
Closing this issue since it is now included in the latest release,
thank you for the contribution.

Regards,
Alessio
Adyen
