### ISSUE TITLE
HTTPClientException not mapped correctly to ApiException

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-java-api-library#390]
**Describe the bug**
When making a local terminal request, the lib is throwing a `HTTPClientException` with body `{"errors": ["Nexo Service: crypto error (6)"], "ServiceID": "-NULL-"}`. It then maps it to an `ApiException` and parses an `ApiError`. But the properties of `ApiError` are all nulls. This hides the underlying problem from lib consumers.

**How to reproduce**
Not sure how to reproduce as I haven't figured out what "crypto error (6)" means. But you should be able to do it by mocking such response.

**Expected behavior**
`ApiException` with error property and all (or most) of its values filled in.

**Additional context**
Resource.java
```
public String request(String json, RequestOptions requestOptions)
```

**Comment by Aleffio** [comment]
Hi @jnorkus ,
Are you sending `ServiceID` in the `messageHeader`?
Do you have an example of the request?
I think we need to add the fields into ApiException, we are going to investigate on it.

Thanks,
Alessio
Adyen

**Comment by jnorkus** [comment]
I only saw this issue after swapping the terminal.
1. I powered down the original terminal
2. I connected the new terminal to the same wifi network and set the same static IP as the original terminal
3. I tried connecting to it and that's how I got the error message

Next day I tried again and was not able to reproduce, the issue went away.

But I think those fields need to be added to ApiException as there might be more cases of similar response.

**Comment by AlexandrosMor** [comment]
Hello @jnorkus,

I would like to ask if this issue is solved for you. If yes then we can close the issue. Otherwise please add the request json messages so we can investigate the issue further

kind regards,
Alexandros
Adyen

**Comment by jnorkus** [comment]
Hi @AlexandrosMor. I have not had an issue since. However I still think `ApiException` should be extended.

**Comment by AlexandrosMor** [comment]
Hello @jnorkus,

Could you give us an example extending the `ApiException`  and how this is useful for the integration ?

kind regards,
Alexandros
Adyen

**Comment by jillingk** [comment]
Closing this ticket as we're not getting a response.
