### ISSUE TITLE
Crash when using a local certificate

### ISSUE THREAD

**Issue by DantheCodingGui** [Adyen/adyen-java-api-library#402]
**Describe the bug**
When making a (Resource) request with a local certificate (`terminalCertificatePath` set on the Client config), I'm getting an `ApiException`. 

Debugged it and found that a call to `FileInputStream` is the issue, `reset` is called on it which throws an `IOException` (mark/reset not supported), (HttpUrlConnectionClient:272 on lib version 8.1.0). Gets rethrown as an `ApiException`.

**Additional context**
Using this through Android, supporting Java 8.

**Comment by Aleffio** [comment]
Hi @DantheCodingGui 
thank you for opening the issue, I am opening a ticket to investigate on that.
@jnorkus did you perhaps encounter the same issue when testing a request with a local certificate on Android?

Regards,
Alessio
Adyen

**Comment by jnorkus** [comment]
Hi. I did not test the `terminalCertificatePath` on Android. I load the stream from a resource which supports resetting and I found it to be needed for that scenario.

**Comment by saquibsayyad** [comment]
We have removed `terminalCertificateStream.reset()` as it fails for the InputStream which does not support mark() (such as FileInputStream) or if no mark is set before calling reset.  Check [reset()](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#reset--) for more details.
