### ISSUE TITLE
Additional timestamp format

### ISSUE THREAD

**Issue by DantheCodingGui** [Adyen/adyen-java-api-library#411]
Hi, 

Just got my terminal connecting for the first time but just wanted to query about the timestamp format for `SaleData`.

Currently the only format supported is `XMLGregorianCalendar`, which would be fine except the method to acquire it isn't supported out of the box on Android, I've had to add an extra dependency for it.

Considering it's just for a timestamp, unless there's another reason i'm not seeing, could an additional supported format be added?

Thanks

**Comment by Aleffio** [comment]
Hi @DantheCodingGui ,
indeed it's only used for timestamp, do you have any suggestions for a format which is also available on Android?
Kind regards,
Alessio
Adyen

**Comment by DantheCodingGui** [comment]
Hi @Aleffio ,

The simplest format I can think of is a `long` of Epoch milliseconds, so I could use `System.currentTimeMillis()`

Thanks

**Comment by AlexandrosMor** [comment]
Hello @DantheCodingGui,

Feel free to open a pull request with your suggestion so we can included with the next release

kind regards
Alexandros
Adyen

**Comment by AlexandrosMor** [comment]
Hi @DantheCodingGui 

Hope you are doing well, the conversion should be done in the application side and the library should not interfere with the POS response values  

kind regards
Alexandros
Adyen
