### ISSUE TITLE
Unparsable Date Exception on parsing notification

### ISSUE THREAD

**Issue by mahesh88** [Adyen/adyen-java-api-library#413]
**Describe the bug**
An exception getting raised while parsing notification json using adyen library

**How to reproduce**

**Expected behavior**
I would expect to json to converted to NotificationRequest  . See snippet below .
 
[InputJson.txt](https://github.com/Adyen/adyen-java-api-library/files/5169857/InputJson.txt)
NotificationHandler notificationHandler = new NotificationHandler();
 NotificationRequest notificationRequest = notificationHandler
                            .handleNotificationJson(notificationRequestJson);
[Exception.txt](https://github.com/Adyen/adyen-java-api-library/files/5169868/Exception.txt)
**Screenshots**

**Desktop (please complete the following information):**
 - Java Version:  1.8.0_261
 - Library Version:  8.2.0

**Additional context**

**Comment by Aleffio** [comment]
Hi @mahesh88 ,
I tried to parse the notification in InputJson.txt but I didn't have any problems,
which version of GSON are you using?
Kind Regards,
Alessio
Adyen

**Comment by mahesh88** [comment]
Hi @Aleffio 

We have GSON 2.1 in our dependency .

Regards
Mahesh Sachdeva

**Comment by saquibsayyad** [comment]
Hi @mahesh88 

Gson `2.1` does not supports custom serialization using `@JsonAdapter` as it was introduced in version `2.3`. That's why it is failing.
We will recommend you to update GSON version to same as Adyen library which is `2.8.6`.

Thanks,
Saquib
Adyen
