### ISSUE TITLE
Difference between JAva API Library and Checkout API

### ISSUE THREAD

**Issue by faridulhaq** [Adyen/adyen-java-api-library#415]
Dear Sir,

This is Farid with you and we are facing issues with Android Drop-IN SDK like 

when we are using Android SDK with below URLS 

https://checkout-test.adyen.com/v64/paymentMethods
https://checkout-test.adyen.com/v64/payments
https://checkout-test.adyen.com/v64/payments/details

it works fine but when we are using adyen-java-api-library

it is rejecting paymentMethods request by saying that channel should be "ANDROID" all caps

it is rejecting payments by saying that channel should be "Android" and dateOfBirth should not be "" whereas Drop-IN is by default sending channel="android"  and dateOfBirth=""

and in the response adyen-java-api-library is returning action

 "type": "REDIRECT" whereas with checkout API its in small which is expected by Android Drop-IN SDK

Kindly guide us how to make the marriage successful between Android Drop-IN SDK and adyen-java-api-library

**Comment by davidzadrazil** [comment]
We are facing the same problem now. iOS SDK is expecting `v64`, but Java library is using `v54` so forwarding `paymentMethods` to iOS through our backend is impossible.

**Comment by Futy99** [comment]
> We are facing the same problem now. iOS SDK is expecting `v64`, but Java library is using `v54`, so forwarding `paymentMethods` to iOS through our backend is impossible.
> 
> And this issue is 18 days without any response from Adyen.

Facing same issue as @davidzadrazil.

**Comment by Aleffio** [comment]
Hi @faridulhaq ,

we are working on a helper function to deserialize the response of drop-in,
also we are going to release a new version soon with support to v64.

Kind Regards,
Alessio
Adyen

**Comment by jimmiebfulton** [comment]
I also notice in the Java SDK differences between the URLs.  For instance, as noted above, the paymentMethods URLs in the Java SDK looks like:

```
https://checkout-test.adyen.com/checkout/v64/paymentMethods
```

There is an extra 'checkout' in the constructed path.  This can be overwritten by setting the chechoutEndpoint explicitly, but this does not match your documentation.

**Comment by Aleffio** [comment]
Hi @faridulhaq ,

with the latest version of the api library it is now possible to deserialize the dropin data into the correct payment method "Details" class #463.
Hi @jimmiebfulton thanks, we're going to remove it soon, the path is still valid though, so it shouldn't be a problem at the moment to call the Checkout endpoints.

Regards,
Alessio 
Adyen
