### ISSUE TITLE
HostedPaymentPages.getPostParametersFromDLRequest incomplete

### ISSUE THREAD

**Issue by sanmibuh** [Adyen/adyen-java-api-library#42]
Hello,
HostedPaymentPages.getPostParametersFromDLRequest is incomplete. Missing arguments:
- shopperLocale
- resURL
- shopperEmail
- shopper.firstName
- shopper.lastName
- shopper.telephoneNumber
- brandCode
- blockedMethods
- allowedMethods
- billingAddress.street
- billingAddress.houseNumberOrName
- billingAddress.city
- billingAddress.postalCode
- billingAddress.stateOrProvince
- billingAddress.country

And sessionValidity could have a fallback with Util.calculateSessionValidity()

Regards

**Comment by rikterbeek** [comment]
Hi @sanmibuh,

DirectoryLookup is only used for retrieving the payment methods so the fields you are mentioning are not needed. This is something you need to provide in the HPP request.
see params that are available for Directory Lookup here: https://docs.adyen.com/developers/products-and-subscriptions/hosted-payment-pages/payment-request/directory-lookup-call

Regards,
Rik
Adyen
