### ISSUE TITLE
Java API to support additional productUrl and imageUrl passed with LineItems for Klarna

### ISSUE THREAD

**Issue by gochev** [Adyen/adyen-java-api-library#443]
**Java version**: 1.8
**Library version**: 4.0.1

**Is your feature request related to a problem? Please describe.**

Klarna shows images inside the emails that are send to customers for each product ordered. This images are by default clickable so the user can be send back to the website product details page. 
However the current API doesnt provide the 2 fields for productUrl and imageUrl. So it will be good if this 2 properties are added.

**Describe the solution you'd like**
Just add the two missing properties on the LineItem.

**Describe alternatives you've considered**
Currently we have to extend the LineItem and the PaymentRequest which is less then ideal.

**Additional context**
Right now all the klarna content looks less then ideal on the klarna website and in the emails Klarna send e.g.
![54dd5e2e-d419-4376-a5be-7a2db89d9e58](https://user-images.githubusercontent.com/5537142/96444851-ea017580-1206-11eb-832c-ad7e18f148de.png)

**Comment by Aleffio** [comment]
Hi @gochev ,

Thank you for opening the issue, we are going to add those two fields and release a new version.

Kind Regards,
Alessio
Adyen

**Comment by zurmalik** [comment]
Hi @gochev ,

I hope your issue is resolved in the latest release.

Thanks,
Hafeez

**Comment by gochev** [comment]
Hello thanks I havent upgraded yet but I see the projectURL and imageURL are there so all should be good.
