### ISSUE TITLE
Apache connection pooling

### ISSUE THREAD

**Issue by mathieu-stennier** [Adyen/adyen-java-api-library#448]
**Java version**: 8+
**Library version**: 9.0.0

**Is your feature request related to a problem? Please describe.**
We would like to pool our HTTP connections towards your API endpoint and are unable to do so with the current implementation of the `Client`.

**Describe the solution you'd like**
Would it be possible to use apache `PoolingHttpClientConnectionManager` and `HttpClient` objects? Would you be against it? I am also keen to help if you would need a PR for that.

**Describe alternatives you've considered**
I have thought about extends `Client` and `HttpURLConnectionClient` but they don't allow dependency injection for HTTP client connections.

**Comment by Aleffio** [comment]
Hi @mathieu-stennier ,

Thank you for opening the issue,
we are investigating the possibility to use apache pooling objects,
what is the scenario you trying to implement?

Kind Regards,
Alessio
Adyen

**Comment by jillingk** [comment]
Closing this ticket because of inactivity.
