### ISSUE TITLE
Change the definition of "metadata" field for PaymentRequest model

### ISSUE THREAD

**Issue by anatolii-kishovar-lebara** [Adyen/adyen-java-api-library#45]
Can we use the "Map<String,String>" for "metadata" field definition instead of "String" at "com.adyen.model.AbstractPaymentRequest" (like it is for "additionalData" field)?

**Comment by lancergr** [comment]
Hi @anatolii-kishovar-lebara 

You are right, Map should be the appropriate type.
Would you like to submit a PR? else I can push a fix for it this week.

Regards,
Giorgos
Adyen

**Comment by anatolii-kishovar-lebara** [comment]
Please proceed :)
