### ISSUE TITLE
"Refund with data" is not supported.

### ISSUE THREAD

**Issue by phmp** [Adyen/adyen-java-api-library#457]
**Library version**: 10.0.0
**Description**
I cannot find path “/refundWithData”.
There is eventCode “REFUND_WITH_DATA” but is not used anywhere.
Can you add support for unreferenced refund?

**Comment by Aleffio** [comment]
Hi @phmp ,

Thank you for opening the issue.
We are looking into the possibility to add this endpoint,
I am creating an internal ticket,

Kind Regards,
Alessio
Adyen

**Comment by SrinivasKG1** [comment]
Hi Team, Is there an update on this issue..when refundwithdata will be supported in java-adyen-ali-library

**Comment by jillingk** [comment]
Hi @SrinivasKG1,

Sorry for the super delayed respons. I don't think we will implement this any time soon unfortunately. You're more than welcome to open a PR though! 

Best, Jilling
Adyen
