### ISSUE TITLE
PW-3434 - ResponseEnum removed without offering a proper alternative

### ISSUE THREAD

**Issue by chrisovergaauw** [Adyen/adyen-java-api-library#458]
**Describe the bug**
All versions prior to 8.0.0 offered a ModificationResult.ResponseEnum.
This has been replaced by a String which makes implementing logic based on the ModificationResult error prone.

**Expected behavior**
Extension of the Enum or any other form of constants.
The way the tests are fixed by checking against hardcoded strings is also ugly and likely to break with future updates of the SDK.

**Desktop (please complete the following information):**
 - Java Version: 1.8.44
 - Library Version: 8.0.0

EDIT: corrected version from 10.0.0 to 8.0.0

**Comment by Aleffio** [comment]
Hi @chrisovergaauw, 

Thank you for opening the issue.
We will create constants with all possible values, so that the String value can be compared to those.

Kind Regards,
Alessio
Adyen
