### ISSUE TITLE
SaleToAcquirerData - JSON vs Key-Value pair

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-java-api-library#459]
As I understand currently when setting the `SaleToAcquirerData`, the JSON serialization is used, which also causes the `AdditionalResponse` to be a Base64 encoded JSON as described [here](https://docs.adyen.com/point-of-sale/add-data#adding-data-elements-to-your-request).

I have noticed one inconsistency in a specific scenario. When passing a wrong POI ID in the `MessageHeader`, the `AdditionalResponse` that comes back with an error response is formatted as a Key-Value pair.

I assume that is because if there is an error within the `MessageHeader`, `SaleToAcquirerData` format is not even checked, so `AdditionalResponse` comes back as a Key-Value pair.

I'd like to know what is the best way to keep consistency in my code. I could just pass the `SaleToAcquirerData` formatted as a Key-Value pair but I don't think that's possible using this Java lib.

**Comment by Aleffio** [comment]
Hi @jnorkus 
Thank you for opening the issue,

it is indeed weird that you pass this value as Base64 and you get back a Key-Value pair.
We will try to reproduce the issue and investigate more.
Just to exclude some scenarios: is the POIID you passed in the request in the correct format but wrong value?

Kind Regards,
Alessio
Adyen

**Comment by jnorkus** [comment]
To answer your question - yes, the POIID is a wrong value. You can reproduce by passing "e285-123456789".

**Comment by Aleffio** [comment]
Hi @jnorkus ,

I verified with POS developers and `AdditionalResponse` is passed back as key-value pair in case of errors.
This is to keep it "human-readable" in case of integration problems.
The library will return `AdditionalResponse` as a String as specified by the nexo protocol.

Kind Regards,
Alessio
Adyen

**Comment by AlexandrosMor** [comment]
This issue is answered so we can close it. Feel free to open a new issue if you have more questions

Alexandros
Adyen
