### ISSUE TITLE
API error on Payment details request after upgrade

### ISSUE THREAD

**Issue by amortJ** [Adyen/adyen-java-api-library#468]
Hi,

we upgraded the adyen java library from version 8.0.0 to 10.1.0 on a testenvironment and now we get an API error on the payment details request.

The call to com.adyen.service.Checkout.paymentsDetails() throws the following exception:

`
ApiException{error=class ApiError {
    status: 400
    errorCode: 702
    message: Structure of PaymentCompletionDetails contains the following unmapped fields type
    errorType: validation
    pspReference: null
    invalidFields: null
}, statusCode=400, message=HTTP Exception, responseHeaders={Transfer-Encoding=[chunked], null=[HTTP/1.1 400 400], Server=[Apache], Connection=[close], Set-Cookie=[JSESSIONID=<redacted>; Path=/checkout; Secure; HttpOnly], pspReference=[<redacted>], Date=[Thu, 26 Nov 2020 13:59:55 GMT], Content-Type=[application/json;charset=UTF-8]}}
`

Best regards,
Jan

**Comment by Aleffio** [comment]
Hi Jan,

can you please contact our support at support@adyen.com with the pspreference of the payments/details call?

Kind Regards,
Alessio
Adyen

**Comment by amortJ** [comment]
Hi Alessio,
I did contact the support. Please see ticket https://www.adyen.help/hc/en-us/requests/1747416 for details.

Best regards,
Jan

**Comment by Aleffio** [comment]
Hi @amortJ ,

I see the ticket https://www.adyen.help/hc/en-us/requests/1747416 has been solved, so I am closing this ticket.
Feel free to reopen it if the issue persists.

Regards,
Alessio
Adyen
