### ISSUE TITLE
api version 65 is not backwards compatible

### ISSUE THREAD

**Issue by chrisovergaauw** [Adyen/adyen-java-api-library#471]
Drop-in version 3.5.0 suddenly stopped working without any changes.
The newest version of the drop-in is 3.18. There should be no reason for the sudden incompatibility.
Java Version: 
Due to these changes we're forced to upgrade the SDK and the drop-in to the latest version.

I'm aware, this repo is not the drop-in not the API itself. But it's not public and you're either working on both or working tightly together on this.
Breaking the API specification like this, and causing downtime for your customers is highly inappropriate.
Please, provide a hot-fix or revert the latest upgrade.

 - Java Version: 8
 - Library Version: 2.6.1
- Drop-in Version: 3.5.0
- API Version: 65

**Comment by Aleffio** [comment]
Hi @chrisovergaauw ,

we didn't discontinue version 3.5.0 of the drop-in, what kind of error are you getting?
I suggest you also send an email to our support team support@adyen.com.

Regards,
Alessio
Adyen

**Comment by Aleffio** [comment]
Hi @chrisovergaauw,

I am closing this issue for now, please feel free to reopen it if the issue persists.

Regards,
Alessio
Adyen
