### ISSUE TITLE
Add error to TransferFundsNotification

### ISSUE THREAD

**Issue by luggi961** [Adyen/adyen-java-api-library#474]
**Description**
Can you add error field in TransferFundsNotification?

**Comment by Aleffio** [comment]
Hi @luggi961 ,

thanks for opening the issue,
I am creating an internal ticket to update all the Notification classes.

regards,
Alessio
Adyen

**Comment by luggi961** [comment]
Can you please also add `invalidFields` in `TransferFundsContent`? Would be quite important and urgent.
It would be best if SDK supports all fields from API.
