### ISSUE TITLE
Add documentation for default connectionTimeout and readTimeout

### ISSUE THREAD

**Issue by EsbenAarz** [Adyen/adyen-java-api-library#482]
**Java version**: Not relevant
**Library version**: 11.0.0

**Is your feature request related to a problem? Please describe.**
We received a couple of connection timeouts yesterday, and I'm currently in the process of deciding  sane timeout-values towards adyen. I've tried navigating through the codebase, but can't seem to find any documentation on what the default timeouts are (both connect and read). 

**Describe the solution you'd like**
Consider adding some javadoc specifying the default values. 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Aleffio** [comment]
Hi @EsbenAarz ,

Unfortunately we don't have any timeout values to advise,
the default value for *connectionTimeout* and *readTimeout* is 0, as they are using the **URLConnection** class that does not have default values.
We introduced in the past the possibility to set a custom timeout, in case you are relying on other platforms/browsers with a set time out.

Regards,
Alessio
Adyen

**Comment by EsbenAarz** [comment]
Allright, I guess I'll just close the issue then.
