### ISSUE TITLE
Wrong Date format pattern

### ISSUE THREAD

**Issue by jherimum** [Adyen/adyen-java-api-library#49]
The date format pattern is wrong in above line!
The correct pattern should be "YYYY-MM-dd'T'HH:mm:ss.sss'Z'"

https://github.com/Adyen/adyen-java-api-library/blob/daea948e844affc48fa383529a30a42e9c5f1f51/src/main/java/com/adyen/serializer/DateTimeGMTSerializer.java#L34

**Comment by rikterbeek** [comment]
Hi @jherimum,

Not following you here, the pattern is already: "YYYY-MM-dd'T'HH:mm:ss.sss'Z'"

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @jherinum,

Thanks did not see that. Although it did not create any problems on my side it indeed is better to use lowercase.  Did it cause problems in your api calls ?

Regards,
Rik
Adyen

**Comment by jherimum** [comment]
Im from brazil, and we need to use deliveryDate to create a  Boleto Payment! So when we make the request, Adyen invalidate the date. DD representas Day of year.
Thanks

**Comment by lancergr** [comment]
Hi @jherimum 

Thanks for reporting this!
I have pushed a fix on develop branch.

Regards,
Giorgos
Adyen
