### ISSUE TITLE
Install library error

### ISSUE THREAD

**Issue by alex-huang-dc** [Adyen/adyen-java-api-library#490]
**Describe the bug**
Display "Cannot resolve com.adyen:adyen-java-api-library:12.0.0" when I put dependency into my pom 

**How to reproduce**
Simple Copy the dependency and put it into pom dependencies, popup error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75409389/106346986-87495c80-6280-11eb-8889-c32eabee67b3.png)

**Desktop (please complete the following information):**
 - Java Version: 1.8
 - Library Version: 12.0.0

**Additional context**
Using Springboot

**Comment by Aleffio** [comment]
Hi @alex-huang-dc ,

The version 12.0.0 has just been released,
it should be available on maven in a while.
Feel free to reopen the issue if you see further issues.

Kind Regards,
Alessio
Adyen
