### ISSUE TITLE
ACCOUNT_HOLDER_VERIFICATION Notification not compatible with latest version

### ISSUE THREAD

**Issue by amortJ** [Adyen/adyen-java-api-library#500]
When I try to parse the Marketpay notification ACCOUNT_HOLDER_VERIFICATION in the format of the latest version (v6) through NotificationHandler.handleMarketpayNotificationJson() the resulting object is missing some important fields. 

The structure of the notification has changed between v4 and v6 quite a bit. So when I try to parse a notification in the v6 format the fields verificationtype, verificationStatus and statusSummary are not mapped correctly.
https://docs.adyen.com/api-explorer/#/NotificationService/v4/post/ACCOUNT_HOLDER_VERIFICATION
https://docs.adyen.com/api-explorer/#/NotificationService/v6/post/ACCOUNT_HOLDER_VERIFICATION

## Example
`
// the notification is taken from the documentation (see links above)
        String notificationJson = "{\"error\": {\"errorCode\": \"000\",\"message\": \"test error message\"},\"eventDate\": \"2019-01-01T01:00:00+01:00\",\"eventType\": \"ACCOUNT_HOLDER_VERIFICATION\",\"executingUserKey\": \"executing-user-key\",\"live\": false,\"pspReference\": \"TSTPSPR0001\",\"content\": {\"accountHolderCode\": \"AH0000001\",\"bankAccountUUID\": \"00000000-0000-0000-0000-000000000000\",\"kycCheckStatusData\": {\"type\": \"IDENTITY_VERIFICATION\",\"status\": \"PENDING\",\"summary\": {\"kycCheckCode\": 100,\"kycCheckDescription\": \"KYC check summary description\"},\"requiredFields\": [\"field.missing\"]},\"shareholderCode\": \"SH00000001\"}}";
        final AccountHolderVerificationNotification genericNotification = (AccountHolderVerificationNotification) new NotificationHandler().handleMarketpayNotificationJson(notificationJson);

        assertThat(genericNotification.getContent().getVerificationStatus()).isNotNull(); // fails
        assertThat(genericNotification.getContent().getVerificationType()).isNotNull(); // fails
`

There might be other notifications that have similar issues as well. It would be great if you could make sure that the library is able to handle all marketpay notifications of the v6 API.

**Comment by Aleffio** [comment]
Hi @amortJ,

thanks for opening the issue, I am creating an internal task to fix the notification issue.

Regards,
Alessio
Adyen
