### ISSUE TITLE
Adyen Integration via PaymentLink - Missing GET request for PaymentLink details

### ISSUE THREAD

**Issue by torsten-lorenz** [Adyen/adyen-java-api-library#501]
**Open JDK**: 11.0.7
**adyen-java-api-library**: 11.0.0

We currently integrate Adyen in our webshop (SPA + Back-End). We want to use the integration via PaymentLink. Therefore we want to use the adyen-java-api-library within our back-end (as Adyen client) for requesting following endpoints:
 
POST /paymentLinks
GET /paymentLInks/{linkId}

During the implementation we realized, there is no support yet for endpoint GET /paymentLInks/{linkId} in the adyen-java-api-library yet. Why come?

**Comment by Aleffio** [comment]
Hi @torsten-lorenz,

Thanks for opening the issue, at the moment our API libraries only support POST, but we are planning to support the GET/PATCH methods in the upcoming weeks.

Regards,
Alessio
Adyen

**Comment by Daanielvb** [comment]
do you have any ETAs on the get calls @Aleffio  ?

**Comment by Aleffio** [comment]
Hi @Daanielvb ,
we have a pull request open: #524 we are reviewing it and we will do a release next week.

Regards,
Alessio
Adyen

**Comment by Aleffio** [comment]
Hi @torsten-lorenz and @Daanielvb ,
GET and PATCH are now available on the latest 15.0.0 release.
Closing the issue.

Regards,
Alessio
Adyen
