### ISSUE TITLE
HttpURLConnectionClient line fix

### ISSUE THREAD

**Issue by sanmibuh** [Adyen/adyen-java-api-library#51]
Hello,

I think this line does nothing:

https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java#L64

Best

**Comment by lancergr** [comment]
Hi @sanmibuh 

Thanks for your input! We will remove it because it seems indeed redundant.

Regards,
Giorgos
Adyen

**Comment by lancergr** [comment]
Fixed in #52
