### ISSUE TITLE
about post / payments request field, threeDS2RequestData.deviceRenderOptions. sdkInterface

### ISSUE THREAD

**Issue by morisada-mina** [Adyen/adyen-java-api-library#510]
Java Version: 1.8
 Library Version: 13.0.0

I have a question about the threeDS2RequestData.deviceRenderOptions.sdkInterface in the /payments request.

I set DeviceRenderOptions.SdkInterfaceEnum.NATIVE and tested it and got the following error
error code:702, detail message:Failed to serialize node Invalid sdkInterface: Native, error type:validation.

The API specification states that the value is one of the following
* native
* html
* both
https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_threeDS2RequestData-deviceRenderOptions-sdkInterface

However, the actual implementation is Native, Html, and both.
The first digit of Native and Html is capitalized.
https://github.com/Adyen/adyen-java-api-library/blob/ed0450097faf23d5c880b91010e9c8def5f85a18/src/main/java/com/adyen/model/DeviceRenderOptions.java#L53

I think the value of SdkInterfaceEnum.class is not correct.
Please check.

**Comment by Aleffio** [comment]
Hi @morisada-mina ,

Thanks for reporting the issue,
We are pushing a fix for this, it will be available in the next release.

Regards,
Alessio
Adyen
