### ISSUE TITLE
PaymentsResponse - To String Method calls super.hashCode() instead of super.toString()

### ISSUE THREAD

**Issue by NadirHelix** [Adyen/adyen-java-api-library#526]
We found out that the toString() method in the PaymentsResponse seems to be written wrong. In other AbstractPaymentsResponse classes `super.toString()` is calles whereas here it's `super.hashCode()`

see reference: 
https://github.com/Adyen/adyen-java-api-library/blob/65eadba2a803e45caf07e52538cf7f6a86799481/src/main/java/com/adyen/model/checkout/PaymentsResponse.java#L82

If possible please fix this, otherwise we are blind in our detailed logging.

**Comment by Aleffio** [comment]
Hi @NadirHelix , indeed, thanks for opening the issue,
we're going to fix it immediately.

Regards,
Alessio
Adyen

**Comment by NadirHelix** [comment]
Hi @Aleffio,
thanks for fast response. Do you already know, when the fix will be available?

Best regards,
NadirHelix
