### ISSUE TITLE
3D Secure Flow - action object not accesible when calling `payments/details` 

### ISSUE THREAD

**Issue by julianhirt** [Adyen/adyen-java-api-library#528]
The documenation for the 3d secure flow states that it is possible to retrieve another `action` when calling `/payments/details` when solving the 3d secure challenge. Unfortunately the `PaymentsDetailsResponse` does not give access to that `action` object. 

# Documentation: 

```
Your next steps depend on whether the /payments/details response contains an action object.
```

https://docs.adyen.com/online-payments/3d-secure/native-3ds2/android-component?tab=codeBlockdetails_request_component_3ds_3

Am I missing something or is the documentation outdated?

**Comment by Aleffio** [comment]
Hi @julianhirt ,

thanks for raising the issue, the documentation has two different tabs for `v66` and `v67`.
In `v67`, supported by the latest version of this library, the `action` field has been removed from the `/details/ response:
https://docs.adyen.com/online-payments/release-notes#breaking-changes.
Hope this helps!

Regards,
Alessio
Adyen

**Comment by julianhirt** [comment]
Hi @Aleffio 
Thanks for the help! Indeed I didnt not realize that this was changed. So as far I understand it, it is simply not possible to retrieve another action after `/payments/details`. It just works or doesnt, right? 
Thanks for the quick support!
