### ISSUE TITLE
AccountHolderStatus.events missing / AccountHolderStatus.accountEvents has wrong name

### ISSUE THREAD

**Issue by LukasDrP** [Adyen/adyen-java-api-library#529]
**Describe the bug**

AccountHolderStatus (eg used in the ACCOUNT_HOLDER_STATUS_CHANGE-notification as content->newStatus/oldStatus as described here https://docs.adyen.com/api-explorer/#/NotificationService/v3/post/ACCOUNT_HOLDER_STATUS_CHANGE) should have a field "events" but has instead a field "accountEvents". As a result, "accountEvents" is always empty. 

**How to reproduce**

receiven an ACCOUNT_HOLDER_STATUS_CHANGE-Notification (e.g. by onboarding a new Account and setting its tier to 3) and compare the parsed Object with the plain JSON Event. 

**Expected behavior**

The deserialized (Java-) Object should represent the same data as the serialized (JSON) one. 

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: 11
 - Library Version: 13.1.0

**Additional context**

**Comment by Aleffio** [comment]
Hi @LukasDrP 
thanks for raising the issue, this was addressed in #522
and the fix will be available in the upcoming 14.0.0 release.

Regards,
Alessio
Adyen

**Comment by LukasDrP** [comment]
Hi @Aleffio, 
thanks your quick response. However, the ArrayList gets filled now, but the AccountEvent-Objects in there are always filled with null-values. The notification before getting parsed to an java-object:
```
{
	"eventDate": "2021-04-30T12:50:27+02:00",
	"eventType": "ACCOUNT_HOLDER_STATUS_CHANGE",
	"executingUserKey": "Status Update",
	"live": "false",
	"pspReference": "8816197798196087",
	"content": {
		"accountHolderCode": "671603ec-90b5-4a10-ad96-b95a8eeba8af",
		"oldStatus": {
			"status": "Active",
			"processingState": {},
			"payoutState": {
				"allowPayout": "false"
			},
			"events": []
		},
		"newStatus": {
			"status": "Active",
			"processingState": {
				"disabled": "false",
				"processedFrom": {
					"currency": "EUR",
					"value": 500000
				},
				"tierNumber": 3
			},
			"payoutState": {
				"allowPayout": "false",
				"disabled": "false"
			},
			"events": [
				{
					"AccountEvent": {
						"event": "InactivateAccount",
						"executionDate": "2021-05-30T12:50:27+02:00",
						"reason": "Processed more than EUR 5000.00 or equivalent, deadline triggered"
					}
				}
			]
		},
		"reason": "Account holder has been updated"
	}
}
```
The same notification after getting parsed to an java-object:
```
 {
	"eventType": "ACCOUNT_HOLDER_STATUS_CHANGE",
	"content": {
		"accountHolderCode": "671603ec-90b5-4a10-ad96-b95a8eeba8af",
		"invalidFields": null,
		"newStatus": {
			"events": [
				{
					"reason": null,
					"resolvedByStateType": null,
					"executionDate": null,
					"event": null
				}
			],
			"payoutState": {
				"allowPayout": false,
				"disableReason": null,
				"disabled": false,
				"notAllowedReason": null,
				"payoutLimit": null,
				"tierNumber": null
			},
			"processingState": {
				"disableReason": null,
				"processedTo": null,
				"processedFrom": {
					"value": 500000,
					"currency": "EUR"
				},
				"tierNumber": 3,
				"disabled": false
			},
			"status": "Active",
			"statusReason": null
		},
		"oldStatus": {
			"events": [],
			"payoutState": {
				"allowPayout": false,
				"disableReason": null,
				"disabled": null,
				"notAllowedReason": null,
				"payoutLimit": null,
				"tierNumber": null
			},
			"processingState": {
				"disableReason": null,
				"processedTo": null,
				"processedFrom": null,
				"tierNumber": null,
				"disabled": null
			},
			"status": "Active",
			"statusReason": null
		},
		"reason": "Account holder has been updated"
	},
	"error": null,
	"eventDate": 1619779827000,
	"executingUserKey": "Status Update",
	"live": false,
	"pspReference": "8816197798196087"
}
```

it looks like each AccountEvent should be wrapped into an anonymous wrapper-object.

**Comment by Aleffio** [comment]
Hi @LukasDrP,
indeed, we're going to fix it asap.
Sorry for the inconvenience.

Regards,
Alessio
Adyen

**Comment by RickWieman** [comment]
@LukasDrP That looks like an old version of the notification. Can you update your notification configuration to use `apiVersion` 5 or 6? That should remove the wrapper of `AccountEvent`.

@Aleffio Can we revert this change? It seems to break for API v5/6, as reported in #589.

**Comment by LukasDrP** [comment]
@RickWieman i don't think so. i'm using the current version of this java-library which is - if i understand it correctly - using the most recent api-version. if i go into the request, thats currently v6 of the MARKETPAY_NOTIFICATION_API_VERSION. 
looking at the documentation of v6 also shows the same structure in the example: https://docs.adyen.com/api-explorer/#/NotificationService/v6/post/ACCOUNT_HOLDER_STATUS_CHANGE

**Comment by RickWieman** [comment]
@LukasDrP You raise a valid point on the example from the API Explorer, let me take that feedback internally. The `MARKETPAY_NOTIFICATION_API_VERSION ` is used to specify the API version for the notification _configuration_ API, but not for setting the version _within_ the notification configuration. For that, you'd need to specify `com.adyen.model.marketpay.notification.NotificationConfigurationDetails#apiVersion`, which seems to default to `null`.

Based on your above example JSON, I quickly checked the configuration on your marketplace, and the apiVersion is not set for the notification endpoints in that marketplace -- which triggers a fallback to an older version than v5. Can you re-create or update your notification configurations by setting `apiVersion` to `5` or `6`?

**Comment by LukasDrP** [comment]
@RickWieman interessting. i didn't realize i could/have to set the api-Version in the json. but you're right, with version 6 the event looks like this: 
`{
	"eventDate": "2021-07-30T10:12:47+02:00",
	"eventType": "ACCOUNT_HOLDER_STATUS_CHANGE",
	"executingUserKey": "Status Update",
	"live": false,
	"pspReference": "8516276327609282",
	"content": {
		"accountHolderCode": "bf5650bb-17af-4bc1-ad56-0c60edf72d1e",
		"oldStatus": {
			"status": "Active",
			"processingState": {},
			"payoutState": {
				"allowPayout": false
			},
			"events": []
		},
		"newStatus": {
			"status": "Active",
			"processingState": {
				"disabled": false,
				"processedFrom": {
					"currency": "EUR",
					"value": 500000
				},
				"tierNumber": 3
			},
			"payoutState": {
				"allowPayout": false,
				"disabled": false
			},
			"events": [
				{
					"event": "InactivateAccount",
					"executionDate": "2021-08-29T10:12:46+02:00",
					"reason": "Processed more than EUR 5000.00 or equivalent, deadline triggered"
				}
			]
		},
		"reason": "Account holder has been updated"
	}
}`

and nextState.getEvents().get(0).getAccountEvent() is null. I'd suggest setting com.adyen.model.marketpay.notification.NotificationConfigurationDetails#apiVersion to Client.MARKETPAY_NOTIFICATION_API_VERSION and marking it as required in the documentation, too then.
