### ISSUE TITLE
Make library Stateless

### ISSUE THREAD

**Issue by sanmibuh** [Adyen/adyen-java-api-library#53]
Nowadays library is stateful:
*HttpURLConnectionClient.createRequest* saves state at *httpConnection*.
This stateful causes a bad testing uses for API clients. If this class was stateless (minor changes), we can make a singleton wrapper with spring, improving the tests.

**Comment by lancergr** [comment]
Hi @sanmibuh 
Thanks for reporting this! We will take a look and keep you posted.

Regards,
Giorgos
Adyen

**Comment by sanmibuh** [comment]
For example, we were using the library as a singleton (creating Client and Payment ones). In this case, the tests were simple. But we find one problem:

If 2 payment authorization arrives at the same time, the first payment receives the second payment response, and the second payment throws an exception (because responses inputStream was closed previously).

We see the problem was *HttpURLConnectionClient*, because saves his status (httpConnection property).

Now we change to use creating *Client* and *Payment* in each authorization and no problem. But this requires a trick at tests (like this https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/Client.java#L86 )

*setHttpClient* is used only for mocking *HttpURLConnectionClient*, and this *if* https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/Client.java#L80 is the consecuence :(

**Comment by lancergr** [comment]
Hi @sanmibuh 
I have pushed a fix for it @ 50fa6d1. Let me know is resolves your issue.

Best Regards,
Giorgos
Adyen

**Comment by sanmibuh** [comment]
Hi @lancergr 
I have tested the fix and it works!
Anyway, we will continue using official version as stateful until the new version with this patch is published :)

Best,
David Belmez
