### ISSUE TITLE
NotificationConfigurationDetails is missing the "hmacSignatureKey"

### ISSUE THREAD

**Issue by LukasDrP** [Adyen/adyen-java-api-library#533]
**Describe the bug**
NotificationConfigurationDetails is missing the "hmacSignatureKey"-Field as defined in the docs: https://docs.adyen.com/api-explorer/#/NotificationConfigurationService/v6/post/createNotificationConfiguration

**How to reproduce**
try to make an CreateNotificationConfigurationRequest and set "hmacSignatureKey" but its missing

**Expected behavior**
NotificationConfigurationDetails should have an String for "hmacSignatureKey"

**Screenshots**
-

**Desktop (please complete the following information):**
 - Java Version: 11
 - Library Version: 14.0.0

**Additional context**
-

**Comment by Aleffio** [comment]
Hi @LukasDrP , the field has been added as part of the 15.0.0 release.
I am closing the issue, feel free to reopen it in case you encounter problems with this field.

Regards,
Alessio
Adyen
