### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by bucknerns** [Adyen/adyen-java-api-library#554]
**Describe the bug**
This line will cause an exception when value is null instead of an invalid request exception or a bad hmac exception.
https://github.com/Adyen/adyen-java-api-library/blob/8f00327e57babfd034b852c9ed724649a45f9b06/src/main/java/com/adyen/util/HMACValidator.java#L90

**How to reproduce**
Steps to reproduce the behavior.
follow the guide for java and pass in a notification without value https://docs.adyen.com/development-resources/webhooks/verify-hmac-signatures#example

**Expected behavior**
A clear and concise error message/type to catch. Since the json is parsed by the library I don't see why it doesn't catch missing required fields and raise an appropriate error.
Or at least some documentation on whats fields are required for all messages, which would help with out backend testing.

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: [11.0.11]
 - Library Version: [6.1.0]

**Comment by Aleffio** [comment]
Hi @bucknerns, thanks for opening the issue,
we're going to fix that line and add proper documentation.

Regards,
Alessio
Adyen

**Comment by Aleffio** [comment]
Hi @bucknerns ,
the fix has been released in the latest 15.0.2 version,
Regards,
Alessio
Adyen
