### ISSUE TITLE
calling getAccountHolder results in a null object for AccountEvents

### ISSUE THREAD

**Issue by sluem16** [Adyen/adyen-java-api-library#589]
**Describe the bug**

After updating the Adyen Java Lib to 15.1 requesting the user status via /getAccountHolder results in a null object for AccountEvents, even if there are any in the response json. It seems like the lib expects an AccountEventContainer which the response can't provide. This bug is possible related to #529. Here the AccountEventContainer is introduced for ACCOUNT_HOLDER_STATUS_CHANGE-notifications

**How to reproduce**
Request getAccountHolder 

**Expected behavior**
Filled AccountEvent-Objects when there are present in the response json.

** System **
* Java 11
* Adyen Lib 15.1

**Additional context**
Perhabs related to the fix introduced with #529

**Comment by RickWieman** [comment]
This should be solved in release [17.0.0](https://github.com/Adyen/adyen-java-api-library/releases/tag/17.0.0)!
