### ISSUE TITLE
Google Pay

### ISSUE THREAD

**Issue by gamerX21** [Adyen/adyen-java-api-library#591]
**Describe the bug**
I already set up google pay as a payment method in my account(**MaibornWolff**)but unfortunately when I try to make payment request I got payWithgoogle Token is invalid and I re-check the configurations steps for the merchant integration with google pay but I got no result

**How to reproduce**
execute payment request with google pay 

**Desktop (please complete the following information):**
 - Java Version: openjdk 11.0.11
 - Library Version: 15.1.0

**Comment by jillingk** [comment]
Hi @gamerX21,

Sincere apology for the late response. Do you still have the same issue? If not, how were you able to solve it?

Best, Jilling
Adyen
