### ISSUE TITLE
[PW-6741] add @JsonProperty to models under com.adyen.model.nexo

### ISSUE THREAD

**Issue by rhansharief** [Adyen/adyen-java-api-library#594]
**Is your feature request related to a problem? Please describe.**
I have my endpoint for catching Terminal API Notification for my terminal cloud api implementation. My problem is when I'm trying to deserialize the json that is coming from the webhook. An example of the json is

`"MessageHeader":{
         "MessageCategory":"Payment",
         "MessageClass":"Service",
         "MessageType":"Response",
         "POIID":"P400Plus-804716806",
         "ProtocolVersion":"3.0",
         "SaleID":"aXrtW21",
         "ServiceID":"flOjdjUDox"
      }`

this is under TerminalAPIResponse.SaleToPOIResponse.MessageHeader

problem here is field messageHeader

`
    @XmlElement(name = "MessageHeader", required = true) `
    `protected MessageHeader messageHeader;`

While this can be deserialized for an xml content type, it will be hard for json deserializers since property names doesn't match.

**Describe the solution you'd like**
My proposed solution is to put `@JsonProperty` to the fields for deserialization. ie.

`
@SerializedName("MessageHeader")`
`@JsonProperty("MessageHeader")`
`protected MessageHeader messageHeader;
`

**Describe alternatives you've considered**
Right now, I'll be building a custom deserializer

**Comment by jillingk** [comment]
Hi @rhansharief,

Apologies for the super delayed respons. I will be looking into the matter and discuss wether we want to add your proposed solution or not. In the mean time I hope you figured it all out with the custom deserialiser. If you didn't or if you ran into anything else please do let me know!

Best, Jilling
Adyen

**Comment by rhansharief** [comment]
Hi @jillingk yes, I implemented a deserializer for this. Just thought this would make it easier. Thanks
