### ISSUE TITLE
Is there any java code sample repository for each Adyen API?

### ISSUE THREAD

**Issue by avaiyahardik** [Adyen/adyen-java-api-library#598]
I am using latest adyen-java-api-library 16.0.0. I see there are couple of repositories to show java integration with Adyen, however, did not find any good enough reference which gives specific examples.
Like this is how we should initiate a payment reversal / cancellation request using Adyen''s adyen-java-api-library and for others.

Is there anything available out there that I could not find in my search so far?

**Comment by avaiyahardik** [comment]
Can anyone tell me how can we integrate below API using adyen-java-api-library?
https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments/{paymentPspReference}/reversals

**Comment by deepu105** [comment]
Hi, we have samples here https://github.com/adyen-examples. The java sample doesnt have cancellations implemented but this one has https://github.com/adyen-examples/adyen-react-online-payments, you can refer that and do the same in Java. We will be adding cancellation flows in Java and other languages in the future.

cc @jlengrand
