### ISSUE TITLE
PaymentFailureNotificationContent is missing Fields

### ISSUE THREAD

**Issue by LukasDrP** [Adyen/adyen-java-api-library#603]
**Describe the bug**
PaymentFailureNotificationContent is missing Fields for modificationMerchantReference, modificationPspReference, paymentMerchantReference and paymentPspReference.

**How to reproduce**
receive a PAYMENT_FAILURE-Notification / look at com.adyen.model.marketpay.notification.PaymentFailureNotificationContent 

**Expected behavior**
The fields should be implemented and accessible. 

**Desktop (please complete the following information):**
 - Java Version: [11.x]
 - Library Version: [16.0.0]

**Comment by jillingk** [comment]
Closing this ticket as #619 seems to have fixed this issue. Thanks again for contributing @LukasDrP!
