### ISSUE TITLE
ListRecurring response object deserialization is failing for PAYPAL saved PM

### ISSUE THREAD

**Issue by anatolii-kishovar-lebara** [Adyen/adyen-java-api-library#61]
com.adyen.model.TokenDetails#tokenData is defined as String. But in response there is an object.
"tokenData": {
    "EmailId": "bla-bla",
    "PayPal.PayerId": "bla-bla",
    "BillingAgreementId": "bla-bla"
}

**Comment by rikterbeek** [comment]
Hi @anatolii-kishovar-lebara,

Thanks for addressing this issue! indeed this should be a Map of <string, string> values.
We will fix this into the code.

Regards,
Rik
Adyen

**Comment by anatolii-kishovar-lebara** [comment]
Hi @rikterbeek, team

This fix is quite important for us. When can we expect it to be fixed?

Br,
Tolik
Lebara

**Comment by rikterbeek** [comment]
Hi @anatolii-kishovar-lebara,

See above the fix. We have one extra feature we want to include into the library so we will add that as well and do a new release.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
@anatolii-kishovar-lebara,

This is fixed in release 1.2.1. I am now deploying this to maven central.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
It is deployed on maven central.

**Comment by anatolii-kishovar-lebara** [comment]
Thanks a lot
