### ISSUE TITLE
[PW-6004] No way to provide split data when making terminal payment

### ISSUE THREAD

**Issue by rhansharief** [Adyen/adyen-java-api-library#612]
**Java version**: x.y.z
**Library version**: x.y.z

**Is your feature request related to a problem? Please describe.**
I'm trying to split data when making terminal payment. The documentation says I need to provide split information thru SaleToAcquirerData but looking at the models for the terminal it looks like it is not yet supported

**Describe the solution you'd like**
Add a way to add splits to SaleToAcquirerData just like what is in com.adyen.model.PaymentRequest

**Comment by AlexandrosMor** [comment]
Hello @rhansharief,

We see the issue and we created an internal ticket for this 

kind regards, 
Alexandros
Adyen

**Comment by jillingk** [comment]
@rhansharief,

After checking the same issue for the Node library it seems you can simply pass the split data through the additionalData field in SaleToAcquirerData. This would be the preferred solution, even though our documentation says you should add it as string (we are looking to change this). If it still does not work like that, please come back to me and we will find another workaround. 

Apologies for the super delayed answer, hope this helps!

Best, Jilling
Adyen

**Comment by johanhugg** [comment]
Still seems to be the case, in 2024
