### ISSUE TITLE
[PW-6740]Add support for Disputes API

### ISSUE THREAD

**Issue by janaz** [Adyen/adyen-java-api-library#620]
**Is your feature request related to a problem? Please describe.**

I would like to access [Dispute APIs](https://docs.adyen.com/risk-management/disputes-api) using this library.

**Describe the solution you'd like**

Support for Disputes API endpoints such as
* `retrieveApplicableDefenseReasons`
* `supplyDefenseDocument`
* `deleteDisputeDefenseDocument`
* `defendDispute`

**Describe alternatives you've considered**

Create my own implementation of the `Service` interface for disputes

**Comment by LukasDrP** [comment]
I'm also missing the Events for `DISPUTE_DEFENSE_PERIOD_ENDED` and `ISSUER_COMMENTS`

**Comment by AlexandrosMor** [comment]
Hello @janaz,

Thank you for opening this issue. There is a pull request for it and we are going to review it as soon as possible.

kind regards,
Alexandros
Adyen

**Comment by senturkozer** [comment]
Hi. Do you have any plans regarding this issue?

**Comment by jillingk** [comment]
Hi @senturkozer,

Unfortunately this API has not been fully rolled out yet. Therefore we cannot really provide any support for it through our libraries. If you would like more assistance on this I would recommend reaching out to our support team, who can direct you to the right people.

Best, Jilling
Adyen
