### ISSUE TITLE
Payment methods request returning validation error

### ISSUE THREAD

**Issue by andma03** [Adyen/adyen-java-api-library#622]
**Java version**: 15.0.2
**Library version**: 17.0.0
**Description**
When using the PaymentMethodsRequest and sending a request with apiVersion 67 one will receive a validation error saying:
'Structure of PaymentMethodsRequest contains the following unknown fields: [enableRealTimeUpdate]'

This field was deprecated but not removed in PaymentMethodsRequest bean.

Using an objectmapper which does not include null values works, but i think deprecated field/s should be removed.

**Comment by AlexandrosMor** [comment]
Hello @andma03,

Thank you for raising this issue. We opened a PR and we are going to merge it as soon as possible.

kind regards,
Alexandros
Adyen
