### ISSUE TITLE
HMACValidator: check for key "hmacSignature" is not null-safe

### ISSUE THREAD

**Issue by tweckert-ecube** [Adyen/adyen-java-api-library#623]
**Describe the bug**
Adyen Java SDK V17, HMACValidator line 82 ff.,

`notificationRequestItem.getAdditionalData().get(HMAC_SIGNATURE).isEmpty()`

is not null safe, because notificationRequestItem.getAdditionalData().get(HMAC_SIGNATURE) returns null if addtionalData does not contain a key "hmacSignature" (or a possible null value for key "hmacSignature").

**How to reproduce**
Additional data contains no key "hmacSignature" or null a value.

**Expected behavior / suggested fix**
```
if (notificationRequestItem.getAdditionalData() == null
	|| !notificationRequestItem.getAdditionalData().containsKey(HMAC_SIGNATURE)
	|| notificationRequestItem.getAdditionalData().get(HMAC_SIGNATURE) == null
	|| notificationRequestItem.getAdditionalData().get(HMAC_SIGNATURE).isEmpty()) {
	throw new IllegalArgumentException("Missing " + HMAC_SIGNATURE);
}
```

**Desktop (please complete the following information):**
 - Java Version: doesn't matter
 - Library Version: Adyen Java SDK V17

**Comment by AlexandrosMor** [comment]
Hello @tweckert-ecube,

Thank you for mentioning this issue. We opened a PR and we are going to merge it as soon as possible.

Regards,
Alexandros
Adyen
