### ISSUE TITLE
request: forward read timeout to terminal when doing Card Acquisition Requests.

### ISSUE THREAD

**Issue by chrisovergaauw** [Adyen/adyen-java-api-library#644]
**Java version**: 11.0.11.j9-adpt
**Library version**: 6.1.0

**Is your feature request related to a problem? Please describe.**
The read timeout configured in the client does nothing to the read timeout in the terminal when issuing CAR requests.
This results in (ErrorConditionType: NotAllowed. Forbidden Request, Service Dialogue CardAcquisitionRequest is in Progress) for subsequent requests.

**Describe the solution you'd like**
The client should send the configured read timeout to the terminal and the terminal should adhere to the same timeout.

**Describe alternatives you've considered**
Alternatively I can configure a read timeout slightly longer than the internally configured 120_000 ms but as soon as you update the terminal firmware with a different read timeout, my integration will need fixing again.

**Additional context**
This occurs often in a completely unattended solution with the UX410 (without numberpad) on a vending machine.

**Comment by AlexandrosMor** [comment]
Hello @chrisovergaauw,

This timeout is on the http client and not on the terminal side. If the terminal does not return a response the http client will timeout. The library does not control the terminal timeout. For this one you could ask help from the support@adyen.com. Feel free to open a new github issue if you have more questions about the library. 

kind regards,
Alexandros
Adyen
