### ISSUE TITLE
getting 422 error code while integrating with hybris

### ISSUE THREAD

**Issue by Ashwini3243** [Adyen/adyen-java-api-library#678]
Hi,
I am trying Adyen integration in hybris for testing. I have followed all steps what ever mentioned in the below link
https://docs.adyen.com/plugins/hybris/set-up-the-add-on

Hereiam getting below error while placing an order

![Capture](https://user-images.githubusercontent.com/39774657/151779248-f7153a19-4b22-45e8-af15-9f409121e045.PNG)
![Capture1](https://user-images.githubusercontent.com/39774657/151779324-8b5e4821-aec1-4583-b3c3-80ecf459f8b3.PNG)

**Comment by wboereboom** [comment]
Hi @Ashwini3243 ,

This Repository deals with the Adyen Backend Library or Java. For questions regardging Plugins or Hybris; please contact [Adyen Support](https://www.adyen.help/hc/en-us)
