### ISSUE TITLE
422 error "Required field 'bankAccount' is not provided

### ISSUE THREAD

**Issue by watchthethrone** [Adyen/adyen-java-api-library#705]
We were using an old version of the adyen java api library (version 7), and we noticed that ach-debit stopped working because of the error below:

{
"status" : 422,
"errorCode" : "14_031",
"message" : "Required field 'bankAccount' is not provided.",
"errorType" : "validation",
"pspReference" : "L9QW64ZH5WD2WN82"
}

This is the request body:
{
   "amount" : {
      "value" : 500,
      "currency" : "USD"
   },
   "lineItems" : [
      {
         
      }
   ],
   "merchantAccount" : "xxxxRedactedECOM",
   "paymentMethod" : {
      "bankAccountNumber" : "123456789",
      "bankLocationId" : "011000138",
      "type" : "ach"
   },
   "reference" : "24882171-158c-47d3-ae99-3525e4b6f485",
   "shopperInteraction" : "Moto",
   "applicationInfo" : {
      "adyenLibrary" : {
         "name" : "adyen-java-api-library",
         "version" : "7.1.0"
      }
   }
}

I see in the request where we are sending "bankAccountNumber".  The reason we do this is because we are just putting a AchDetails object into the paymentMethod.  AchDetails is in com.adyen.model.checkout.details.  Should we no longer use AchDetails?  

**Desktop (please complete the following information):**
 - Java Version: 8
 - Library Version: 7.1.0

**Comment by jillingk** [comment]
Hey @watchthethrone,

Sorry for the delayed respons. You're right in that the way you described is not working anymore. What does work is just adding the type in "paymentMethod". Then create another object "bankAccount" and provide the "bankAccountNumber" plus the other ach details in that object. I'm not sure why it has changed to that structure now, I will dive into to it though and get back to you as soon as I have clear answer!

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hey @watchthethrone,

A quick update. It seems that you're able to do just what you mentioned above, that is adding the achDetails object with all the required bank information in the "paymentMethod". However, we recommend updating the library used as 7.1.0 is quite old now and definitely not supported anymore (I had the same issues you had with 7.1.0). If you update to a more recent version, everything should work perfectly fine.

I'll be closing the ticket now. If you have any additional questions or remarks feel free to do so here!

Best, Jilling
Adyen
