### ISSUE TITLE
[PW-6494] CreateAccountHolderRequest.LegalEntityEnum is missing items

### ISSUE THREAD

**Issue by ramisaa** [Adyen/adyen-java-api-library#707]
**Describe the bug**
The LegalEntityEnum seems to be lagging behind. Based on the documentation there are five different items, but only Business and Individual are currently supported. We'd need at least the NonProfit and PublicCompany. The identical LegalEntityEnum from CreateAccountHolderResponse has all the defined items. 

https://docs.adyen.com/platforms/account-holders-and-accounts?tab=create-public-company-request_5#create-an-account-holder

**Comment by jillingk** [comment]
Hi @ramisaa,

Thanks for letting us know, indeed the models were not up to date anymore. I've created a PR to update it, should be approved rather soon! If there is anything else I can help you with let me know.

Best, Jilling
Adyen
