### ISSUE TITLE
startDropIn API giving null response

### ISSUE THREAD

**Issue by surajsahani** [Adyen/adyen-java-api-library#709]
**Describe the bug**

**How to reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Java Version: [x.y.z]
 - Library Version: [x.y.z]

**Additional context**

**Comment by jillingk** [comment]
Hi @surajsahani,

Can you please provide some more information about the nature of the issue? What versions you're using? Your implementation? This would help us massively in trying to figure out your issue.

Best, Jilling
Adyen

**Comment by surajsahani** [comment]
@jillingk Thanks for responding back. this was project error related to cure . you can find the project link here https://play.google.com/store/apps/details?id=com.apptunix.curecustomer
I am not working in this project anymore. so you can close this issue from my side. but I suggest to cross verify from cure team  hello@getcure.app once. because they are facing real issue at their product. 
thank you.

**Comment by jillingk** [comment]
Hi again,

Thanks for letting us know, we will reach out to them to see what is causing this error. In the meantime I will be closing this ticket. 
Best, Jilling
