### ISSUE TITLE
[PW-6684]Add closeStores support to the Account API

### ISSUE THREAD

**Issue by KlemenGitHub** [Adyen/adyen-java-api-library#717]
Please add support for https://cal-test(live).adyen.com/cal/services/Account/v6/closeStores api call in the Account API.

Regards,
Klemen

**Comment by jillingk** [comment]
Hi @KlemenGitHub,

Thank you for raising this issue. I have created an internal ticket to add the endpoint to the library. Once we have made any progress on it, I will get back to you on this.

Best, Jilling
Adyen

**Comment by JonasJuss** [comment]
@jillingk Any progress on this? Would be great to be able to call the closeStores endpoint through the library 🙏
