### ISSUE TITLE
Error on Instalment type attribute (instalmentType))

### ISSUE THREAD

**Issue by sherasWL** [Adyen/adyen-java-api-library#753]
**Describe the bug**
For Point of sale Terminal API reference we find a mistake on InstalmentType Type on PaymentRequest.
On api documentation it's an attribute with InstalmentType type and on lib it's a List
[Point of Sale Terminal API doc - Instalment](https://docs.adyen.com/point-of-sale/terminal-api-reference#comadyennexoinstalment)

**How to reproduce**
Do a terminal payment with Instalment data on PaymentRequest / paymentData

**Expected behavior**
Terminal must accept payment request

**Screenshots**
No screenshot

**Desktop (please complete the following information):**
 - Java Version: [11.0.10]
 - Library Version: [17.4.0]

**Additional context**
we made a oney card payment with an installmentType set to DEFERRED_INSTALMENTS for test instalment request parameter.
with List we get an error :
errors=At SaleToPOIRequest.PaymentRequest.PaymentData.Instalment.InstalmentType: Expected JSON string

**Comment by jillingk** [comment]
Hi @sherasWL,

Thanks a lot for bringing this issue to our attention and for contributing!

Best, Jilling
Adyen
