### ISSUE TITLE
Can't locate fundingSource

### ISSUE THREAD

**Issue by leokhm** [Adyen/adyen-java-api-library#756]
**Java version**: 52
**Library version**: 17.0.0
**Description**

**Comment by jillingk** [comment]
Hi @leokhm,

I'm not sure I understand your question. Do you mean you cannot find the funding source for specific cards? Or is there some issue you having trying to add **fundingSource** parameter on requests? If you elaborate a little bit more I could offer you some more assistance.

Best, Jilling
Adyen
