### ISSUE TITLE
Deserialization of OnlinePin enum value in AuthenticationMethod is failing

### ISSUE THREAD

**Issue by JonasJuss** [Adyen/adyen-java-api-library#758]
**Describe the bug**
We are using the adyen java library: adyen-java-api-library:17.3.0 and are getting some errors parsing some of the terminal notifiations. 

More specifically we have a problem with parsing an enum value that we receive in this part of the notification:
SaleToPOIResponse.PaymentResponse.PaymentResult.AuthenticationMethod

The enum value we receive is "OnlinePin", shown in the notification below:
![image](https://user-images.githubusercontent.com/6849567/173684595-40874cc9-f332-412e-bc46-2a0474702720.png)

However, the library does not seem to be able to parse this enum value (see the xml annotation below), but can only parse the enum "OnLinePin" (with a capital L in there):
<img width="927" alt="image" src="https://user-images.githubusercontent.com/6849567/173684931-a7935d1b-04a9-43ec-be88-975780540d3c.png">

**Temporary fix**
Since we are not yet relying on the enum value itself, we temporarily fixed the failing notification parsing by telling the object mapper to map unknown enum values to nulls:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/6849567/173685558-c5978f39-1eaf-477c-a363-74e1b7f5a2d1.png">

However, if we suddenly need the actual enum value, we won't be able to get it with this temporary fix.

**Comment by jillingk** [comment]
Hi @JonasJuss,

Thanks for reaching out to us with this issue. It seems that this is a remnant from an old implementation we used for the nexo models. I've opened a quick PR to change this. Let me know if you have other questions/remarks!

Best, Jilling
Adyen
