### ISSUE TITLE
Add support for Adyen Balance Platform API

### ISSUE THREAD

**Issue by SedoTech** [Adyen/adyen-java-api-library#772]
**Java version**: 17
**Library version**: 0.0.0

**Is your feature request related to a problem? Please describe.**
In order to integrate Adyen Balance Platform into our system we need java sdk for the new platform just like it's available for other products of Adyen.

**Describe the solution you'd like**
Add support for Adyen Balance Platform API into current implementation or create new SDK 

**Describe alternatives you've considered**
Implement balance platform client ourselves but this is not a sustainable solution

**Comment by jillingk** [comment]
Hi @SedoTech,

Thank you for reaching out to us! Which endpoint would you like to see added in this library exactly? As far as I know we have most of the Adyen Platform endpoints implemented already and I'm not sure which one in there you would like to see added. 

I did see our team added a new endpoint in the management API called the Adyen Balance Control, is that the one you mean? Let me know so I can help you further!

Best, Jilling
Adyen

**Comment by vemod** [comment]
I reached out your support asking the question and they suggested to create a feature request on github. So I created the ticket here. What I am talking about is "bcl/v2" API. 

We are actively working on integration and already created our own client and dropped usage of this sdk.

**Comment by SedoTech** [comment]
I reached out your support asking the question and they suggested to create a feature request on github. So I created the ticket here. What I am talking about is "bcl/v2" API.

We are actively working on integration and already created our own client and dropped usage of this sdk.
Best, 
David

**Comment by jillingk** [comment]
Hi @SedoTech, 

Yes I realise which endpoints you're talking about now. We have just added the balance API to our node library, since we are now in the process of automating that one. Next on our agenda is this library, so you should also expect the balance API to be added here very soon! In the meanwhile, our apologies for the inconvenience of not having these endpoints ready to go in this library.

 Best, Jilling
Adyen
