### ISSUE TITLE
Support newest version of Payout API

### ISSUE THREAD

**Issue by luggi961** [Adyen/adyen-java-api-library#773]
**Java version**: 11.0.0
**Library version**: 18.0.0

**Is your feature request related to a problem? Please describe.**
Is there a reason why this library uses Payout API v51? Latest version is v68. 
Is this library updated regularly to ensure that the latest versions of all APIs are used?

**Describe the solution you'd like**
Migrate Payout API to latest version.

**Comment by jillingk** [comment]
Hi @luggi961,

Thanks for reaching out to us with this. We're actually in the middle of an automation process for this library, which will update the API versions and corresponding models automatically with every internal API release. This is actually also the reason why as of yet we are running a bit behind on some endpoints. Our apologies for the inconvenience this might cause you. 

Is there any specific functionality regarding the Payout API v68 you would like to use, that's currently not in the library? If so we could always take a look if we can implement a quick fix, or you could consider contributing.

Best, Jilling
Adyen
