### ISSUE TITLE
 CountryCode sent by adyen java api and Include Shopper Country are different

### ISSUE THREAD

**Issue by pkgonan** [Adyen/adyen-java-api-library#801]
Hi.

I am using Adyen Java 1.8.10 to call Adyen Checkout API v69.
It uses the Create Session API and makes the request as shown below.

At this time, request.countryCode is sent to JO (Jordan).

If you look at CreateCheckoutSessionRequest Class, there are shopperReference and shopperLocale, but no shopperCountry.

Is the countryCode provided by CreateCheckoutSessionRequest the same as shopperCountry?

Please Check
* [Adyen Webhook Additional Setting Document](https://docs.adyen.com/development-resources/webhooks/additional-settings) 
* Include Shopper Country - Receive the country of the shopper, as passed in the payment request. This is formatted using the [ISO-3166 alpha-2](https://www.iso.org/iso-3166-country-codes.html) standard.
<img width="878" alt="스크린샷 2022-09-04 오후 5 16 05" src="https://user-images.githubusercontent.com/15858772/188304197-769112c9-e479-4fce-b166-c93c2b7288b3.png">

```
    private fun AdyenDropInPaymentV1.toCreateCheckoutSessionRequest(configuration: AdyenConfigurationV1): CreateCheckoutSessionRequest {
        val request = CreateCheckoutSessionRequest()
        request.merchantAccount = configuration.getMerchantAccount()
        request.amount = getAmount().toAdyenAmount()
        request.shopperReference = getId().getApplicationId().toString()
        request.reference = getId().getId().toString()
        request.returnUrl = getReturnUrl().toExternalForm()
        request.shopperLocale = getLocale()
        request.countryCode = getCountryCode()
        request.channel = CreateCheckoutSessionRequest.ChannelEnum.WEB

        return request
    }

```
**As a result of receiving the Adyen AUTHORISATION event, the shopperCountry is sent to KR, not JO, as shown below.**

```
AdyenEventRequest(live=false, notificationItemContainers=[AdyenEventItemContainerRequest(notificationItem=AdyenEventItemRequest(success=true, eventCode=AUTHORISATION, amount=AdyenAmountRequest(currency=JOD, value=100556), eventDate=2022-09-04T07:44:01Z, merchantAccountCode=Hyperconnect2021ECOM, merchantReference=1ed2c255-27c8-6793-8078-016057fd1105, pspReference=MCXLQ2V7TSGLNK82, originalReference=null, reason=041078:0002:03/2030, paymentMethod=amex, operations=[CANCEL, CAPTURE, REFUND], additionalData={expiryDate=03/2030, issuerCountry=NL, authCode=041078, cardSummary=0002, threeds2.cardEnrolled=false, checkoutSessionId=CSFB1ECE9D82993D91, shopperCountry=KR, checkout.cardAddedBrand=amex}))])
```

**Comment by wboereboom** [comment]
Hi @pkgonan ,

Thanks for raising this issue.
The confusion is understandable. Please refer to the field descriptions in the library and our API documentation which can be found [here](https://docs.adyen.com/api-explorer-beta/Checkout/69/post/sessions#request)
`countryCode` should contain `The shopper's two-letter country code.`. `shopperLocale` is `The combination of a language code and a country code to specify the language to be used in the payment.`

In the notification `shopperCountry` refers to `Country of the shopper.` the description of the webhook models can be found [here](https://docs.adyen.com/api-explorer-beta/Webhooks/1/post/AUTHORISATION#request)

I hope this clarifies things.

Kind Regards,
Wouter
Adyen
