### ISSUE TITLE
Add support for onlinebanking_PL

### ISSUE THREAD

**Issue by ukasiu** [Adyen/adyen-java-api-library#817]
Please add support for https://docs.adyen.com/payment-methods/online-banking-poland

**Comment by jillingk** [comment]
Hi @ukasiu,

Thank you for reaching out to us with this. What seems to be exactly your issue? If you use the checkout endpoints and the following payment method type, you should be able to leverage the Polish online banking:
```
DefaultPaymentMethodDetails paymentMethodDetails = new DefaultPaymentMethodDetails();
paymentMethodDetails.setType("onlineBanking_PL");
paymentsRequest.setPaymentMethod(paymentMethodDetails);
```
Is there any specific errors you receive?

Best, Jilling
Adyen

**Comment by ukasiu** [comment]
Hi @jillingk,

thanks for your response. We are using specific `com.adyen.model.checkout.details.X` classes in our implementation and I though that we would need a specific one for `onlineBanking_PL` as well. I'll let you know, if it works the way you suggested.

Best, Łukasz

**Comment by jillingk** [comment]
Hi @ukasiu,

All good. I understand the confusion, these details classes however are for inherent different payment methods like ApplePay etc. This payment system however uses the conventional payment standards, just over the Polish online banking system.

See this [docs](https://docs.adyen.com/payment-methods/online-banking-poland/api-only?tab=codeBlockonlinebanking_pl_payments_vnQaE_Java_3) tab for more info about the integration. Also please remember to enable the payment method in your Customer Area. 

If you run into anything else, do let me know and I'll try to assist you further!

Best, Jilling
Adyen

**Comment by ukasiu** [comment]
It is indeed working the way you suggested, thanks:)

**Comment by ukasiu** [comment]
BTW. it seems that `DefaultPaymentMethodDetails` got removed in v18

**Comment by jillingk** [comment]
Hi @ukasiu,

That's weird, that object does indeed not exist in the library. I think the docs here are outdated. Can you try the same implementation with ```paymentMethodDetails``` or ```paymentMethod instead of ```defaultPaymentMethodDetails```? Let me know if that works. In the ```paymentsRequest```, you should also be able to set the ```shopperEmail```.

**Comment by ukasiu** [comment]
Where do I find `paymentMethodDetails` or `paymentMethod`? Which class do you mean?

**Comment by ukasiu** [comment]
NVM, I thought `shopperEmail` is on the payment method details level, not on the request level.
