### ISSUE TITLE
et this

### ISSUE THREAD

**Issue by prijithvrgs** [Adyen/adyen-java-api-library#82]
If the payment is successful, the details are stored, and the recurringDetailReference is created. how can i get this recurringDetailReference. i think it will send back with response, anyone please help me to do this. please reply me back with sample java code for this. Thank you..

**Comment by rikterbeek** [comment]
Hi @prijithvrgs,

You can receive this directly if we turn that on or through a recurring_contract notification. Best to let us know together with your merchantAccount to support@adyen.com so we can configure this for you.

Regards,
Rik
Adyen
