### ISSUE TITLE
Transaction Id is not returned on the /payments response for some local payment methods from DropIn (e.g Klarna, BCMC,)

### ISSUE THREAD

**Issue by ClaudiuDomutaNestle** [Adyen/adyen-java-api-library#833]
Please find below the responses: 

Response of /payments for NaverPay:

class PaymentsResponse {
    additionalData: null
    fraudResult: null
    pspReference: null
    refusalReason: null
    refusalReasonCode: null
    resultCode: RedirectShopper
    serviceError: null
    authResponse: null
    merchantReference: null
    threeDS2Result: null
    amount: null
    order: null
    donationToken: null
    action: CheckoutPaymentsAction{alternativeReference='null', data={acquirerAccountId=91570, amount=10, currency=KRW, notifyUrl=https://test.adyen.com/hpp/notificationAcquirerSimulator.shtml, paymentMethod=kcp_naverpay, returnUrl=https://checkoutshopper-test.adyen.com/checkoutshopper/checkoutPaymentReturn?gpid=GP123E48C2B5DC6863, signature=VRHs2RcaXGnNVeYBNmM02Jc82bU=, transactionId=8516649541630815}, downloadUrl='null', expiresAt='null', initialAmount=null, instructionsUrl='null', issuer='null', maskedTelephoneNumber='null', merchantName='null', merchantReference='null', method='POST', paymentData='null', paymentMethodType='kcp_naverpay', qrCodeData='null', reference='null', shopperEmail='null', shopperName='null', surcharge=null, token='null', totalAmount=null, entity='null', sdkData=null, resendInterval=0, resendMaxAttempts=0, resendUrl='null', redirect=null, authorisationToken='null', subtype='null', beneficiary='null', bic='null', iban='null', shopperStatement='null', type=redirect, url='https://checkoutshopper-test.adyen.com/checkoutshopper/checkoutPaymentRedirect?redirectData=X3XtfGC7%21H4sIAAAAAAAAAIVTYVPiMBD9L%2F16UpIWSunMjQMVkQHRQcD7wAwT2gWqbRLSlLE6%2FPfbIIinp37M7svbvPc2L1Y3LUCyFVwwzazgxVooxuNQxGAF1mMk55xtQUlWWmcWPMlEQd7S2HKI41QoqRBvTJoB9QLi%2FiJOQAjikhgB3VvquJ2aHzrt%2BkXo%2BZ6LnQxUtGZct6JIFNzwDCGXyJmL%2Fgj7CmKcEOlbVmbA9fFNLNoUWFeHaz3kb9J6g5xZLHvlebGiQingUYmc%2FdE9cm0ZKrMCSnYIk8kUVJ4IbgVew5xlmkRMY6HHl2I%2FIy6BDxKUr0pz5iwzFuzLlQe2ZRUkqaQHANIf%2BSzasIlNrB3O%2Bca8aA3Royh0iPo5pAi4h4WpGwGqPFzau%2FCTS8f%2BCJZgNJuLdUIJIXXPaewjECpZJZylt7l8j%2FLr1PNqzXqNeq7jN3xESpaOIC9S%2FQ2U%2BLS%2BT2dTQK5bcZwY51j6ls%2B%2FdtoHl4Y%2FWKhAAtMVwSs6yQC9QfCSpTlYnxI6Uk4%2Fun5yo8c1rNT%2Bhq1LaSaHV52wfzMZz7udYWfUC79An6L0GtbOvEsXik%2BUCWmttcyDWXVWPQaYr4WUoCoarbD32uxIZJ%2F6p8JhmUd71vOVTOLf%2F%2F0cOaS4%2BhC3zRJ9XqAD70BELDXigM%2B77VP9fXauQ10cQE33MeGH3ZLFwt46tu9gopQSSuuu4xJqt7dDuVpePul10i994Uya87A%2F1dv2YjCByTNMNpdj7%2BoPFHnNEGqh4CDpGvRaxG%2Bp7U4f%2BKN5H806%2Fug8yYqUIeWsiirtfK2z1PoqgdRIX4tcB82aT2bVVxSSGd5ZNVZCJtyUX98wq54jZ4p2tzYDchMOyykdXmWbDhOM%2Bhfe3bM3vrsPH2rXpNH0vaW7WMTQrC0JZa7XiBjEjuOBGzUp%2Fu2%2FaRh4DikFAAA%3DCfCykRLBrBtsAshqDhPK96uEN7eU4hzVUIFkVR4WViM%3D', collectionInstitutionNumber='null'}
}

Response of /payments for Klarna/ Bancontact:

class PaymentsResponse {
    additionalData: null
    fraudResult: null
    pspReference: null
    refusalReason: null
    refusalReasonCode: null
    resultCode: RedirectShopper
    serviceError: null
    authResponse: null
    merchantReference: null
    threeDS2Result: null
    amount: null
    order: null
    donationToken: null
    action: CheckoutPaymentsAction{alternativeReference='null', data=null, downloadUrl='null', expiresAt='null', initialAmount=null, instructionsUrl='null', issuer='null', maskedTelephoneNumber='null', merchantName='null', merchantReference='null', method='GET', paymentData='null', paymentMethodType='klarna_paynow', qrCodeData='null', reference='null', shopperEmail='null', shopperName='null', surcharge=null, token='null', totalAmount=null, entity='null', sdkData=null, resendInterval=0, resendMaxAttempts=0, resendUrl='null', redirect=null, authorisationToken='null', subtype='null', beneficiary='null', bic='null', iban='null', shopperStatement='null', type=redirect, url='https://checkoutshopper-test.adyen.com/checkoutshopper/checkoutPaymentRedirect?redirectData=X3XtfGC7%21H4sIAAAAAAAAAIVTa2%2BbQBD8L3xtgeOAAyNVkU2IY6VJHOfhRkKyznA8ZAyX47BLovz3LmArVtMHH3fmZmdnlzdlWjSM05SdU0kV701ZC1rGfhUzxVM2BRUlXXHaltVe%2BaqwnzwXrB5LwDDCWDWQisgDGnnY8JD7BWEPIeDlMRCmc%2BS41si5CILJOLAngQPIlokoo6UcR1HVlJ3ODas5aNbVfQC4YDF0iOSctltWyqMpGr00UBeHZzPQx8QhhvNVoXGcy7wqaXEk804wAWmXYEKskW1ZxHXgA%2F1hIj6o11oNjeHtqjdM12tk2qapumuUqBYhSKV25KouomiU2GuWOHFvMWqEyMvUr0opaNQNIUXDAKqzinMmFixhgpVRF6GJDdPApqG8g9XtMPOb0ikAoQXCfXAFL3cU1qB4BkKoI%2FL8iYnOmeIRmPFfO%2BkDEe0B7UP8X8hH%2FNSnjbreNsEOMoBSiTzNIdN5zU9ZLjE%2BEsUu7uN4aVgtx5%2FWcOwyKyVLBe1ATba8k%2FEvA%2F%2Fq9vFhNQ1ugsXMP%2FF0yt4dM1CI0%2BUnmGxE%2BSgKqGRS8toL9VCPMhZtqkYewlcluNFo3LJSi6rtJ%2FyjcLixRa96lvI8%2FvbHm603eXmIlzdrbYc1FxvEIo7lIsswRhbRFvPvbbFd%2Bs%2F7iVqe3y2XGW4tfzZ9WtkFenV8%2BWz719vtRG7SYZDhyn8fBZaq8YK2qYC9xdqw6mEK1oR6xnnP6W831A26y1znUvlbMEUV0SKraumNwGmoD6xQ77MJ9VhUPC%2B78mAm1M9Au4AUZk%2FX13T%2F%2FOPBXO6dkSkukvP02r3M96%2Fu7d1FFsRx7CaJQ0yMIvhNCGWRgzGjsQWNbGYp7%2B%2B%2FABg704JYBAAA7fexKnWqn7Y712vFagdsJ%2Br0PLrGG6NIqElKy5ohpl8%3D', collectionInstitutionNumber='null'}
}

As you can see for NaverPay(and other payment methods) Adyen returns transactionId information , but for Klarna, Bancontact, etc Adyen doesn’t return this transactionId information. I hope this will help you. Thanks.

Thanks.

**Comment by jillingk** [comment]
Hi @ClaudiuDomutaNestle,

Thanks for reaching out to us. You're right that Klarna/Bancontact will not return this transactionId, but other payment methods do. This is by design since some of those payment methods work a little bit differently from each other. If there is anything specific about it that you're not sure about and need helpt with, be sure to let me know!

Best, Jilling
Adyen
