### ISSUE TITLE
Version 1.4 is not found on Maven Central

### ISSUE THREAD

**Issue by blasterz** [Adyen/adyen-java-api-library#87]
I could only find 1.3 version on Maven Central, not 1.4

**Comment by lancergr** [comment]
Hi @blasterz 

That's right, 1.4 is not currently on master branch and not released yet.
You can use 1.3 though.

Kind Regards,
Giorgos
Adyen

**Comment by blasterz** [comment]
Thank you, I assumed 1.4 since it is in the README
