### ISSUE TITLE
HTTP Exception

### ISSUE THREAD

**Issue by blasterz** [Adyen/adyen-java-api-library#88]
I'm getting HTTP Exception when running the example outlined here: https://github.com/Adyen/adyen-java-sample-code/blob/master/src/com/adyen/examples/api/Library/CreatePaymentAPI.java

Any ideas why?

**Comment by blasterz** [comment]
I tested with JSON API and I received "security 010 Not allowed", that was fixed by the support team.
Thank you

**Comment by lancergr** [comment]
Hi @blasterz 

This means that you are trying to send a payment request with non-encrypted card data.
If you like to enable this permission, please send an e-mail to support@adyen.com with your Web Service Username.

Please keep in mind that processing non-encrypted card data will require PCI compliance for Live systems.


Kind Regards,
Giorgos
Adyen

**Comment by blasterz** [comment]
Is there a way to encrypt the card data from backend ? Or it can only be done from the UI Adyen offers?
Does the PCI compliance still apply if we use tokenization ? (Most likely we will have PCI compliance, just asking)

**Comment by lancergr** [comment]
Hi @blasterz 

We don't offer any library to encrypt them from backend. 
You need to encrypt them client side on shopper's browser using the Client Side Encryption library: https://docs.adyen.com/developers/ecommerce-integration/cards

If you use tokenisation, you don't handle raw card data but a token, so you shouldn't expect the 010 error in this case.

Kind Regards,
Giorgos
Adyen

**Comment by blasterz** [comment]
When you say PCI compliance, do you mean the self certification form of the initial application?
Or something like Security Metrics ?

**Comment by lancergr** [comment]
Hi @blasterz 

You can find more details about the PCI requirements for Client Side Encryption and Direct API (non-encrypted card data) here:
https://www.adyen.com/blog/pci-dss-32-what-you-need-to-know

If you need more details on this that are not related to the PHP library I would suggest to contact support@adyen.com

Kind Regards,
Giorgos
Adyen
