### ISSUE TITLE
Adding support for Idempotency Header

### ISSUE THREAD

**Issue by maratermeshev** [Adyen/adyen-java-api-library#881]
**Java version: 1.8
Library version: 18.1.3
Description**

Support for adding Idempotency-Key via Java API for [CreatePaymentCaptureRequest](https://github.com/Adyen/adyen-java-api-library/blob/acfa9bb7d205cb242ac37583c5cd44c99541b90e/src/main/java/com/adyen/model/checkout/CreatePaymentCaptureRequest.java#L55), [CreatePaymentRefundRequest](https://github.com/Adyen/adyen-java-api-library/blob/acfa9bb7d205cb242ac37583c5cd44c99541b90e/src/main/java/com/adyen/model/checkout/CreatePaymentRefundRequest.java#L55) and [CreatePaymentCancelRequest](https://github.com/Adyen/adyen-java-api-library/blob/acfa9bb7d205cb242ac37583c5cd44c99541b90e/src/main/java/com/adyen/model/checkout/CreatePaymentCancelRequest.java#L50).

The [example](https://docs.adyen.com/development-resources/api-idempotency?tab=codeBlockpayments_idempotency_jquK8_Java_3#enable-idempotency) shows how to set idempotency key in [RequestOptions](https://github.com/Adyen/adyen-java-api-library/blob/bc2fdcd47b4341f66423af572bc0b536c788e2fa/src/main/java/com/adyen/model/RequestOptions.java#L3) and how to [add RequestOptions to PaymentsRequest](
https://github.com/Adyen/adyen-java-api-library/blob/fdade3c63ce45c1c5659dfb19af8612e89bdbbb7/src/main/java/com/adyen/service/Checkout.java#L106).

 [CreatePaymentCaptureRequest](https://github.com/Adyen/adyen-java-api-library/blob/acfa9bb7d205cb242ac37583c5cd44c99541b90e/src/main/java/com/adyen/model/checkout/CreatePaymentCaptureRequest.java#L55), [CreatePaymentRefundRequest](https://github.com/Adyen/adyen-java-api-library/blob/acfa9bb7d205cb242ac37583c5cd44c99541b90e/src/main/java/com/adyen/model/checkout/CreatePaymentRefundRequest.java#L55) and [CreatePaymentCancelRequest](https://github.com/Adyen/adyen-java-api-library/blob/acfa9bb7d205cb242ac37583c5cd44c99541b90e/src/main/java/com/adyen/model/checkout/CreatePaymentCancelRequest.java#L50) lack such functionality. Methods [paymentsCaptures](https://github.com/Adyen/adyen-java-api-library/blob/fdade3c63ce45c1c5659dfb19af8612e89bdbbb7/src/main/java/com/adyen/service/Checkout.java#L226), [paymentsRefunds](https://github.com/Adyen/adyen-java-api-library/blob/fdade3c63ce45c1c5659dfb19af8612e89bdbbb7/src/main/java/com/adyen/service/Checkout.java#L304) and [paymentsCancels](https://github.com/Adyen/adyen-java-api-library/blob/fdade3c63ce45c1c5659dfb19af8612e89bdbbb7/src/main/java/com/adyen/service/Checkout.java#L246) don't accept [RequestOptions](https://github.com/Adyen/adyen-java-api-library/blob/bc2fdcd47b4341f66423af572bc0b536c788e2fa/src/main/java/com/adyen/model/RequestOptions.java#L3).

**Comment by jillingk** [comment]
Hi @maratermeshev,

Thanks a lot for reaching out to us with this issue. We have actually added this functionality recently, however these changes still have to be released. We are planning to do a major release very soon though, so stay tuned for that. If the urgency is very high you can also import the develop branch manually, as this branch has the updates you need!

Best, Jilling
Adyen
