### ISSUE TITLE
Util.implode bug

### ISSUE THREAD

**Issue by sanmibuh** [Adyen/adyen-java-api-library#90]
**Java version**: 1.7.0_80
**Library version**: 1.3.0
**Description**

We are using com.adyen.Util.Util#implode method for making the notification signing string.
But we found that if any element of the list is null, it adds `null` string instead of adding empty string.

**Comment by lancergr** [comment]
Hi @sanmibuh 

Thanks for the Pull Request!

It would be interesting for me to know how did you bump into the problem of null Strings in the implode method.
The strings passed there should be escaped and this is done by the function https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/Util/HMACValidator.java#L76 which blanks null strings.

Regards,
Giorgos
Adyen

**Comment by sanmibuh** [comment]
Hi @lancergr 
We are facing the problem when we are checking the notification signature.
But instead of making manually the signingData as described in the example 
https://docs.adyen.com/developers/payment-notifications/signature-for-notifications
we are reusing Util.implode directly.

`public boolean verify(final NotificationRequestItem notificationRequestItem)
      throws SignatureException {

        final List<String> signedDataList = new ArrayList<>(8);
        signedDataList.add(notificationRequestItem.getPspReference());
        signedDataList.add(notificationRequestItem.getOriginalReference());
        signedDataList.add(notificationRequestItem.getMerchantAccountCode());
        signedDataList.add(notificationRequestItem.getMerchantReference());
        final Amount amount = notificationRequestItem.getAmount();
        signedDataList.add(amount.getValue().toString());
        signedDataList.add(amount.getCurrency());
        signedDataList.add(notificationRequestItem.getEventCode());
        signedDataList.add(String.valueOf(notificationRequestItem.isSuccess()));

        /*
            NOTE Util.implode has a bug https://github.com/Adyen/adyen-java-api-library/issues/90
            Until fix, we need to make the signingData with other utility
         */
        //final String signingData = Util.implode(SIGNED_DATA_SEPARATOR, signedDataList);
        final String signingData = StringUtils.join(signedDataList, SIGNED_DATA_SEPARATOR);
         ....`

Apache lang3 StringUtils do the same thing, but we don't want to add another dependency only for this if the Adyen library has the utility for do it :)

Another question of this, is that it could be helpfully overloading methods on HMACValidator utility for notifications:

- calculateHMAC(NotificationRequestItem notificationRequestItem, NotificationRequestItem notificationRequestItem)
- getDataToSign(NotificationRequestItem notificationRequestItem)

This would avoids all clients to do the same stuff

Best,

David Belmez

**Comment by lancergr** [comment]
Hi @sanmibuh 

I like your suggestion! Would you be able to update your PR with that?

Thanks,
Giorgos
Adyen

**Comment by sanmibuh** [comment]
Sure :)

**Comment by sanmibuh** [comment]
Hi @lancergr 
Done. Could you review it, please?

Best,
David Belmez

**Comment by lancergr** [comment]
Merged - #91
