### ISSUE TITLE
Get payment details based on PSPReference

### ISSUE THREAD

**Issue by blasterz** [Adyen/adyen-java-api-library#92]
Hello,

Is there a way to retrieve the payment details given the PSPReference?

Thank you

**Comment by lancergr** [comment]
Hi @blasterz 

There is no any API endpoint for that. The suggested way is to use the Payment Notifications instead:
https://docs.adyen.com/developers/payment-notifications

If you have further questions on the Adyen platform - not related to the Java library, I would advise to contact support@adyen.com

Kind Regards,
Giorgos
Adyen
