### ISSUE TITLE
Fraud Result Notifications

### ISSUE THREAD

**Issue by naattmoo** [Adyen/adyen-java-api-library#922]
When you activate in additionalData the risk section it adds more parameter to additionalData object that comes in the notification. But also adds new parameter that is fraudResult. 

![image](https://user-images.githubusercontent.com/26548314/207892070-100ea4a1-6cd9-4a3a-86bc-936b7a9baeda.png)

In the class com.adyen.model.notification.NotificationRequestItem I can see a method to get additionalData parameter but not to get fraudResult parameter. 

How I can retrieve this parameter?

**Comment by jillingk** [comment]
Hi @naattmoo,

Massive apologies for the delayed response! I'm looking around and it seems this response is actually an API response and not something you would receive through the webhooks. All the fraud information should be populated in the additionalData field in the notificationRequestItem, according to our docs. Do you have an example where you received these parameters in an actual webhook?

Best, Jilling
Adyen
