### ISSUE TITLE
[ITT-76] Add deserializer for notification event hook messages

### ISSUE THREAD

**Issue by jsyrjala** [Adyen/adyen-java-api-library#936]
**Is your feature request related to a problem? Please describe.**

It seems that there is not currently a way to deserialize webhook notifications (or SaleToPOIMessage objects in general). Or at least that feature is undocumented and very well hidden.

These messages are sent by payment terminal to webhook URL and the messages should be handled by code that we implement at Point Of Sales system.

Related URL: https://docs.adyen.com/point-of-sale/design-your-integration/notifications

**Describe the solution you'd like**

There should be a (preferably documented) way to deserialize webhook messages.

**Describe alternatives you've considered**

Alternative is to roll your own serialization for the webhook messages.

**Additional context**

.NET library has the exact same problem https://github.com/Adyen/adyen-dotnet-api-library/issues/717

**Comment by jillingk** [comment]
Hi @jsyrjala,

Thanks for reaching out to us again and apologies for the delayed response, I guess this one flew under the radar a bit. I created a internal ticket to take a look at this issue for this library as well and hopefully we can get it sorted rather soon.

Best, Jilling
Adyen
