### ISSUE TITLE
ApiError does not match the response for the BalancePlatform

### ISSUE THREAD

**Issue by carstensenEmind** [Adyen/adyen-java-api-library#968]
**Describe the bug**
When the request to create a virtual creditcard returns with an error (for example 403) the returning json looks like this:

`{
    "type": "https://docs.adyen.com/errors/forbidden",
    "title": "Forbidden",
    "status": 403,
    "detail": "Not allowed",
    "errorCode": "00_403"
}`
This is also how it is described in the documentation.
When the response gets parsed into an APIException and an APIError some fields go missing, as the structure does not match.
I assume this is because the BalancePlatform was only recently implemented in the api-library and the APIError was implemented to correspond to the structure for the error objects in LegalEntities.

**How to reproduce**
Send a BalencePlatform request that will provoke an error.

**Expected behavior**
I would either expect 

- the error-objects to be the same for all endpoints
- have different exceptions and different APIError Class
- or add all possible fields for all endpoints in the APIError

**Desktop (please complete the following information):**
 - Java Version: [11.0.18]
 - Library Version: [19.0.0-beta]

**Comment by jillingk** [comment]
Hi @carstensenEmind,

Thanks a lot for reaching out to us here. You're completely spot on in that the exceptions are not handled properly for the new endpoints we added recently, something we noticed as well in our pilot. We have fixed this issue now (through a simplified error object), and will release it very soon. 

Best, Jilling
Adyen
