### ISSUE TITLE
ITT-385: The field `requestType` in the JSON string is not defined in the `TransactionRule` properties.

### ISSUE THREAD

**Issue by carstensenEmind** [Adyen/adyen-java-api-library#972]
**Describe the bug**
When trying to create a Transaction Rule to a PaymentInstrument the returning Json includes a field requestType that is not part of the TransactionRule object. (It is not part of the object description https://docs.adyen.com/api-explorer/balanceplatform/2/post/transactionRules as well but it is featured in the example). This leads to an IllegalArgumentException: "The field `requestType` in the JSON string is not defined in the `TransactionRule` properties."  

**How to reproduce**
Create a TransactionRule

**Expected behavior**
The field is either part of the POJO, it gets removed from the response or the mapper accepts and ignores unknown fields.

**Desktop (please complete the following information):**
- Java Version: [11.0.18]
- Library Version: [19.0.0-beta]

**Comment by wboereboom** [comment]
@carstensenEmind ,

Thanks for raising this issue.
We'll work on fixing the API specification on our end in order to resolve this issue.

Kind Regards,
Wouter
Adyen

**Comment by jillingk** [comment]
Hi @carstensenEmind,

I just checked this issue again, and it seems it has been resolved now. It was just a matter of updating our library with the new changes in our configuration API. Thanks again for reaching out to us and please let us know if you run into anything else!

Best, Jilling
Adyen
