### ISSUE TITLE
403 Forbidden in API calls

### ISSUE THREAD

**Issue by ghoroubi** [Adyen/adyen-java-api-library#98]
**Java version**: 8

**Description**

After building and running code , there is no successful response from server, I’m using a test account of the Adyen. I could use setup payment and verify payment APIs in both of java and the Golang code and certainly in the Postman application.
But all of the ThirdPartyPayment and also AccountHolder related APIs are returning 403, forbidden security error code.
In addition I am using the ClientToken as x-api-key in the requests header, without it I see 401-Unauthorized error code. I tried with basic authentication method and failed again.
Please help me to resolve these issues, I appreciate you.

**Comment by rkewlani** [comment]
Sincere apologise for late reply. We have added api key support. Can you please take the latest version and try again ? Please let us know if you issue still persist and you need any help. 
Thanks.

**Comment by rikterbeek** [comment]
Hi @ghoroubi,

I think this issue is solved so we are closing this issue. 

Regards,
Rik
Adyen

**Comment by Shahtaj-Khalid** [comment]
@rkewlani @rikterbeek Hi, i'm facing the same issue, i'm trying to use basic auth and it keeps giving 401 unauthorised  error. can you guide me how to test adyen APIs through postman to check if APIs are working or not?

**Comment by rkewlani** [comment]
Hi @Shahtaj-Khalid ,
Can you please provide more details- 
Are you using API key or username and password ? 
Which end point you are trying to hit ?
Thanks,
Rajni

Adyen

**Comment by dfratte** [comment]
Hi @rkewlani 

I am having the same issue (403 Forbidden every time I want to hit the /paymentMethods endpoint with Java library 2.0.2). I have followed the steps in here (for Java code):

https://docs.adyen.com/developers/checkout/api-integration#step1getavailablepaymentmethods

Details:
- Web service user is Active (ws@Company)
- API key has been generated
- I am trying to hit the /paymentMethods endpoint
- Web service has Checkout WS role enabled
- Web service has merchant account associated
- It doesn't work with the generated API key, nor with the demo server API key.

Any ideas? Let me know if you need more info.

Thanks in advance!

Daniel

**Comment by rkewlani** [comment]
Hi @dfratte ,
It seems some configuration issue. Can you please contact our support team to guide you ?
We only handle technical code related issues only here.

Thanks,
Rajni
Adyen

**Comment by chunlinwang** [comment]
The same problem. Any idea?

**Comment by Mert0-1** [comment]
Same problem any ideas?

**Comment by Aleffio** [comment]
Hi @Mert0-1 ,

Can you please contact our support team?
It might be that your Webservice user is missing some permissions for the operation.

Thanks,
Alessio
Adyen

**Comment by Mert0-1** [comment]
Hey again im sorry for bothering you guys , after when i added test_ to strings i forgot to change number,year,month to EncryptedExpiryYear that is why i couldnt make it work , now working perfectly thanks have a good night

iPhone’umdan gönderildi
