### ISSUE TITLE
NullPointerException when creating BusinessLineInfo

### ISSUE THREAD

**Issue by melvinkoopmans** [Adyen/adyen-java-api-library#991]
**Describe the bug**
When you create a `BusinessLineInfo` object with the required fields from https://docs.adyen.com/api-explorer/legalentity/2/post/businessLines you get a `NullPointerException`.

```java
java.lang.NullPointerException at com.adyen.model.legalentitymanagement.BusinessLineInfo.toJson(BusinessLineInfo.java:442)
```

**How to reproduce**
This test reproduces the issue:

```kotlin
@Test
fun whenCreateBusinessLine_givenLegalEntityId_thenCreatesTheBusinessLine() {
    val info = BusinessLineInfo()
    info.legalEntityId = "LE123"
    info.capability = "receivePayments"
    info.industryCode = "7991"

    println(info.toJson())
}
```

**Expected behavior**
Properly convert the object to JSON.

**Desktop:**
 - Java Version: Java 11
 - Library Version: 19.0.0

**Additional context**

**Comment by jillingk** [comment]
Hi @melvinkoopmans,

Thanks for reaching out to us and apologies for the delayed response. I just tested this in the our newest version 20 of the library and it seemed to work just fine. Any chance you can upgrade and/or verify it works? If not let me know and we'll see if we can solve another way!

Best, Jilling
Adyen
