### ISSUE TITLE
[ITT-482] Cannot deserialise AccountHolder

### ISSUE THREAD

**Issue by pstojek** [Adyen/adyen-java-api-library#996]
We observed an issue in the Adyen java library (v. 19.0.0) which we started using for API Client.  Few days ago everything was working fine, but now we noticed some issue in the library on creating account holders. There is a problem with response deserialization.

The library throws java.lang.IllegalArgumentException: The field `interval` in the JSON string is not defined in the `JSONObject` properties. JSON: {"interval":"daily","maxAmount":{"currency":"EUR","value”:0}}

Usage of library:

```
accountHolders.create(
	AccountHolderInfo()
    		.balancePlatform(“<xxx>”)
    		.description(“<xxx>”)
    		.legalEntityId(“<legalEntity>”)
    		.reference(“<ref>”),
)

```

Received response from endpoint which library fails to deserialize: 

`{"balancePlatform":"some_platform","description":"account holder for <ID>","legalEntityId":"<ID>","reference":"<ID>","capabilities":{"receiveFromPlatformPayments":{"enabled":true,"requested":true,"allowed":true,"verificationStatus":"valid"},"receiveFromBalanceAccount":{"enabled":true,"requested":true,"allowed":true,"verificationStatus":"valid"},"sendToBalanceAccount":{"enabled":true,"requested":true,"allowed":false,"problems":[{"entity":{"id":"<ID>","type":"LegalEntity"},"verificationErrors":[{"code":"2_8067","message":"'Signatory' was missing.","remediatingActions":[{"code":"2_124","message":"Add 'organization.entityAssociations' of type 'signatory' to legal entity"}],"type":"dataMissing"}]}],"verificationStatus":"invalid"},"sendToTransferInstrument":{"enabled":true,"requested":true,"allowed":false,"problems":[{"entity":{"id":"<ID>","type":"LegalEntity"},"verificationErrors":[{"code":"2_8067","message":"'Signatory' was missing.","remediatingActions":[{"code":"2_124","message":"Add 'organization.entityAssociations' of type 'signatory' to legal entity"}],"type":"dataMissing"}]}],"requestedSettings":{"interval":"daily","maxAmount":{"currency":"EUR","value":0}},"verificationStatus":"invalid"}},"id":"<id>","status":"active"}`

Exception is thrown from this line: [https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/model/balanceplatform/AccountHolder.java#L549](https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/model/balanceplatform/AccountHolder.java#L549)

Stacktrace:
```
read:547, AccountHolder$CustomTypeAdapterFactory$1 (com.adyen.model.balanceplatform)
read:538, AccountHolder$CustomTypeAdapterFactory$1 (com.adyen.model.balanceplatform)
read:204, TypeAdapter$1 (com.google.gson)
fromJson:1227, Gson (com.google.gson)
fromJson:1137, Gson (com.google.gson)
fromJson:1047, Gson (com.google.gson)
fromJson:982, Gson (com.google.gson)
fromJson:564, AccountHolder (com.adyen.model.balanceplatform)
create:28, AccountHolders (com.adyen.service.balanceplatform)
```

Looks like it cannot deserialize [requestedSettings](https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/model/balanceplatform/AccountHolderCapability.java#L186) which is field of JSONObject type.

**Comment by jillingk** [comment]
Hi @pstojek,

Thanks a lot for reaching out to us here. I took a quick look and it seems there are some things going wrong in the specs, where we base our models on, which causes the deserialization to fail. I created an internal ticket and we'll be investigating and fixing this asap.

Best, Jilling
Adyen

**Comment by jillingk** [comment]
Hi @pstojek,

We have just released the fix for your issue! Thanks again for bringing this up and let us know if you run into anything else using this library :)

Best, Jilling
Adyen
